// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: auth.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const consumeRefreshToken = `-- name: ConsumeRefreshToken :one
UPDATE refresh_tokens
SET revoked_at = now(), last_used_at = now()
WHERE token_hash = $1
  AND revoked_at IS NULL
  AND expires_at > now()
RETURNING id, tenant_id, user_id
`

type ConsumeRefreshTokenRow struct {
	ID       pgtype.UUID `json:"id"`
	TenantID pgtype.UUID `json:"tenant_id"`
	UserID   pgtype.UUID `json:"user_id"`
}

func (q *Queries) ConsumeRefreshToken(ctx context.Context, tokenHash string) (ConsumeRefreshTokenRow, error) {
	row := q.db.QueryRow(ctx, consumeRefreshToken, tokenHash)
	var i ConsumeRefreshTokenRow
	err := row.Scan(&i.ID, &i.TenantID, &i.UserID)
	return i, err
}

const createRefreshToken = `-- name: CreateRefreshToken :one
INSERT INTO refresh_tokens (
  tenant_id,
  user_id,
  token_hash,
  expires_at
) VALUES (
  $1,
  $2,
  $3,
  $4
)
RETURNING id
`

type CreateRefreshTokenParams struct {
	TenantID  pgtype.UUID        `json:"tenant_id"`
	UserID    pgtype.UUID        `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createRefreshToken,
		arg.TenantID,
		arg.UserID,
		arg.TokenHash,
		arg.ExpiresAt,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const findAuthUserByTenantCode = `-- name: FindAuthUserByTenantCode :one
SELECT
  u.id,
  u.tenant_id,
  u.username,
  u.password_hash,
  u.email,
  u.full_name,
  u.role,
  u.status,
  t.code AS tenant_code,
  t.name AS tenant_name,
  t.status AS tenant_status,
  t.logo_object_key,
  t.login_background_object_key
FROM users u
JOIN tenants t ON t.id = u.tenant_id
WHERE lower(u.username) = lower($1)
  AND lower(t.code) = lower($2)
LIMIT 1
`

type FindAuthUserByTenantCodeParams struct {
	Username   string `json:"username"`
	TenantCode string `json:"tenant_code"`
}

type FindAuthUserByTenantCodeRow struct {
	ID                       pgtype.UUID `json:"id"`
	TenantID                 pgtype.UUID `json:"tenant_id"`
	Username                 string      `json:"username"`
	PasswordHash             string      `json:"password_hash"`
	Email                    pgtype.Text `json:"email"`
	FullName                 pgtype.Text `json:"full_name"`
	Role                     string      `json:"role"`
	Status                   string      `json:"status"`
	TenantCode               string      `json:"tenant_code"`
	TenantName               string      `json:"tenant_name"`
	TenantStatus             string      `json:"tenant_status"`
	LogoObjectKey            pgtype.Text `json:"logo_object_key"`
	LoginBackgroundObjectKey pgtype.Text `json:"login_background_object_key"`
}

func (q *Queries) FindAuthUserByTenantCode(ctx context.Context, arg FindAuthUserByTenantCodeParams) (FindAuthUserByTenantCodeRow, error) {
	row := q.db.QueryRow(ctx, findAuthUserByTenantCode, arg.Username, arg.TenantCode)
	var i FindAuthUserByTenantCodeRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Username,
		&i.PasswordHash,
		&i.Email,
		&i.FullName,
		&i.Role,
		&i.Status,
		&i.TenantCode,
		&i.TenantName,
		&i.TenantStatus,
		&i.LogoObjectKey,
		&i.LoginBackgroundObjectKey,
	)
	return i, err
}

const findAuthUsersByUsername = `-- name: FindAuthUsersByUsername :many
SELECT
  u.id,
  u.tenant_id,
  u.username,
  u.password_hash,
  u.email,
  u.full_name,
  u.role,
  u.status,
  t.code AS tenant_code,
  t.name AS tenant_name,
  t.status AS tenant_status,
  t.logo_object_key,
  t.login_background_object_key
FROM users u
JOIN tenants t ON t.id = u.tenant_id
WHERE lower(u.username) = lower($1)
ORDER BY u.created_at
LIMIT 2
`

type FindAuthUsersByUsernameRow struct {
	ID                       pgtype.UUID `json:"id"`
	TenantID                 pgtype.UUID `json:"tenant_id"`
	Username                 string      `json:"username"`
	PasswordHash             string      `json:"password_hash"`
	Email                    pgtype.Text `json:"email"`
	FullName                 pgtype.Text `json:"full_name"`
	Role                     string      `json:"role"`
	Status                   string      `json:"status"`
	TenantCode               string      `json:"tenant_code"`
	TenantName               string      `json:"tenant_name"`
	TenantStatus             string      `json:"tenant_status"`
	LogoObjectKey            pgtype.Text `json:"logo_object_key"`
	LoginBackgroundObjectKey pgtype.Text `json:"login_background_object_key"`
}

func (q *Queries) FindAuthUsersByUsername(ctx context.Context, username string) ([]FindAuthUsersByUsernameRow, error) {
	rows, err := q.db.Query(ctx, findAuthUsersByUsername, username)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindAuthUsersByUsernameRow{}
	for rows.Next() {
		var i FindAuthUsersByUsernameRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Username,
			&i.PasswordHash,
			&i.Email,
			&i.FullName,
			&i.Role,
			&i.Status,
			&i.TenantCode,
			&i.TenantName,
			&i.TenantStatus,
			&i.LogoObjectKey,
			&i.LoginBackgroundObjectKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAuthUserByID = `-- name: GetAuthUserByID :one
SELECT
  u.id,
  u.tenant_id,
  u.username,
  u.password_hash,
  u.email,
  u.full_name,
  u.role,
  u.status,
  t.code AS tenant_code,
  t.name AS tenant_name,
  t.status AS tenant_status,
  t.logo_object_key,
  t.login_background_object_key
FROM users u
JOIN tenants t ON t.id = u.tenant_id
WHERE u.id = $1
LIMIT 1
`

type GetAuthUserByIDRow struct {
	ID                       pgtype.UUID `json:"id"`
	TenantID                 pgtype.UUID `json:"tenant_id"`
	Username                 string      `json:"username"`
	PasswordHash             string      `json:"password_hash"`
	Email                    pgtype.Text `json:"email"`
	FullName                 pgtype.Text `json:"full_name"`
	Role                     string      `json:"role"`
	Status                   string      `json:"status"`
	TenantCode               string      `json:"tenant_code"`
	TenantName               string      `json:"tenant_name"`
	TenantStatus             string      `json:"tenant_status"`
	LogoObjectKey            pgtype.Text `json:"logo_object_key"`
	LoginBackgroundObjectKey pgtype.Text `json:"login_background_object_key"`
}

func (q *Queries) GetAuthUserByID(ctx context.Context, userID pgtype.UUID) (GetAuthUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getAuthUserByID, userID)
	var i GetAuthUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Username,
		&i.PasswordHash,
		&i.Email,
		&i.FullName,
		&i.Role,
		&i.Status,
		&i.TenantCode,
		&i.TenantName,
		&i.TenantStatus,
		&i.LogoObjectKey,
		&i.LoginBackgroundObjectKey,
	)
	return i, err
}

const getRefreshTokenByHash = `-- name: GetRefreshTokenByHash :one
SELECT id, tenant_id, user_id, token_hash, expires_at, revoked_at
FROM refresh_tokens
WHERE token_hash = $1
LIMIT 1
`

type GetRefreshTokenByHashRow struct {
	ID        pgtype.UUID        `json:"id"`
	TenantID  pgtype.UUID        `json:"tenant_id"`
	UserID    pgtype.UUID        `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
}

func (q *Queries) GetRefreshTokenByHash(ctx context.Context, tokenHash string) (GetRefreshTokenByHashRow, error) {
	row := q.db.QueryRow(ctx, getRefreshTokenByHash, tokenHash)
	var i GetRefreshTokenByHashRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const getTenantBrandingByCode = `-- name: GetTenantBrandingByCode :one
SELECT id, code, name, logo_object_key, login_background_object_key
FROM tenants
WHERE lower(code) = lower($1) AND status = 'active'
LIMIT 1
`

type GetTenantBrandingByCodeRow struct {
	ID                       pgtype.UUID `json:"id"`
	Code                     string      `json:"code"`
	Name                     string      `json:"name"`
	LogoObjectKey            pgtype.Text `json:"logo_object_key"`
	LoginBackgroundObjectKey pgtype.Text `json:"login_background_object_key"`
}

func (q *Queries) GetTenantBrandingByCode(ctx context.Context, tenantCode string) (GetTenantBrandingByCodeRow, error) {
	row := q.db.QueryRow(ctx, getTenantBrandingByCode, tenantCode)
	var i GetTenantBrandingByCodeRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.LogoObjectKey,
		&i.LoginBackgroundObjectKey,
	)
	return i, err
}

const revokeRefreshToken = `-- name: RevokeRefreshToken :exec
UPDATE refresh_tokens
SET revoked_at = COALESCE(revoked_at, now()),
    last_used_at = now()
WHERE token_hash = $1
`

func (q *Queries) RevokeRefreshToken(ctx context.Context, tokenHash string) error {
	_, err := q.db.Exec(ctx, revokeRefreshToken, tokenHash)
	return err
}

const revokeUserRefreshTokens = `-- name: RevokeUserRefreshTokens :exec
UPDATE refresh_tokens
SET revoked_at = COALESCE(revoked_at, now())
WHERE user_id = $1
  AND revoked_at IS NULL
`

func (q *Queries) RevokeUserRefreshTokens(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, revokeUserRefreshTokens, userID)
	return err
}

const setRefreshTokenReplacement = `-- name: SetRefreshTokenReplacement :exec
UPDATE refresh_tokens
SET replaced_by_token_id = $1
WHERE id = $2
  AND revoked_at IS NOT NULL
`

type SetRefreshTokenReplacementParams struct {
	ReplacedByTokenID pgtype.UUID `json:"replaced_by_token_id"`
	TokenID           pgtype.UUID `json:"token_id"`
}

func (q *Queries) SetRefreshTokenReplacement(ctx context.Context, arg SetRefreshTokenReplacementParams) error {
	_, err := q.db.Exec(ctx, setRefreshTokenReplacement, arg.ReplacedByTokenID, arg.TokenID)
	return err
}

const updateAuthUserLogin = `-- name: UpdateAuthUserLogin :exec
UPDATE users
SET last_login_at = now(),
    last_login_ip = $1,
    updated_at = now()
WHERE id = $2
`

type UpdateAuthUserLoginParams struct {
	LoginIp pgtype.Text `json:"login_ip"`
	UserID  pgtype.UUID `json:"user_id"`
}

func (q *Queries) UpdateAuthUserLogin(ctx context.Context, arg UpdateAuthUserLoginParams) error {
	_, err := q.db.Exec(ctx, updateAuthUserLogin, arg.LoginIp, arg.UserID)
	return err
}

const updateAuthUserPassword = `-- name: UpdateAuthUserPassword :exec
UPDATE users
SET password_hash = $1,
    password_changed_at = now(),
    updated_at = now()
WHERE id = $2
`

type UpdateAuthUserPasswordParams struct {
	PasswordHash string      `json:"password_hash"`
	UserID       pgtype.UUID `json:"user_id"`
}

func (q *Queries) UpdateAuthUserPassword(ctx context.Context, arg UpdateAuthUserPasswordParams) error {
	_, err := q.db.Exec(ctx, updateAuthUserPassword, arg.PasswordHash, arg.UserID)
	return err
}
