// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: deployment.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countApplicationVersions = `-- name: CountApplicationVersions :one
SELECT count(*) FROM application_versions v
JOIN projects p ON p.id = v.project_id
WHERE v.project_id = $1 AND v.tenant_id = $2
  AND p.status <> 'deleted' AND v.status <> 'deleted'
`

type CountApplicationVersionsParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	TenantID  pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) CountApplicationVersions(ctx context.Context, arg CountApplicationVersionsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countApplicationVersions, arg.ProjectID, arg.TenantID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createApplicationVersion = `-- name: CreateApplicationVersion :one
INSERT INTO application_versions (
  tenant_id, project_id, version, name, description, status, source_hash,
  artifact_bucket, artifact_key, artifact_hash, artifact_size, manifest,
  created_by, completed_at
)
VALUES (
  $1, $2, $3, $4, $5,
  'ready', $6, $7, $8,
  $9, $10, $11, $12, now()
)
RETURNING id, tenant_id, project_id, version, name, description, status, source_hash, artifact_bucket, artifact_key, artifact_hash, artifact_size, manifest, build_log, error_message, created_by, completed_at, deleted_at, created_at, updated_at
`

type CreateApplicationVersionParams struct {
	TenantID       pgtype.UUID `json:"tenant_id"`
	ProjectID      pgtype.UUID `json:"project_id"`
	Version        string      `json:"version"`
	Name           pgtype.Text `json:"name"`
	Description    pgtype.Text `json:"description"`
	SourceHash     pgtype.Text `json:"source_hash"`
	ArtifactBucket pgtype.Text `json:"artifact_bucket"`
	ArtifactKey    pgtype.Text `json:"artifact_key"`
	ArtifactHash   pgtype.Text `json:"artifact_hash"`
	ArtifactSize   pgtype.Int8 `json:"artifact_size"`
	Manifest       []byte      `json:"manifest"`
	UserID         pgtype.UUID `json:"user_id"`
}

func (q *Queries) CreateApplicationVersion(ctx context.Context, arg CreateApplicationVersionParams) (ApplicationVersion, error) {
	row := q.db.QueryRow(ctx, createApplicationVersion,
		arg.TenantID,
		arg.ProjectID,
		arg.Version,
		arg.Name,
		arg.Description,
		arg.SourceHash,
		arg.ArtifactBucket,
		arg.ArtifactKey,
		arg.ArtifactHash,
		arg.ArtifactSize,
		arg.Manifest,
		arg.UserID,
	)
	var i ApplicationVersion
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ProjectID,
		&i.Version,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.SourceHash,
		&i.ArtifactBucket,
		&i.ArtifactKey,
		&i.ArtifactHash,
		&i.ArtifactSize,
		&i.Manifest,
		&i.BuildLog,
		&i.ErrorMessage,
		&i.CreatedBy,
		&i.CompletedAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createNodeCommand = `-- name: CreateNodeCommand :one
INSERT INTO node_commands (
  tenant_id, node_id, node_deployment_id, project_id, command_type, status, payload
)
VALUES (
  $1, $2, $3, $4,
  $5, 'pending', $6
)
RETURNING id, tenant_id, node_id, node_deployment_id, project_id, command_type, status, payload, attempts, max_attempts, timeout_seconds, requested_at, issued_at, acknowledged_at, completed_at, last_error, created_at, updated_at
`

type CreateNodeCommandParams struct {
	TenantID         pgtype.UUID `json:"tenant_id"`
	NodeID           pgtype.UUID `json:"node_id"`
	NodeDeploymentID pgtype.UUID `json:"node_deployment_id"`
	ProjectID        pgtype.UUID `json:"project_id"`
	CommandType      string      `json:"command_type"`
	Payload          []byte      `json:"payload"`
}

func (q *Queries) CreateNodeCommand(ctx context.Context, arg CreateNodeCommandParams) (NodeCommand, error) {
	row := q.db.QueryRow(ctx, createNodeCommand,
		arg.TenantID,
		arg.NodeID,
		arg.NodeDeploymentID,
		arg.ProjectID,
		arg.CommandType,
		arg.Payload,
	)
	var i NodeCommand
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.NodeID,
		&i.NodeDeploymentID,
		&i.ProjectID,
		&i.CommandType,
		&i.Status,
		&i.Payload,
		&i.Attempts,
		&i.MaxAttempts,
		&i.TimeoutSeconds,
		&i.RequestedAt,
		&i.IssuedAt,
		&i.AcknowledgedAt,
		&i.CompletedAt,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createNodeDeployment = `-- name: CreateNodeDeployment :one
INSERT INTO node_deployments (
  tenant_id, node_id, project_id, application_version_id, version, mode,
  status, runtime_config, deployed_by
)
VALUES (
  $1, $2, $3, $4,
  $5, $6, 'pending', $7, $8
)
RETURNING id, tenant_id, node_id, project_id, application_version_id, version, mode, status, runtime_config, runtime_metrics, deploy_log, error_message, deployed_by, deployed_at, started_at, stopped_at, deleted_at, created_at, updated_at
`

type CreateNodeDeploymentParams struct {
	TenantID             pgtype.UUID `json:"tenant_id"`
	NodeID               pgtype.UUID `json:"node_id"`
	ProjectID            pgtype.UUID `json:"project_id"`
	ApplicationVersionID pgtype.UUID `json:"application_version_id"`
	Version              pgtype.Text `json:"version"`
	Mode                 string      `json:"mode"`
	RuntimeConfig        []byte      `json:"runtime_config"`
	UserID               pgtype.UUID `json:"user_id"`
}

func (q *Queries) CreateNodeDeployment(ctx context.Context, arg CreateNodeDeploymentParams) (NodeDeployment, error) {
	row := q.db.QueryRow(ctx, createNodeDeployment,
		arg.TenantID,
		arg.NodeID,
		arg.ProjectID,
		arg.ApplicationVersionID,
		arg.Version,
		arg.Mode,
		arg.RuntimeConfig,
		arg.UserID,
	)
	var i NodeDeployment
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.NodeID,
		&i.ProjectID,
		&i.ApplicationVersionID,
		&i.Version,
		&i.Mode,
		&i.Status,
		&i.RuntimeConfig,
		&i.RuntimeMetrics,
		&i.DeployLog,
		&i.ErrorMessage,
		&i.DeployedBy,
		&i.DeployedAt,
		&i.StartedAt,
		&i.StoppedAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteApplicationVersion = `-- name: DeleteApplicationVersion :execrows
UPDATE application_versions
SET status = 'deleted', deleted_at = now(), updated_at = now()
WHERE application_versions.id = $1 AND application_versions.tenant_id = $2
  AND NOT EXISTS (
    SELECT 1 FROM node_deployments d
    WHERE d.application_version_id = application_versions.id
      AND d.deleted_at IS NULL AND d.status IN ('pending', 'deploying', 'running')
  )
`

type DeleteApplicationVersionParams struct {
	VersionID pgtype.UUID `json:"version_id"`
	TenantID  pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) DeleteApplicationVersion(ctx context.Context, arg DeleteApplicationVersionParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteApplicationVersion, arg.VersionID, arg.TenantID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getApplicationVersion = `-- name: GetApplicationVersion :one
SELECT v.id, v.tenant_id, v.project_id, v.version, v.name, v.description, v.status, v.source_hash, v.artifact_bucket, v.artifact_key, v.artifact_hash, v.artifact_size, v.manifest, v.build_log, v.error_message, v.created_by, v.completed_at, v.deleted_at, v.created_at, v.updated_at FROM application_versions v
JOIN projects p ON p.id = v.project_id
WHERE v.id = $1 AND v.tenant_id = $2
  AND p.status <> 'deleted' AND v.status <> 'deleted'
LIMIT 1
`

type GetApplicationVersionParams struct {
	VersionID pgtype.UUID `json:"version_id"`
	TenantID  pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) GetApplicationVersion(ctx context.Context, arg GetApplicationVersionParams) (ApplicationVersion, error) {
	row := q.db.QueryRow(ctx, getApplicationVersion, arg.VersionID, arg.TenantID)
	var i ApplicationVersion
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ProjectID,
		&i.Version,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.SourceHash,
		&i.ArtifactBucket,
		&i.ArtifactKey,
		&i.ArtifactHash,
		&i.ArtifactSize,
		&i.Manifest,
		&i.BuildLog,
		&i.ErrorMessage,
		&i.CreatedBy,
		&i.CompletedAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getApprovedDeploymentNode = `-- name: GetApprovedDeploymentNode :one
SELECT id, tenant_id, name, code, node_type, status, approval_status, registration_token_hash, agent_version, os, architecture, hostname, ip_address, capabilities, metrics, metadata, last_heartbeat_at, approved_at, approved_by, rejected_at, rejected_by, created_at, updated_at FROM nodes
WHERE id = $1 AND tenant_id = $2
  AND approval_status = 'approved' AND status <> 'disabled'
LIMIT 1
`

type GetApprovedDeploymentNodeParams struct {
	NodeID   pgtype.UUID `json:"node_id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) GetApprovedDeploymentNode(ctx context.Context, arg GetApprovedDeploymentNodeParams) (Node, error) {
	row := q.db.QueryRow(ctx, getApprovedDeploymentNode, arg.NodeID, arg.TenantID)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Code,
		&i.NodeType,
		&i.Status,
		&i.ApprovalStatus,
		&i.RegistrationTokenHash,
		&i.AgentVersion,
		&i.Os,
		&i.Architecture,
		&i.Hostname,
		&i.IpAddress,
		&i.Capabilities,
		&i.Metrics,
		&i.Metadata,
		&i.LastHeartbeatAt,
		&i.ApprovedAt,
		&i.ApprovedBy,
		&i.RejectedAt,
		&i.RejectedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getNodeDeployment = `-- name: GetNodeDeployment :one
SELECT d.id, d.tenant_id, d.node_id, d.project_id, d.application_version_id, d.version, d.mode, d.status, d.runtime_config, d.runtime_metrics, d.deploy_log, d.error_message, d.deployed_by, d.deployed_at, d.started_at, d.stopped_at, d.deleted_at, d.created_at, d.updated_at FROM node_deployments d
WHERE d.id = $1 AND d.tenant_id = $2
  AND d.deleted_at IS NULL
LIMIT 1
`

type GetNodeDeploymentParams struct {
	NodeDeploymentID pgtype.UUID `json:"node_deployment_id"`
	TenantID         pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) GetNodeDeployment(ctx context.Context, arg GetNodeDeploymentParams) (NodeDeployment, error) {
	row := q.db.QueryRow(ctx, getNodeDeployment, arg.NodeDeploymentID, arg.TenantID)
	var i NodeDeployment
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.NodeID,
		&i.ProjectID,
		&i.ApplicationVersionID,
		&i.Version,
		&i.Mode,
		&i.Status,
		&i.RuntimeConfig,
		&i.RuntimeMetrics,
		&i.DeployLog,
		&i.ErrorMessage,
		&i.DeployedBy,
		&i.DeployedAt,
		&i.StartedAt,
		&i.StoppedAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listApplicationVersions = `-- name: ListApplicationVersions :many
SELECT v.id, v.tenant_id, v.project_id, v.version, v.name, v.description, v.status, v.source_hash, v.artifact_bucket, v.artifact_key, v.artifact_hash, v.artifact_size, v.manifest, v.build_log, v.error_message, v.created_by, v.completed_at, v.deleted_at, v.created_at, v.updated_at FROM application_versions v
JOIN projects p ON p.id = v.project_id
WHERE v.project_id = $1 AND v.tenant_id = $2
  AND p.status <> 'deleted' AND v.status <> 'deleted'
ORDER BY v.created_at DESC
LIMIT $4 OFFSET $3
`

type ListApplicationVersionsParams struct {
	ProjectID  pgtype.UUID `json:"project_id"`
	TenantID   pgtype.UUID `json:"tenant_id"`
	PageOffset int32       `json:"page_offset"`
	PageLimit  int32       `json:"page_limit"`
}

func (q *Queries) ListApplicationVersions(ctx context.Context, arg ListApplicationVersionsParams) ([]ApplicationVersion, error) {
	rows, err := q.db.Query(ctx, listApplicationVersions,
		arg.ProjectID,
		arg.TenantID,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ApplicationVersion{}
	for rows.Next() {
		var i ApplicationVersion
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ProjectID,
			&i.Version,
			&i.Name,
			&i.Description,
			&i.Status,
			&i.SourceHash,
			&i.ArtifactBucket,
			&i.ArtifactKey,
			&i.ArtifactHash,
			&i.ArtifactSize,
			&i.Manifest,
			&i.BuildLog,
			&i.ErrorMessage,
			&i.CreatedBy,
			&i.CompletedAt,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectNodeDeployments = `-- name: ListProjectNodeDeployments :many
SELECT d.id, d.tenant_id, d.node_id, d.project_id, d.application_version_id, d.version, d.mode, d.status, d.runtime_config, d.runtime_metrics, d.deploy_log, d.error_message, d.deployed_by, d.deployed_at, d.started_at, d.stopped_at, d.deleted_at, d.created_at, d.updated_at, n.name AS node_name, n.status AS node_status, n.ip_address,
       p.name AS project_name, p.code AS project_code,
       v.artifact_hash, v.manifest
FROM node_deployments d
JOIN nodes n ON n.id = d.node_id
JOIN projects p ON p.id = d.project_id
LEFT JOIN application_versions v ON v.id = d.application_version_id
WHERE d.project_id = $1 AND d.tenant_id = $2
  AND d.deleted_at IS NULL AND d.status <> 'removed'
ORDER BY d.created_at DESC
`

type ListProjectNodeDeploymentsParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	TenantID  pgtype.UUID `json:"tenant_id"`
}

type ListProjectNodeDeploymentsRow struct {
	ID                   pgtype.UUID        `json:"id"`
	TenantID             pgtype.UUID        `json:"tenant_id"`
	NodeID               pgtype.UUID        `json:"node_id"`
	ProjectID            pgtype.UUID        `json:"project_id"`
	ApplicationVersionID pgtype.UUID        `json:"application_version_id"`
	Version              pgtype.Text        `json:"version"`
	Mode                 string             `json:"mode"`
	Status               string             `json:"status"`
	RuntimeConfig        []byte             `json:"runtime_config"`
	RuntimeMetrics       []byte             `json:"runtime_metrics"`
	DeployLog            pgtype.Text        `json:"deploy_log"`
	ErrorMessage         pgtype.Text        `json:"error_message"`
	DeployedBy           pgtype.UUID        `json:"deployed_by"`
	DeployedAt           pgtype.Timestamptz `json:"deployed_at"`
	StartedAt            pgtype.Timestamptz `json:"started_at"`
	StoppedAt            pgtype.Timestamptz `json:"stopped_at"`
	DeletedAt            pgtype.Timestamptz `json:"deleted_at"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
	NodeName             string             `json:"node_name"`
	NodeStatus           string             `json:"node_status"`
	IpAddress            pgtype.Text        `json:"ip_address"`
	ProjectName          string             `json:"project_name"`
	ProjectCode          string             `json:"project_code"`
	ArtifactHash         pgtype.Text        `json:"artifact_hash"`
	Manifest             []byte             `json:"manifest"`
}

func (q *Queries) ListProjectNodeDeployments(ctx context.Context, arg ListProjectNodeDeploymentsParams) ([]ListProjectNodeDeploymentsRow, error) {
	rows, err := q.db.Query(ctx, listProjectNodeDeployments, arg.ProjectID, arg.TenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProjectNodeDeploymentsRow{}
	for rows.Next() {
		var i ListProjectNodeDeploymentsRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.NodeID,
			&i.ProjectID,
			&i.ApplicationVersionID,
			&i.Version,
			&i.Mode,
			&i.Status,
			&i.RuntimeConfig,
			&i.RuntimeMetrics,
			&i.DeployLog,
			&i.ErrorMessage,
			&i.DeployedBy,
			&i.DeployedAt,
			&i.StartedAt,
			&i.StoppedAt,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.NodeName,
			&i.NodeStatus,
			&i.IpAddress,
			&i.ProjectName,
			&i.ProjectCode,
			&i.ArtifactHash,
			&i.Manifest,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStaleNodeCommands = `-- name: ListStaleNodeCommands :many
SELECT id, payload, attempts, max_attempts
FROM node_commands
WHERE status IN ('issued', 'acknowledged')
  AND COALESCE(issued_at, requested_at) < now() - timeout_seconds * interval '1 second'
ORDER BY requested_at
LIMIT 100
`

type ListStaleNodeCommandsRow struct {
	ID          pgtype.UUID `json:"id"`
	Payload     []byte      `json:"payload"`
	Attempts    int32       `json:"attempts"`
	MaxAttempts int32       `json:"max_attempts"`
}

func (q *Queries) ListStaleNodeCommands(ctx context.Context) ([]ListStaleNodeCommandsRow, error) {
	rows, err := q.db.Query(ctx, listStaleNodeCommands)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListStaleNodeCommandsRow{}
	for rows.Next() {
		var i ListStaleNodeCommandsRow
		if err := rows.Scan(
			&i.ID,
			&i.Payload,
			&i.Attempts,
			&i.MaxAttempts,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recoverStaleNodeCommand = `-- name: RecoverStaleNodeCommand :execrows
UPDATE node_commands
SET status = CASE WHEN attempts >= max_attempts THEN 'dead_letter' ELSE 'pending' END,
    payload = $1,
    issued_at = CASE WHEN attempts >= max_attempts THEN issued_at ELSE NULL END,
    completed_at = CASE WHEN attempts >= max_attempts THEN now() ELSE completed_at END,
    last_error = '命令执行超时，已由控制面恢复',
    updated_at = now()
WHERE id = $2
  AND status IN ('issued', 'acknowledged')
  AND COALESCE(issued_at, requested_at) < now() - timeout_seconds * interval '1 second'
`

type RecoverStaleNodeCommandParams struct {
	Payload   []byte      `json:"payload"`
	CommandID pgtype.UUID `json:"command_id"`
}

func (q *Queries) RecoverStaleNodeCommand(ctx context.Context, arg RecoverStaleNodeCommandParams) (int64, error) {
	result, err := q.db.Exec(ctx, recoverStaleNodeCommand, arg.Payload, arg.CommandID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const recoverStaleNodeCommands = `-- name: RecoverStaleNodeCommands :execrows
UPDATE node_commands
SET status = CASE WHEN attempts >= max_attempts THEN 'dead_letter' ELSE 'pending' END,
    issued_at = CASE WHEN attempts >= max_attempts THEN issued_at ELSE NULL END,
    completed_at = CASE WHEN attempts >= max_attempts THEN now() ELSE completed_at END,
    last_error = '命令执行超时，已由控制面恢复',
    updated_at = now()
WHERE status IN ('issued', 'acknowledged')
  AND COALESCE(issued_at, requested_at) < now() - timeout_seconds * interval '1 second'
`

func (q *Queries) RecoverStaleNodeCommands(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, recoverStaleNodeCommands)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const removeActiveNodeDeployment = `-- name: RemoveActiveNodeDeployment :exec
UPDATE node_deployments
SET status = 'removed', deleted_at = now(), updated_at = now()
WHERE node_id = $1 AND project_id = $2
  AND deleted_at IS NULL AND status IN ('pending', 'deploying', 'running', 'stopped', 'failed')
`

type RemoveActiveNodeDeploymentParams struct {
	NodeID    pgtype.UUID `json:"node_id"`
	ProjectID pgtype.UUID `json:"project_id"`
}

func (q *Queries) RemoveActiveNodeDeployment(ctx context.Context, arg RemoveActiveNodeDeploymentParams) error {
	_, err := q.db.Exec(ctx, removeActiveNodeDeployment, arg.NodeID, arg.ProjectID)
	return err
}

const updateNodeDeploymentState = `-- name: UpdateNodeDeploymentState :one
UPDATE node_deployments
SET status = $1, updated_at = now(),
    started_at = CASE WHEN $1::text = 'running' THEN now() ELSE started_at END,
    stopped_at = CASE WHEN $1::text = 'stopped' THEN now() ELSE stopped_at END,
    deleted_at = CASE WHEN $1::text = 'removed' THEN now() ELSE deleted_at END
WHERE id = $2 AND tenant_id = $3
RETURNING id, tenant_id, node_id, project_id, application_version_id, version, mode, status, runtime_config, runtime_metrics, deploy_log, error_message, deployed_by, deployed_at, started_at, stopped_at, deleted_at, created_at, updated_at
`

type UpdateNodeDeploymentStateParams struct {
	Status           string      `json:"status"`
	NodeDeploymentID pgtype.UUID `json:"node_deployment_id"`
	TenantID         pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) UpdateNodeDeploymentState(ctx context.Context, arg UpdateNodeDeploymentStateParams) (NodeDeployment, error) {
	row := q.db.QueryRow(ctx, updateNodeDeploymentState, arg.Status, arg.NodeDeploymentID, arg.TenantID)
	var i NodeDeployment
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.NodeID,
		&i.ProjectID,
		&i.ApplicationVersionID,
		&i.Version,
		&i.Mode,
		&i.Status,
		&i.RuntimeConfig,
		&i.RuntimeMetrics,
		&i.DeployLog,
		&i.ErrorMessage,
		&i.DeployedBy,
		&i.DeployedAt,
		&i.StartedAt,
		&i.StoppedAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
