// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: log.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countAuditLogs = `-- name: CountAuditLogs :one
SELECT count(*) FROM audit_logs l
WHERE l.tenant_id = $1
  AND ($2::text = '' OR l.level = $2)
  AND ($3::text = '' OR COALESCE(l.action, '') = $3)
  AND ($4::text = '' OR COALESCE(l.resource, '') = $4)
  AND ($5::text = '' OR l.user_id::text = $5)
  AND ($6::text = '' OR l.message ILIKE '%' || $6 || '%' OR COALESCE(l.action, '') ILIKE '%' || $6 || '%' OR COALESCE(l.resource, '') ILIKE '%' || $6 || '%')
  AND ($7::timestamptz IS NULL OR l.created_at >= $7)
  AND ($8::timestamptz IS NULL OR l.created_at <= $8)
`

type CountAuditLogsParams struct {
	TenantID  pgtype.UUID        `json:"tenant_id"`
	Level     string             `json:"level"`
	Action    string             `json:"action"`
	Resource  string             `json:"resource"`
	UserID    string             `json:"user_id"`
	Keyword   string             `json:"keyword"`
	StartTime pgtype.Timestamptz `json:"start_time"`
	EndTime   pgtype.Timestamptz `json:"end_time"`
}

func (q *Queries) CountAuditLogs(ctx context.Context, arg CountAuditLogsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAuditLogs,
		arg.TenantID,
		arg.Level,
		arg.Action,
		arg.Resource,
		arg.UserID,
		arg.Keyword,
		arg.StartTime,
		arg.EndTime,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAuditLog = `-- name: CreateAuditLog :exec
INSERT INTO audit_logs (
  id, tenant_id, user_id, level, action, resource, resource_id, message,
  request_id, method, path, result, ip, user_agent, metadata, created_at
) VALUES (
  $1, $2, $3, $4, $5,
  $6, $7, $8, $9,
  $10, $11, $12, $13, $14,
  $15, $16
)
`

type CreateAuditLogParams struct {
	ID         pgtype.UUID        `json:"id"`
	TenantID   pgtype.UUID        `json:"tenant_id"`
	UserID     pgtype.UUID        `json:"user_id"`
	Level      string             `json:"level"`
	Action     pgtype.Text        `json:"action"`
	Resource   pgtype.Text        `json:"resource"`
	ResourceID pgtype.Text        `json:"resource_id"`
	Message    string             `json:"message"`
	RequestID  pgtype.Text        `json:"request_id"`
	Method     pgtype.Text        `json:"method"`
	Path       pgtype.Text        `json:"path"`
	Result     pgtype.Text        `json:"result"`
	Ip         pgtype.Text        `json:"ip"`
	UserAgent  pgtype.Text        `json:"user_agent"`
	Metadata   []byte             `json:"metadata"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) error {
	_, err := q.db.Exec(ctx, createAuditLog,
		arg.ID,
		arg.TenantID,
		arg.UserID,
		arg.Level,
		arg.Action,
		arg.Resource,
		arg.ResourceID,
		arg.Message,
		arg.RequestID,
		arg.Method,
		arg.Path,
		arg.Result,
		arg.Ip,
		arg.UserAgent,
		arg.Metadata,
		arg.CreatedAt,
	)
	return err
}

const deleteAuditLogsBefore = `-- name: DeleteAuditLogsBefore :execrows
DELETE FROM audit_logs
WHERE tenant_id = $1 AND created_at < $2
`

type DeleteAuditLogsBeforeParams struct {
	TenantID   pgtype.UUID        `json:"tenant_id"`
	BeforeTime pgtype.Timestamptz `json:"before_time"`
}

func (q *Queries) DeleteAuditLogsBefore(ctx context.Context, arg DeleteAuditLogsBeforeParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAuditLogsBefore, arg.TenantID, arg.BeforeTime)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const exportAuditLogs = `-- name: ExportAuditLogs :many
SELECT l.id, l.tenant_id, l.user_id, l.level, l.action, l.resource, l.resource_id, l.message, l.request_id, l.method, l.path, l.result, l.ip, l.user_agent, l.metadata, l.created_at, u.username, u.full_name
FROM audit_logs l
LEFT JOIN users u ON u.id = l.user_id
WHERE l.tenant_id = $1
  AND ($2::text = '' OR l.level = $2)
  AND ($3::text = '' OR COALESCE(l.action, '') = $3)
  AND ($4::text = '' OR COALESCE(l.resource, '') = $4)
  AND ($5::text = '' OR l.user_id::text = $5)
  AND ($6::text = '' OR l.message ILIKE '%' || $6 || '%' OR COALESCE(l.action, '') ILIKE '%' || $6 || '%' OR COALESCE(l.resource, '') ILIKE '%' || $6 || '%')
  AND ($7::timestamptz IS NULL OR l.created_at >= $7)
  AND ($8::timestamptz IS NULL OR l.created_at <= $8)
ORDER BY l.created_at DESC
LIMIT 10000
`

type ExportAuditLogsParams struct {
	TenantID  pgtype.UUID        `json:"tenant_id"`
	Level     string             `json:"level"`
	Action    string             `json:"action"`
	Resource  string             `json:"resource"`
	UserID    string             `json:"user_id"`
	Keyword   string             `json:"keyword"`
	StartTime pgtype.Timestamptz `json:"start_time"`
	EndTime   pgtype.Timestamptz `json:"end_time"`
}

type ExportAuditLogsRow struct {
	ID         pgtype.UUID        `json:"id"`
	TenantID   pgtype.UUID        `json:"tenant_id"`
	UserID     pgtype.UUID        `json:"user_id"`
	Level      string             `json:"level"`
	Action     pgtype.Text        `json:"action"`
	Resource   pgtype.Text        `json:"resource"`
	ResourceID pgtype.Text        `json:"resource_id"`
	Message    string             `json:"message"`
	RequestID  pgtype.Text        `json:"request_id"`
	Method     pgtype.Text        `json:"method"`
	Path       pgtype.Text        `json:"path"`
	Result     pgtype.Text        `json:"result"`
	Ip         pgtype.Text        `json:"ip"`
	UserAgent  pgtype.Text        `json:"user_agent"`
	Metadata   []byte             `json:"metadata"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	Username   pgtype.Text        `json:"username"`
	FullName   pgtype.Text        `json:"full_name"`
}

func (q *Queries) ExportAuditLogs(ctx context.Context, arg ExportAuditLogsParams) ([]ExportAuditLogsRow, error) {
	rows, err := q.db.Query(ctx, exportAuditLogs,
		arg.TenantID,
		arg.Level,
		arg.Action,
		arg.Resource,
		arg.UserID,
		arg.Keyword,
		arg.StartTime,
		arg.EndTime,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExportAuditLogsRow{}
	for rows.Next() {
		var i ExportAuditLogsRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.UserID,
			&i.Level,
			&i.Action,
			&i.Resource,
			&i.ResourceID,
			&i.Message,
			&i.RequestID,
			&i.Method,
			&i.Path,
			&i.Result,
			&i.Ip,
			&i.UserAgent,
			&i.Metadata,
			&i.CreatedAt,
			&i.Username,
			&i.FullName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAuditLog = `-- name: GetAuditLog :one
SELECT l.id, l.tenant_id, l.user_id, l.level, l.action, l.resource, l.resource_id, l.message, l.request_id, l.method, l.path, l.result, l.ip, l.user_agent, l.metadata, l.created_at, u.username, u.full_name
FROM audit_logs l
LEFT JOIN users u ON u.id = l.user_id
WHERE l.id = $1 AND l.tenant_id = $2
LIMIT 1
`

type GetAuditLogParams struct {
	LogID    pgtype.UUID `json:"log_id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

type GetAuditLogRow struct {
	ID         pgtype.UUID        `json:"id"`
	TenantID   pgtype.UUID        `json:"tenant_id"`
	UserID     pgtype.UUID        `json:"user_id"`
	Level      string             `json:"level"`
	Action     pgtype.Text        `json:"action"`
	Resource   pgtype.Text        `json:"resource"`
	ResourceID pgtype.Text        `json:"resource_id"`
	Message    string             `json:"message"`
	RequestID  pgtype.Text        `json:"request_id"`
	Method     pgtype.Text        `json:"method"`
	Path       pgtype.Text        `json:"path"`
	Result     pgtype.Text        `json:"result"`
	Ip         pgtype.Text        `json:"ip"`
	UserAgent  pgtype.Text        `json:"user_agent"`
	Metadata   []byte             `json:"metadata"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	Username   pgtype.Text        `json:"username"`
	FullName   pgtype.Text        `json:"full_name"`
}

func (q *Queries) GetAuditLog(ctx context.Context, arg GetAuditLogParams) (GetAuditLogRow, error) {
	row := q.db.QueryRow(ctx, getAuditLog, arg.LogID, arg.TenantID)
	var i GetAuditLogRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.Level,
		&i.Action,
		&i.Resource,
		&i.ResourceID,
		&i.Message,
		&i.RequestID,
		&i.Method,
		&i.Path,
		&i.Result,
		&i.Ip,
		&i.UserAgent,
		&i.Metadata,
		&i.CreatedAt,
		&i.Username,
		&i.FullName,
	)
	return i, err
}

const getAuditLogActionStats = `-- name: GetAuditLogActionStats :many
SELECT COALESCE(action, '') AS action, count(*) AS count
FROM audit_logs
WHERE tenant_id = $1
  AND ($2::timestamptz IS NULL OR created_at >= $2)
  AND ($3::timestamptz IS NULL OR created_at <= $3)
GROUP BY action
ORDER BY count(*) DESC
LIMIT 10
`

type GetAuditLogActionStatsParams struct {
	TenantID  pgtype.UUID        `json:"tenant_id"`
	StartTime pgtype.Timestamptz `json:"start_time"`
	EndTime   pgtype.Timestamptz `json:"end_time"`
}

type GetAuditLogActionStatsRow struct {
	Action string `json:"action"`
	Count  int64  `json:"count"`
}

func (q *Queries) GetAuditLogActionStats(ctx context.Context, arg GetAuditLogActionStatsParams) ([]GetAuditLogActionStatsRow, error) {
	rows, err := q.db.Query(ctx, getAuditLogActionStats, arg.TenantID, arg.StartTime, arg.EndTime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAuditLogActionStatsRow{}
	for rows.Next() {
		var i GetAuditLogActionStatsRow
		if err := rows.Scan(&i.Action, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAuditLogLevelStats = `-- name: GetAuditLogLevelStats :many
SELECT level, count(*) AS count
FROM audit_logs
WHERE tenant_id = $1
  AND ($2::timestamptz IS NULL OR created_at >= $2)
  AND ($3::timestamptz IS NULL OR created_at <= $3)
GROUP BY level
`

type GetAuditLogLevelStatsParams struct {
	TenantID  pgtype.UUID        `json:"tenant_id"`
	StartTime pgtype.Timestamptz `json:"start_time"`
	EndTime   pgtype.Timestamptz `json:"end_time"`
}

type GetAuditLogLevelStatsRow struct {
	Level string `json:"level"`
	Count int64  `json:"count"`
}

func (q *Queries) GetAuditLogLevelStats(ctx context.Context, arg GetAuditLogLevelStatsParams) ([]GetAuditLogLevelStatsRow, error) {
	rows, err := q.db.Query(ctx, getAuditLogLevelStats, arg.TenantID, arg.StartTime, arg.EndTime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAuditLogLevelStatsRow{}
	for rows.Next() {
		var i GetAuditLogLevelStatsRow
		if err := rows.Scan(&i.Level, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAuditLogTrendStats = `-- name: GetAuditLogTrendStats :many
SELECT to_char(date_trunc('day', created_at), 'YYYY-MM-DD') AS date, count(*) AS count
FROM audit_logs
WHERE tenant_id = $1
  AND created_at >= COALESCE($2::timestamptz, now() - interval '7 days')
  AND ($3::timestamptz IS NULL OR created_at <= $3)
GROUP BY date_trunc('day', created_at)
ORDER BY date_trunc('day', created_at)
`

type GetAuditLogTrendStatsParams struct {
	TenantID  pgtype.UUID        `json:"tenant_id"`
	StartTime pgtype.Timestamptz `json:"start_time"`
	EndTime   pgtype.Timestamptz `json:"end_time"`
}

type GetAuditLogTrendStatsRow struct {
	Date  string `json:"date"`
	Count int64  `json:"count"`
}

func (q *Queries) GetAuditLogTrendStats(ctx context.Context, arg GetAuditLogTrendStatsParams) ([]GetAuditLogTrendStatsRow, error) {
	rows, err := q.db.Query(ctx, getAuditLogTrendStats, arg.TenantID, arg.StartTime, arg.EndTime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAuditLogTrendStatsRow{}
	for rows.Next() {
		var i GetAuditLogTrendStatsRow
		if err := rows.Scan(&i.Date, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditLogs = `-- name: ListAuditLogs :many
SELECT l.id, l.tenant_id, l.user_id, l.level, l.action, l.resource, l.resource_id, l.message, l.request_id, l.method, l.path, l.result, l.ip, l.user_agent, l.metadata, l.created_at, u.username, u.full_name
FROM audit_logs l
LEFT JOIN users u ON u.id = l.user_id
WHERE l.tenant_id = $1
  AND ($2::text = '' OR l.level = $2)
  AND ($3::text = '' OR COALESCE(l.action, '') = $3)
  AND ($4::text = '' OR COALESCE(l.resource, '') = $4)
  AND ($5::text = '' OR l.user_id::text = $5)
  AND ($6::text = '' OR l.message ILIKE '%' || $6 || '%' OR COALESCE(l.action, '') ILIKE '%' || $6 || '%' OR COALESCE(l.resource, '') ILIKE '%' || $6 || '%')
  AND ($7::timestamptz IS NULL OR l.created_at >= $7)
  AND ($8::timestamptz IS NULL OR l.created_at <= $8)
ORDER BY l.created_at DESC
LIMIT $10 OFFSET $9
`

type ListAuditLogsParams struct {
	TenantID   pgtype.UUID        `json:"tenant_id"`
	Level      string             `json:"level"`
	Action     string             `json:"action"`
	Resource   string             `json:"resource"`
	UserID     string             `json:"user_id"`
	Keyword    string             `json:"keyword"`
	StartTime  pgtype.Timestamptz `json:"start_time"`
	EndTime    pgtype.Timestamptz `json:"end_time"`
	PageOffset int32              `json:"page_offset"`
	PageLimit  int32              `json:"page_limit"`
}

type ListAuditLogsRow struct {
	ID         pgtype.UUID        `json:"id"`
	TenantID   pgtype.UUID        `json:"tenant_id"`
	UserID     pgtype.UUID        `json:"user_id"`
	Level      string             `json:"level"`
	Action     pgtype.Text        `json:"action"`
	Resource   pgtype.Text        `json:"resource"`
	ResourceID pgtype.Text        `json:"resource_id"`
	Message    string             `json:"message"`
	RequestID  pgtype.Text        `json:"request_id"`
	Method     pgtype.Text        `json:"method"`
	Path       pgtype.Text        `json:"path"`
	Result     pgtype.Text        `json:"result"`
	Ip         pgtype.Text        `json:"ip"`
	UserAgent  pgtype.Text        `json:"user_agent"`
	Metadata   []byte             `json:"metadata"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	Username   pgtype.Text        `json:"username"`
	FullName   pgtype.Text        `json:"full_name"`
}

func (q *Queries) ListAuditLogs(ctx context.Context, arg ListAuditLogsParams) ([]ListAuditLogsRow, error) {
	rows, err := q.db.Query(ctx, listAuditLogs,
		arg.TenantID,
		arg.Level,
		arg.Action,
		arg.Resource,
		arg.UserID,
		arg.Keyword,
		arg.StartTime,
		arg.EndTime,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAuditLogsRow{}
	for rows.Next() {
		var i ListAuditLogsRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.UserID,
			&i.Level,
			&i.Action,
			&i.Resource,
			&i.ResourceID,
			&i.Message,
			&i.RequestID,
			&i.Method,
			&i.Path,
			&i.Result,
			&i.Ip,
			&i.UserAgent,
			&i.Metadata,
			&i.CreatedAt,
			&i.Username,
			&i.FullName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentAuditActivities = `-- name: ListRecentAuditActivities :many
SELECT l.id, l.message, l.action, l.created_at, u.id AS user_id, u.username, u.full_name
FROM audit_logs l
LEFT JOIN users u ON u.id = l.user_id
WHERE l.tenant_id = $1
ORDER BY l.created_at DESC
LIMIT $2
`

type ListRecentAuditActivitiesParams struct {
	TenantID  pgtype.UUID `json:"tenant_id"`
	ItemLimit int32       `json:"item_limit"`
}

type ListRecentAuditActivitiesRow struct {
	ID        pgtype.UUID        `json:"id"`
	Message   string             `json:"message"`
	Action    pgtype.Text        `json:"action"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UserID    pgtype.UUID        `json:"user_id"`
	Username  pgtype.Text        `json:"username"`
	FullName  pgtype.Text        `json:"full_name"`
}

func (q *Queries) ListRecentAuditActivities(ctx context.Context, arg ListRecentAuditActivitiesParams) ([]ListRecentAuditActivitiesRow, error) {
	rows, err := q.db.Query(ctx, listRecentAuditActivities, arg.TenantID, arg.ItemLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRecentAuditActivitiesRow{}
	for rows.Next() {
		var i ListRecentAuditActivitiesRow
		if err := rows.Scan(
			&i.ID,
			&i.Message,
			&i.Action,
			&i.CreatedAt,
			&i.UserID,
			&i.Username,
			&i.FullName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
