// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ApplicationVersion struct {
	ID             pgtype.UUID        `json:"id"`
	TenantID       pgtype.UUID        `json:"tenant_id"`
	ProjectID      pgtype.UUID        `json:"project_id"`
	Version        string             `json:"version"`
	Name           pgtype.Text        `json:"name"`
	Description    pgtype.Text        `json:"description"`
	Status         string             `json:"status"`
	SourceHash     pgtype.Text        `json:"source_hash"`
	ArtifactBucket pgtype.Text        `json:"artifact_bucket"`
	ArtifactKey    pgtype.Text        `json:"artifact_key"`
	ArtifactHash   pgtype.Text        `json:"artifact_hash"`
	ArtifactSize   pgtype.Int8        `json:"artifact_size"`
	Manifest       []byte             `json:"manifest"`
	BuildLog       pgtype.Text        `json:"build_log"`
	ErrorMessage   pgtype.Text        `json:"error_message"`
	CreatedBy      pgtype.UUID        `json:"created_by"`
	CompletedAt    pgtype.Timestamptz `json:"completed_at"`
	DeletedAt      pgtype.Timestamptz `json:"deleted_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type AuditLog struct {
	ID         pgtype.UUID        `json:"id"`
	TenantID   pgtype.UUID        `json:"tenant_id"`
	UserID     pgtype.UUID        `json:"user_id"`
	Level      string             `json:"level"`
	Action     pgtype.Text        `json:"action"`
	Resource   pgtype.Text        `json:"resource"`
	ResourceID pgtype.Text        `json:"resource_id"`
	Message    string             `json:"message"`
	RequestID  pgtype.Text        `json:"request_id"`
	Method     pgtype.Text        `json:"method"`
	Path       pgtype.Text        `json:"path"`
	Result     pgtype.Text        `json:"result"`
	Ip         pgtype.Text        `json:"ip"`
	UserAgent  pgtype.Text        `json:"user_agent"`
	Metadata   []byte             `json:"metadata"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type Node struct {
	ID                    pgtype.UUID        `json:"id"`
	TenantID              pgtype.UUID        `json:"tenant_id"`
	Name                  string             `json:"name"`
	Code                  pgtype.Text        `json:"code"`
	NodeType              string             `json:"node_type"`
	Status                string             `json:"status"`
	ApprovalStatus        string             `json:"approval_status"`
	RegistrationTokenHash pgtype.Text        `json:"registration_token_hash"`
	AgentVersion          pgtype.Text        `json:"agent_version"`
	Os                    pgtype.Text        `json:"os"`
	Architecture          pgtype.Text        `json:"architecture"`
	Hostname              pgtype.Text        `json:"hostname"`
	IpAddress             pgtype.Text        `json:"ip_address"`
	Capabilities          []byte             `json:"capabilities"`
	Metrics               []byte             `json:"metrics"`
	Metadata              []byte             `json:"metadata"`
	LastHeartbeatAt       pgtype.Timestamptz `json:"last_heartbeat_at"`
	ApprovedAt            pgtype.Timestamptz `json:"approved_at"`
	ApprovedBy            pgtype.UUID        `json:"approved_by"`
	RejectedAt            pgtype.Timestamptz `json:"rejected_at"`
	RejectedBy            pgtype.UUID        `json:"rejected_by"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
}

type NodeCommand struct {
	ID               pgtype.UUID        `json:"id"`
	TenantID         pgtype.UUID        `json:"tenant_id"`
	NodeID           pgtype.UUID        `json:"node_id"`
	NodeDeploymentID pgtype.UUID        `json:"node_deployment_id"`
	ProjectID        pgtype.UUID        `json:"project_id"`
	CommandType      string             `json:"command_type"`
	Status           string             `json:"status"`
	Payload          []byte             `json:"payload"`
	Attempts         int32              `json:"attempts"`
	MaxAttempts      int32              `json:"max_attempts"`
	TimeoutSeconds   int32              `json:"timeout_seconds"`
	RequestedAt      pgtype.Timestamptz `json:"requested_at"`
	IssuedAt         pgtype.Timestamptz `json:"issued_at"`
	AcknowledgedAt   pgtype.Timestamptz `json:"acknowledged_at"`
	CompletedAt      pgtype.Timestamptz `json:"completed_at"`
	LastError        pgtype.Text        `json:"last_error"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type NodeDeployment struct {
	ID                   pgtype.UUID        `json:"id"`
	TenantID             pgtype.UUID        `json:"tenant_id"`
	NodeID               pgtype.UUID        `json:"node_id"`
	ProjectID            pgtype.UUID        `json:"project_id"`
	ApplicationVersionID pgtype.UUID        `json:"application_version_id"`
	Version              pgtype.Text        `json:"version"`
	Mode                 string             `json:"mode"`
	Status               string             `json:"status"`
	RuntimeConfig        []byte             `json:"runtime_config"`
	RuntimeMetrics       []byte             `json:"runtime_metrics"`
	DeployLog            pgtype.Text        `json:"deploy_log"`
	ErrorMessage         pgtype.Text        `json:"error_message"`
	DeployedBy           pgtype.UUID        `json:"deployed_by"`
	DeployedAt           pgtype.Timestamptz `json:"deployed_at"`
	StartedAt            pgtype.Timestamptz `json:"started_at"`
	StoppedAt            pgtype.Timestamptz `json:"stopped_at"`
	DeletedAt            pgtype.Timestamptz `json:"deleted_at"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}

type Project struct {
	ID            pgtype.UUID        `json:"id"`
	TenantID      pgtype.UUID        `json:"tenant_id"`
	Name          string             `json:"name"`
	Code          string             `json:"code"`
	Description   pgtype.Text        `json:"description"`
	Icon          pgtype.Text        `json:"icon"`
	WorkspacePath string             `json:"workspace_path"`
	Status        string             `json:"status"`
	Visibility    string             `json:"visibility"`
	CreatedBy     pgtype.UUID        `json:"created_by"`
	UpdatedBy     pgtype.UUID        `json:"updated_by"`
	ArchivedAt    pgtype.Timestamptz `json:"archived_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type ProjectGroup struct {
	ID          pgtype.UUID        `json:"id"`
	TenantID    pgtype.UUID        `json:"tenant_id"`
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	SortOrder   int32              `json:"sort_order"`
	CreatedBy   pgtype.UUID        `json:"created_by"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type ProjectGroupMember struct {
	ProjectID pgtype.UUID        `json:"project_id"`
	GroupID   pgtype.UUID        `json:"group_id"`
	SortOrder int32              `json:"sort_order"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type ProjectRole struct {
	ID          pgtype.UUID        `json:"id"`
	ProjectID   pgtype.UUID        `json:"project_id"`
	Code        string             `json:"code"`
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	Status      string             `json:"status"`
	IsBuiltin   bool               `json:"is_builtin"`
	CreatedBy   pgtype.UUID        `json:"created_by"`
	UpdatedBy   pgtype.UUID        `json:"updated_by"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type ProjectRoleGrant struct {
	ID         pgtype.UUID        `json:"id"`
	ProjectID  pgtype.UUID        `json:"project_id"`
	RoleID     pgtype.UUID        `json:"role_id"`
	Capability string             `json:"capability"`
	Effect     string             `json:"effect"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type ProjectRuntimeUser struct {
	ID                pgtype.UUID        `json:"id"`
	ProjectID         pgtype.UUID        `json:"project_id"`
	Username          string             `json:"username"`
	PasswordHash      string             `json:"password_hash"`
	DisplayName       pgtype.Text        `json:"display_name"`
	Email             pgtype.Text        `json:"email"`
	Status            string             `json:"status"`
	IsBuiltinAdmin    bool               `json:"is_builtin_admin"`
	LastLoginAt       pgtype.Timestamptz `json:"last_login_at"`
	PasswordChangedAt pgtype.Timestamptz `json:"password_changed_at"`
	CreatedBy         pgtype.UUID        `json:"created_by"`
	UpdatedBy         pgtype.UUID        `json:"updated_by"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type ProjectTag struct {
	ID          pgtype.UUID        `json:"id"`
	TenantID    pgtype.UUID        `json:"tenant_id"`
	Name        string             `json:"name"`
	Color       pgtype.Text        `json:"color"`
	Description pgtype.Text        `json:"description"`
	SortOrder   int32              `json:"sort_order"`
	CreatedBy   pgtype.UUID        `json:"created_by"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type ProjectTagBinding struct {
	ProjectID pgtype.UUID        `json:"project_id"`
	TagID     pgtype.UUID        `json:"tag_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type ProjectUserRoleBinding struct {
	RuntimeUserID pgtype.UUID        `json:"runtime_user_id"`
	RoleID        pgtype.UUID        `json:"role_id"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type RefreshToken struct {
	ID                pgtype.UUID        `json:"id"`
	TenantID          pgtype.UUID        `json:"tenant_id"`
	UserID            pgtype.UUID        `json:"user_id"`
	TokenHash         string             `json:"token_hash"`
	ExpiresAt         pgtype.Timestamptz `json:"expires_at"`
	RevokedAt         pgtype.Timestamptz `json:"revoked_at"`
	ReplacedByTokenID pgtype.UUID        `json:"replaced_by_token_id"`
	LastUsedAt        pgtype.Timestamptz `json:"last_used_at"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

type Tenant struct {
	ID                       pgtype.UUID        `json:"id"`
	Name                     string             `json:"name"`
	Code                     string             `json:"code"`
	Description              pgtype.Text        `json:"description"`
	Status                   string             `json:"status"`
	ContactEmail             pgtype.Text        `json:"contact_email"`
	ContactPhone             pgtype.Text        `json:"contact_phone"`
	MaxUsers                 int32              `json:"max_users"`
	MaxProjects              int32              `json:"max_projects"`
	MaxStorage               int64              `json:"max_storage"`
	UsedStorage              int64              `json:"used_storage"`
	LogoObjectKey            pgtype.Text        `json:"logo_object_key"`
	LoginBackgroundObjectKey pgtype.Text        `json:"login_background_object_key"`
	CompanyName              pgtype.Text        `json:"company_name"`
	CompanyAddress           pgtype.Text        `json:"company_address"`
	CompanyPhone             pgtype.Text        `json:"company_phone"`
	CompanyWebsite           pgtype.Text        `json:"company_website"`
	Settings                 []byte             `json:"settings"`
	ExpiresAt                pgtype.Timestamptz `json:"expires_at"`
	CreatedAt                pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                pgtype.Timestamptz `json:"updated_at"`
}

type TenantDashboardNote struct {
	ID        pgtype.UUID        `json:"id"`
	TenantID  pgtype.UUID        `json:"tenant_id"`
	Content   string             `json:"content"`
	CreatedBy pgtype.UUID        `json:"created_by"`
	UpdatedBy pgtype.UUID        `json:"updated_by"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID                pgtype.UUID        `json:"id"`
	TenantID          pgtype.UUID        `json:"tenant_id"`
	Username          string             `json:"username"`
	PasswordHash      string             `json:"password_hash"`
	Email             pgtype.Text        `json:"email"`
	Phone             pgtype.Text        `json:"phone"`
	FullName          pgtype.Text        `json:"full_name"`
	Avatar            pgtype.Text        `json:"avatar"`
	Role              string             `json:"role"`
	Status            string             `json:"status"`
	Preferences       []byte             `json:"preferences"`
	LastLoginAt       pgtype.Timestamptz `json:"last_login_at"`
	LastLoginIp       pgtype.Text        `json:"last_login_ip"`
	PasswordChangedAt pgtype.Timestamptz `json:"password_changed_at"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}
