// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: node.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const approveNode = `-- name: ApproveNode :one
UPDATE nodes
SET approval_status = 'approved', status = 'offline', approved_at = now(), approved_by = $1,
    rejected_at = NULL, rejected_by = NULL, updated_at = now()
WHERE id = $2 AND tenant_id = $3
RETURNING id, tenant_id, name, code, node_type, status, approval_status, registration_token_hash, agent_version, os, architecture, hostname, ip_address, capabilities, metrics, metadata, last_heartbeat_at, approved_at, approved_by, rejected_at, rejected_by, created_at, updated_at
`

type ApproveNodeParams struct {
	UserID   pgtype.UUID `json:"user_id"`
	NodeID   pgtype.UUID `json:"node_id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) ApproveNode(ctx context.Context, arg ApproveNodeParams) (Node, error) {
	row := q.db.QueryRow(ctx, approveNode, arg.UserID, arg.NodeID, arg.TenantID)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Code,
		&i.NodeType,
		&i.Status,
		&i.ApprovalStatus,
		&i.RegistrationTokenHash,
		&i.AgentVersion,
		&i.Os,
		&i.Architecture,
		&i.Hostname,
		&i.IpAddress,
		&i.Capabilities,
		&i.Metrics,
		&i.Metadata,
		&i.LastHeartbeatAt,
		&i.ApprovedAt,
		&i.ApprovedBy,
		&i.RejectedAt,
		&i.RejectedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const completeNodeDeploymentCommands = `-- name: CompleteNodeDeploymentCommands :exec
UPDATE node_commands
SET status = $1, completed_at = now(), last_error = $2, updated_at = now()
WHERE node_deployment_id = $3
  AND status IN ('pending', 'issued', 'acknowledged')
`

type CompleteNodeDeploymentCommandsParams struct {
	Status           string      `json:"status"`
	LastError        pgtype.Text `json:"last_error"`
	NodeDeploymentID pgtype.UUID `json:"node_deployment_id"`
}

func (q *Queries) CompleteNodeDeploymentCommands(ctx context.Context, arg CompleteNodeDeploymentCommandsParams) error {
	_, err := q.db.Exec(ctx, completeNodeDeploymentCommands, arg.Status, arg.LastError, arg.NodeDeploymentID)
	return err
}

const countNodes = `-- name: CountNodes :one
SELECT count(*) FROM nodes n
WHERE n.tenant_id = $1
  AND ($2::text = '' OR n.status = $2)
  AND ($3::text = '' OR n.approval_status = $3)
  AND ($4::text = '' OR n.name ILIKE '%' || $4 || '%' OR COALESCE(n.hostname, '') ILIKE '%' || $4 || '%' OR COALESCE(n.ip_address, '') ILIKE '%' || $4 || '%')
`

type CountNodesParams struct {
	TenantID       pgtype.UUID `json:"tenant_id"`
	Status         string      `json:"status"`
	ApprovalStatus string      `json:"approval_status"`
	Keyword        string      `json:"keyword"`
}

func (q *Queries) CountNodes(ctx context.Context, arg CountNodesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countNodes,
		arg.TenantID,
		arg.Status,
		arg.ApprovalStatus,
		arg.Keyword,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteNode = `-- name: DeleteNode :execrows
DELETE FROM nodes WHERE id = $1 AND tenant_id = $2
`

type DeleteNodeParams struct {
	NodeID   pgtype.UUID `json:"node_id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) DeleteNode(ctx context.Context, arg DeleteNodeParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteNode, arg.NodeID, arg.TenantID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getNode = `-- name: GetNode :one
SELECT id, tenant_id, name, code, node_type, status, approval_status, registration_token_hash, agent_version, os, architecture, hostname, ip_address, capabilities, metrics, metadata, last_heartbeat_at, approved_at, approved_by, rejected_at, rejected_by, created_at, updated_at FROM nodes WHERE id = $1 AND tenant_id = $2 LIMIT 1
`

type GetNodeParams struct {
	NodeID   pgtype.UUID `json:"node_id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) GetNode(ctx context.Context, arg GetNodeParams) (Node, error) {
	row := q.db.QueryRow(ctx, getNode, arg.NodeID, arg.TenantID)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Code,
		&i.NodeType,
		&i.Status,
		&i.ApprovalStatus,
		&i.RegistrationTokenHash,
		&i.AgentVersion,
		&i.Os,
		&i.Architecture,
		&i.Hostname,
		&i.IpAddress,
		&i.Capabilities,
		&i.Metrics,
		&i.Metadata,
		&i.LastHeartbeatAt,
		&i.ApprovedAt,
		&i.ApprovedBy,
		&i.RejectedAt,
		&i.RejectedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getNodeApprovalStatus = `-- name: GetNodeApprovalStatus :one
SELECT id, name, status, approval_status, approved_at, rejected_at, updated_at
FROM nodes WHERE id = $1 LIMIT 1
`

type GetNodeApprovalStatusRow struct {
	ID             pgtype.UUID        `json:"id"`
	Name           string             `json:"name"`
	Status         string             `json:"status"`
	ApprovalStatus string             `json:"approval_status"`
	ApprovedAt     pgtype.Timestamptz `json:"approved_at"`
	RejectedAt     pgtype.Timestamptz `json:"rejected_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetNodeApprovalStatus(ctx context.Context, nodeID pgtype.UUID) (GetNodeApprovalStatusRow, error) {
	row := q.db.QueryRow(ctx, getNodeApprovalStatus, nodeID)
	var i GetNodeApprovalStatusRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.ApprovalStatus,
		&i.ApprovedAt,
		&i.RejectedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getNodeByToken = `-- name: GetNodeByToken :one
SELECT id, tenant_id, name, code, node_type, status, approval_status, registration_token_hash, agent_version, os, architecture, hostname, ip_address, capabilities, metrics, metadata, last_heartbeat_at, approved_at, approved_by, rejected_at, rejected_by, created_at, updated_at FROM nodes
WHERE id = $1 AND registration_token_hash = $2
LIMIT 1
`

type GetNodeByTokenParams struct {
	NodeID                pgtype.UUID `json:"node_id"`
	RegistrationTokenHash pgtype.Text `json:"registration_token_hash"`
}

func (q *Queries) GetNodeByToken(ctx context.Context, arg GetNodeByTokenParams) (Node, error) {
	row := q.db.QueryRow(ctx, getNodeByToken, arg.NodeID, arg.RegistrationTokenHash)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Code,
		&i.NodeType,
		&i.Status,
		&i.ApprovalStatus,
		&i.RegistrationTokenHash,
		&i.AgentVersion,
		&i.Os,
		&i.Architecture,
		&i.Hostname,
		&i.IpAddress,
		&i.Capabilities,
		&i.Metrics,
		&i.Metadata,
		&i.LastHeartbeatAt,
		&i.ApprovedAt,
		&i.ApprovedBy,
		&i.RejectedAt,
		&i.RejectedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listNodes = `-- name: ListNodes :many
SELECT n.id, n.tenant_id, n.name, n.code, n.node_type, n.status, n.approval_status,
       n.agent_version, n.os, n.architecture, n.hostname, n.ip_address,
       n.capabilities, n.metrics, n.metadata, n.last_heartbeat_at,
       n.approved_at, n.rejected_at, n.created_at, n.updated_at,
       COALESCE(
         jsonb_agg(
           DISTINCT jsonb_build_object(
             'id', d.id,
             'deploymentId', d.application_version_id,
             'nodeId', d.node_id,
             'projectId', d.project_id,
             'version', d.version,
             'mode', upper(CASE WHEN d.mode = 'development' THEN 'DEV' ELSE 'RELEASE' END),
             'status', d.status,
             'runtimeConfig', d.runtime_config,
             'runtimeMetrics', d.runtime_metrics,
             'errorMessage', d.error_message,
             'createdAt', d.created_at,
             'updatedAt', d.updated_at,
             'project', jsonb_build_object('id', p.id, 'name', p.name, 'code', p.code)
           )
         ) FILTER (WHERE d.id IS NOT NULL),
         '[]'::jsonb
       ) AS deployments
FROM nodes n
LEFT JOIN node_deployments d ON d.node_id = n.id AND d.deleted_at IS NULL AND d.status <> 'removed'
LEFT JOIN projects p ON p.id = d.project_id
WHERE n.tenant_id = $1
  AND ($2::text = '' OR n.status = $2)
  AND ($3::text = '' OR n.approval_status = $3)
  AND ($4::text = '' OR n.name ILIKE '%' || $4 || '%' OR COALESCE(n.hostname, '') ILIKE '%' || $4 || '%' OR COALESCE(n.ip_address, '') ILIKE '%' || $4 || '%')
GROUP BY n.id
ORDER BY n.created_at DESC
LIMIT $6 OFFSET $5
`

type ListNodesParams struct {
	TenantID       pgtype.UUID `json:"tenant_id"`
	Status         string      `json:"status"`
	ApprovalStatus string      `json:"approval_status"`
	Keyword        string      `json:"keyword"`
	PageOffset     int32       `json:"page_offset"`
	PageLimit      int32       `json:"page_limit"`
}

type ListNodesRow struct {
	ID              pgtype.UUID        `json:"id"`
	TenantID        pgtype.UUID        `json:"tenant_id"`
	Name            string             `json:"name"`
	Code            pgtype.Text        `json:"code"`
	NodeType        string             `json:"node_type"`
	Status          string             `json:"status"`
	ApprovalStatus  string             `json:"approval_status"`
	AgentVersion    pgtype.Text        `json:"agent_version"`
	Os              pgtype.Text        `json:"os"`
	Architecture    pgtype.Text        `json:"architecture"`
	Hostname        pgtype.Text        `json:"hostname"`
	IpAddress       pgtype.Text        `json:"ip_address"`
	Capabilities    []byte             `json:"capabilities"`
	Metrics         []byte             `json:"metrics"`
	Metadata        []byte             `json:"metadata"`
	LastHeartbeatAt pgtype.Timestamptz `json:"last_heartbeat_at"`
	ApprovedAt      pgtype.Timestamptz `json:"approved_at"`
	RejectedAt      pgtype.Timestamptz `json:"rejected_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	Deployments     interface{}        `json:"deployments"`
}

func (q *Queries) ListNodes(ctx context.Context, arg ListNodesParams) ([]ListNodesRow, error) {
	rows, err := q.db.Query(ctx, listNodes,
		arg.TenantID,
		arg.Status,
		arg.ApprovalStatus,
		arg.Keyword,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListNodesRow{}
	for rows.Next() {
		var i ListNodesRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.Code,
			&i.NodeType,
			&i.Status,
			&i.ApprovalStatus,
			&i.AgentVersion,
			&i.Os,
			&i.Architecture,
			&i.Hostname,
			&i.IpAddress,
			&i.Capabilities,
			&i.Metrics,
			&i.Metadata,
			&i.LastHeartbeatAt,
			&i.ApprovedAt,
			&i.RejectedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Deployments,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingNodeCommands = `-- name: ListPendingNodeCommands :many
SELECT id, tenant_id, node_id, node_deployment_id, project_id, command_type, status, payload, attempts, max_attempts, timeout_seconds, requested_at, issued_at, acknowledged_at, completed_at, last_error, created_at, updated_at FROM node_commands
WHERE node_id = $1 AND status = 'pending'
ORDER BY requested_at
LIMIT 20
`

func (q *Queries) ListPendingNodeCommands(ctx context.Context, nodeID pgtype.UUID) ([]NodeCommand, error) {
	rows, err := q.db.Query(ctx, listPendingNodeCommands, nodeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NodeCommand{}
	for rows.Next() {
		var i NodeCommand
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.NodeID,
			&i.NodeDeploymentID,
			&i.ProjectID,
			&i.CommandType,
			&i.Status,
			&i.Payload,
			&i.Attempts,
			&i.MaxAttempts,
			&i.TimeoutSeconds,
			&i.RequestedAt,
			&i.IssuedAt,
			&i.AcknowledgedAt,
			&i.CompletedAt,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markNodeCommandIssued = `-- name: MarkNodeCommandIssued :exec
UPDATE node_commands
SET status = 'issued', issued_at = now(), attempts = attempts + 1, updated_at = now()
WHERE id = $1 AND status = 'pending'
`

func (q *Queries) MarkNodeCommandIssued(ctx context.Context, commandID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markNodeCommandIssued, commandID)
	return err
}

const registerNode = `-- name: RegisterNode :one
INSERT INTO nodes (
  id, tenant_id, name, node_type, status, approval_status, registration_token_hash,
  agent_version, ip_address, metadata, approved_at, approved_by
)
VALUES (
  $1, $2, $3, 'edge', $4,
  $5, $6, $7,
  $8, $9, $10, $11
)
ON CONFLICT (id) DO UPDATE SET
  tenant_id = EXCLUDED.tenant_id,
  name = EXCLUDED.name,
  status = EXCLUDED.status,
  approval_status = EXCLUDED.approval_status,
  registration_token_hash = EXCLUDED.registration_token_hash,
  agent_version = EXCLUDED.agent_version,
  ip_address = EXCLUDED.ip_address,
  metadata = EXCLUDED.metadata,
  approved_at = EXCLUDED.approved_at,
  approved_by = EXCLUDED.approved_by,
  rejected_at = NULL,
  rejected_by = NULL,
  updated_at = now()
RETURNING id, tenant_id, name, code, node_type, status, approval_status, registration_token_hash, agent_version, os, architecture, hostname, ip_address, capabilities, metrics, metadata, last_heartbeat_at, approved_at, approved_by, rejected_at, rejected_by, created_at, updated_at
`

type RegisterNodeParams struct {
	NodeID                pgtype.UUID        `json:"node_id"`
	TenantID              pgtype.UUID        `json:"tenant_id"`
	Name                  string             `json:"name"`
	Status                string             `json:"status"`
	ApprovalStatus        string             `json:"approval_status"`
	RegistrationTokenHash pgtype.Text        `json:"registration_token_hash"`
	AgentVersion          pgtype.Text        `json:"agent_version"`
	IpAddress             pgtype.Text        `json:"ip_address"`
	Metadata              []byte             `json:"metadata"`
	ApprovedAt            pgtype.Timestamptz `json:"approved_at"`
	ApprovedBy            pgtype.UUID        `json:"approved_by"`
}

func (q *Queries) RegisterNode(ctx context.Context, arg RegisterNodeParams) (Node, error) {
	row := q.db.QueryRow(ctx, registerNode,
		arg.NodeID,
		arg.TenantID,
		arg.Name,
		arg.Status,
		arg.ApprovalStatus,
		arg.RegistrationTokenHash,
		arg.AgentVersion,
		arg.IpAddress,
		arg.Metadata,
		arg.ApprovedAt,
		arg.ApprovedBy,
	)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Code,
		&i.NodeType,
		&i.Status,
		&i.ApprovalStatus,
		&i.RegistrationTokenHash,
		&i.AgentVersion,
		&i.Os,
		&i.Architecture,
		&i.Hostname,
		&i.IpAddress,
		&i.Capabilities,
		&i.Metrics,
		&i.Metadata,
		&i.LastHeartbeatAt,
		&i.ApprovedAt,
		&i.ApprovedBy,
		&i.RejectedAt,
		&i.RejectedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const rejectNode = `-- name: RejectNode :one
UPDATE nodes
SET approval_status = 'rejected', status = 'rejected', rejected_at = now(), rejected_by = $1,
    approved_at = NULL, approved_by = NULL, updated_at = now()
WHERE id = $2 AND tenant_id = $3
RETURNING id, tenant_id, name, code, node_type, status, approval_status, registration_token_hash, agent_version, os, architecture, hostname, ip_address, capabilities, metrics, metadata, last_heartbeat_at, approved_at, approved_by, rejected_at, rejected_by, created_at, updated_at
`

type RejectNodeParams struct {
	UserID   pgtype.UUID `json:"user_id"`
	NodeID   pgtype.UUID `json:"node_id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) RejectNode(ctx context.Context, arg RejectNodeParams) (Node, error) {
	row := q.db.QueryRow(ctx, rejectNode, arg.UserID, arg.NodeID, arg.TenantID)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Code,
		&i.NodeType,
		&i.Status,
		&i.ApprovalStatus,
		&i.RegistrationTokenHash,
		&i.AgentVersion,
		&i.Os,
		&i.Architecture,
		&i.Hostname,
		&i.IpAddress,
		&i.Capabilities,
		&i.Metrics,
		&i.Metadata,
		&i.LastHeartbeatAt,
		&i.ApprovedAt,
		&i.ApprovedBy,
		&i.RejectedAt,
		&i.RejectedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateNodeHeartbeat = `-- name: UpdateNodeHeartbeat :one
UPDATE nodes
SET status = 'online', metrics = $1, agent_version = $2,
    last_heartbeat_at = now(), updated_at = now()
WHERE id = $3 AND registration_token_hash = $4
  AND approval_status = 'approved'
RETURNING id, tenant_id, name, code, node_type, status, approval_status, registration_token_hash, agent_version, os, architecture, hostname, ip_address, capabilities, metrics, metadata, last_heartbeat_at, approved_at, approved_by, rejected_at, rejected_by, created_at, updated_at
`

type UpdateNodeHeartbeatParams struct {
	Metrics               []byte      `json:"metrics"`
	AgentVersion          pgtype.Text `json:"agent_version"`
	NodeID                pgtype.UUID `json:"node_id"`
	RegistrationTokenHash pgtype.Text `json:"registration_token_hash"`
}

func (q *Queries) UpdateNodeHeartbeat(ctx context.Context, arg UpdateNodeHeartbeatParams) (Node, error) {
	row := q.db.QueryRow(ctx, updateNodeHeartbeat,
		arg.Metrics,
		arg.AgentVersion,
		arg.NodeID,
		arg.RegistrationTokenHash,
	)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Code,
		&i.NodeType,
		&i.Status,
		&i.ApprovalStatus,
		&i.RegistrationTokenHash,
		&i.AgentVersion,
		&i.Os,
		&i.Architecture,
		&i.Hostname,
		&i.IpAddress,
		&i.Capabilities,
		&i.Metrics,
		&i.Metadata,
		&i.LastHeartbeatAt,
		&i.ApprovedAt,
		&i.ApprovedBy,
		&i.RejectedAt,
		&i.RejectedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateNodeOffline = `-- name: UpdateNodeOffline :one
UPDATE nodes
SET status = 'offline', metadata = metadata || $1::jsonb, updated_at = now()
WHERE id = $2 AND registration_token_hash = $3
RETURNING id, tenant_id, name, code, node_type, status, approval_status, registration_token_hash, agent_version, os, architecture, hostname, ip_address, capabilities, metrics, metadata, last_heartbeat_at, approved_at, approved_by, rejected_at, rejected_by, created_at, updated_at
`

type UpdateNodeOfflineParams struct {
	Metadata              []byte      `json:"metadata"`
	NodeID                pgtype.UUID `json:"node_id"`
	RegistrationTokenHash pgtype.Text `json:"registration_token_hash"`
}

func (q *Queries) UpdateNodeOffline(ctx context.Context, arg UpdateNodeOfflineParams) (Node, error) {
	row := q.db.QueryRow(ctx, updateNodeOffline, arg.Metadata, arg.NodeID, arg.RegistrationTokenHash)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Code,
		&i.NodeType,
		&i.Status,
		&i.ApprovalStatus,
		&i.RegistrationTokenHash,
		&i.AgentVersion,
		&i.Os,
		&i.Architecture,
		&i.Hostname,
		&i.IpAddress,
		&i.Capabilities,
		&i.Metrics,
		&i.Metadata,
		&i.LastHeartbeatAt,
		&i.ApprovedAt,
		&i.ApprovedBy,
		&i.RejectedAt,
		&i.RejectedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateNodeReportedDeployment = `-- name: UpdateNodeReportedDeployment :one
UPDATE node_deployments
SET status = $1, error_message = $2, deploy_log = $3,
    deployed_at = CASE WHEN $1::text = 'running' THEN COALESCE(deployed_at, now()) ELSE deployed_at END,
    started_at = CASE WHEN $1::text = 'running' THEN COALESCE($4, now()) ELSE started_at END,
    stopped_at = CASE WHEN $1::text = 'stopped' THEN COALESCE($5, now()) ELSE stopped_at END,
    updated_at = now()
WHERE id = $6 AND node_id = $7
RETURNING id, tenant_id, node_id, project_id, application_version_id, version, mode, status, runtime_config, runtime_metrics, deploy_log, error_message, deployed_by, deployed_at, started_at, stopped_at, deleted_at, created_at, updated_at
`

type UpdateNodeReportedDeploymentParams struct {
	Status           string             `json:"status"`
	ErrorMessage     pgtype.Text        `json:"error_message"`
	Message          pgtype.Text        `json:"message"`
	StartedAt        pgtype.Timestamptz `json:"started_at"`
	StoppedAt        pgtype.Timestamptz `json:"stopped_at"`
	NodeDeploymentID pgtype.UUID        `json:"node_deployment_id"`
	NodeID           pgtype.UUID        `json:"node_id"`
}

func (q *Queries) UpdateNodeReportedDeployment(ctx context.Context, arg UpdateNodeReportedDeploymentParams) (NodeDeployment, error) {
	row := q.db.QueryRow(ctx, updateNodeReportedDeployment,
		arg.Status,
		arg.ErrorMessage,
		arg.Message,
		arg.StartedAt,
		arg.StoppedAt,
		arg.NodeDeploymentID,
		arg.NodeID,
	)
	var i NodeDeployment
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.NodeID,
		&i.ProjectID,
		&i.ApplicationVersionID,
		&i.Version,
		&i.Mode,
		&i.Status,
		&i.RuntimeConfig,
		&i.RuntimeMetrics,
		&i.DeployLog,
		&i.ErrorMessage,
		&i.DeployedBy,
		&i.DeployedAt,
		&i.StartedAt,
		&i.StoppedAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
