// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: project.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countProjects = `-- name: CountProjects :one
SELECT count(DISTINCT p.id)
FROM projects p
LEFT JOIN project_group_members gm ON gm.project_id = p.id
LEFT JOIN project_groups g ON g.id = gm.group_id
WHERE p.tenant_id = $1
  AND p.status <> 'deleted'
  AND (
    $2::boolean
    OR p.created_by = $3
    OR ($4::boolean AND p.visibility = 'internal')
  )
  AND ($5::text = '' OR p.name ILIKE '%' || $5 || '%' OR p.code ILIKE '%' || $5 || '%')
  AND ($6::text = '' OR p.status = $6)
  AND ($7::text = '' OR p.visibility = $7)
  AND ($8::text = '' OR g.id::text = $8)
  AND ($9::text = '' OR EXISTS (SELECT 1 FROM project_tag_bindings filter_tb WHERE filter_tb.project_id = p.id AND filter_tb.tag_id::text = $9))
`

type CountProjectsParams struct {
	TenantID        pgtype.UUID `json:"tenant_id"`
	IsPlatformAdmin bool        `json:"is_platform_admin"`
	ActorID         pgtype.UUID `json:"actor_id"`
	CanReadShared   bool        `json:"can_read_shared"`
	Keyword         string      `json:"keyword"`
	Status          string      `json:"status"`
	Visibility      string      `json:"visibility"`
	GroupID         string      `json:"group_id"`
	TagID           string      `json:"tag_id"`
}

func (q *Queries) CountProjects(ctx context.Context, arg CountProjectsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countProjects,
		arg.TenantID,
		arg.IsPlatformAdmin,
		arg.ActorID,
		arg.CanReadShared,
		arg.Keyword,
		arg.Status,
		arg.Visibility,
		arg.GroupID,
		arg.TagID,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createProject = `-- name: CreateProject :one
INSERT INTO projects (id, tenant_id, name, code, description, icon, workspace_path, status, visibility, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, 'active', $8, $9)
RETURNING id, tenant_id, name, code, description, icon, workspace_path, status, visibility, authoring_epoch, created_by, updated_by, archived_at, created_at, updated_at
`

type CreateProjectParams struct {
	ProjectID     pgtype.UUID `json:"project_id"`
	TenantID      pgtype.UUID `json:"tenant_id"`
	Name          string      `json:"name"`
	Code          string      `json:"code"`
	Description   pgtype.Text `json:"description"`
	Icon          pgtype.Text `json:"icon"`
	WorkspacePath string      `json:"workspace_path"`
	Visibility    string      `json:"visibility"`
	UserID        pgtype.UUID `json:"user_id"`
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, createProject,
		arg.ProjectID,
		arg.TenantID,
		arg.Name,
		arg.Code,
		arg.Description,
		arg.Icon,
		arg.WorkspacePath,
		arg.Visibility,
		arg.UserID,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Code,
		&i.Description,
		&i.Icon,
		&i.WorkspacePath,
		&i.Status,
		&i.Visibility,
		&i.AuthoringEpoch,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createProjectGroup = `-- name: CreateProjectGroup :one
INSERT INTO project_groups (tenant_id, name, description, sort_order, created_by)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, tenant_id, name, description, sort_order, created_by, created_at, updated_at
`

type CreateProjectGroupParams struct {
	TenantID    pgtype.UUID `json:"tenant_id"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	SortOrder   int32       `json:"sort_order"`
	UserID      pgtype.UUID `json:"user_id"`
}

func (q *Queries) CreateProjectGroup(ctx context.Context, arg CreateProjectGroupParams) (ProjectGroup, error) {
	row := q.db.QueryRow(ctx, createProjectGroup,
		arg.TenantID,
		arg.Name,
		arg.Description,
		arg.SortOrder,
		arg.UserID,
	)
	var i ProjectGroup
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Description,
		&i.SortOrder,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createProjectGroupBinding = `-- name: CreateProjectGroupBinding :exec
INSERT INTO project_group_members (project_id, group_id) VALUES ($1, $2)
`

type CreateProjectGroupBindingParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	GroupID   pgtype.UUID `json:"group_id"`
}

func (q *Queries) CreateProjectGroupBinding(ctx context.Context, arg CreateProjectGroupBindingParams) error {
	_, err := q.db.Exec(ctx, createProjectGroupBinding, arg.ProjectID, arg.GroupID)
	return err
}

const createProjectTag = `-- name: CreateProjectTag :one
INSERT INTO project_tags (tenant_id, name, color, description, sort_order, created_by)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, tenant_id, name, color, description, sort_order, created_by, created_at, updated_at
`

type CreateProjectTagParams struct {
	TenantID    pgtype.UUID `json:"tenant_id"`
	Name        string      `json:"name"`
	Color       pgtype.Text `json:"color"`
	Description pgtype.Text `json:"description"`
	SortOrder   int32       `json:"sort_order"`
	UserID      pgtype.UUID `json:"user_id"`
}

func (q *Queries) CreateProjectTag(ctx context.Context, arg CreateProjectTagParams) (ProjectTag, error) {
	row := q.db.QueryRow(ctx, createProjectTag,
		arg.TenantID,
		arg.Name,
		arg.Color,
		arg.Description,
		arg.SortOrder,
		arg.UserID,
	)
	var i ProjectTag
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Color,
		&i.Description,
		&i.SortOrder,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createProjectTagBinding = `-- name: CreateProjectTagBinding :exec
INSERT INTO project_tag_bindings (project_id, tag_id) VALUES ($1, $2)
`

type CreateProjectTagBindingParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	TagID     pgtype.UUID `json:"tag_id"`
}

func (q *Queries) CreateProjectTagBinding(ctx context.Context, arg CreateProjectTagBindingParams) error {
	_, err := q.db.Exec(ctx, createProjectTagBinding, arg.ProjectID, arg.TagID)
	return err
}

const deleteProjectGroup = `-- name: DeleteProjectGroup :execrows
DELETE FROM project_groups WHERE id = $1 AND tenant_id = $2
`

type DeleteProjectGroupParams struct {
	GroupID  pgtype.UUID `json:"group_id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) DeleteProjectGroup(ctx context.Context, arg DeleteProjectGroupParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteProjectGroup, arg.GroupID, arg.TenantID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteProjectGroupBinding = `-- name: DeleteProjectGroupBinding :exec
DELETE FROM project_group_members WHERE project_id = $1
`

func (q *Queries) DeleteProjectGroupBinding(ctx context.Context, projectID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteProjectGroupBinding, projectID)
	return err
}

const deleteProjectTag = `-- name: DeleteProjectTag :execrows
DELETE FROM project_tags WHERE id = $1 AND tenant_id = $2
`

type DeleteProjectTagParams struct {
	TagID    pgtype.UUID `json:"tag_id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) DeleteProjectTag(ctx context.Context, arg DeleteProjectTagParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteProjectTag, arg.TagID, arg.TenantID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteProjectTagBindings = `-- name: DeleteProjectTagBindings :exec
DELETE FROM project_tag_bindings WHERE project_id = $1
`

func (q *Queries) DeleteProjectTagBindings(ctx context.Context, projectID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteProjectTagBindings, projectID)
	return err
}

const getProject = `-- name: GetProject :one
SELECT id, tenant_id, name, code, description, icon, workspace_path, status, visibility, authoring_epoch, created_by, updated_by, archived_at, created_at, updated_at FROM projects WHERE id = $1 AND tenant_id = $2 AND status <> 'deleted' LIMIT 1
`

type GetProjectParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	TenantID  pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) GetProject(ctx context.Context, arg GetProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, getProject, arg.ProjectID, arg.TenantID)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Code,
		&i.Description,
		&i.Icon,
		&i.WorkspacePath,
		&i.Status,
		&i.Visibility,
		&i.AuthoringEpoch,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProjectDeleteImpact = `-- name: GetProjectDeleteImpact :one
WITH input AS (SELECT $1::uuid AS id)
SELECT
  (SELECT count(*) FROM project_runtime_users, input WHERE project_runtime_users.project_id = input.id) AS runtime_user_count,
  (SELECT count(*) FROM project_roles, input WHERE project_roles.project_id = input.id) AS runtime_role_count,
  (SELECT count(*) FROM node_deployments, input WHERE node_deployments.project_id = input.id AND deleted_at IS NULL) AS deployment_count,
  (SELECT count(*) FROM application_versions, input WHERE application_versions.project_id = input.id AND deleted_at IS NULL) AS version_count
`

type GetProjectDeleteImpactRow struct {
	RuntimeUserCount int64 `json:"runtime_user_count"`
	RuntimeRoleCount int64 `json:"runtime_role_count"`
	DeploymentCount  int64 `json:"deployment_count"`
	VersionCount     int64 `json:"version_count"`
}

func (q *Queries) GetProjectDeleteImpact(ctx context.Context, projectID pgtype.UUID) (GetProjectDeleteImpactRow, error) {
	row := q.db.QueryRow(ctx, getProjectDeleteImpact, projectID)
	var i GetProjectDeleteImpactRow
	err := row.Scan(
		&i.RuntimeUserCount,
		&i.RuntimeRoleCount,
		&i.DeploymentCount,
		&i.VersionCount,
	)
	return i, err
}

const getProjectGroup = `-- name: GetProjectGroup :one
SELECT id, tenant_id, name, description, sort_order, created_by, created_at, updated_at FROM project_groups WHERE id = $1 AND tenant_id = $2 LIMIT 1
`

type GetProjectGroupParams struct {
	GroupID  pgtype.UUID `json:"group_id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) GetProjectGroup(ctx context.Context, arg GetProjectGroupParams) (ProjectGroup, error) {
	row := q.db.QueryRow(ctx, getProjectGroup, arg.GroupID, arg.TenantID)
	var i ProjectGroup
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Description,
		&i.SortOrder,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProjectTag = `-- name: GetProjectTag :one
SELECT id, tenant_id, name, color, description, sort_order, created_by, created_at, updated_at FROM project_tags WHERE id = $1 AND tenant_id = $2 LIMIT 1
`

type GetProjectTagParams struct {
	TagID    pgtype.UUID `json:"tag_id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) GetProjectTag(ctx context.Context, arg GetProjectTagParams) (ProjectTag, error) {
	row := q.db.QueryRow(ctx, getProjectTag, arg.TagID, arg.TenantID)
	var i ProjectTag
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Color,
		&i.Description,
		&i.SortOrder,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listProjectGroups = `-- name: ListProjectGroups :many
SELECT g.id, g.tenant_id, g.name, g.description, g.sort_order, g.created_by, g.created_at, g.updated_at, (SELECT count(*) FROM project_group_members m WHERE m.group_id = g.id) AS project_count
FROM project_groups g
WHERE g.tenant_id = $1
  AND ($2::text = '' OR g.name ILIKE '%' || $2 || '%')
ORDER BY g.sort_order, g.created_at
`

type ListProjectGroupsParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	Keyword  string      `json:"keyword"`
}

type ListProjectGroupsRow struct {
	ID           pgtype.UUID        `json:"id"`
	TenantID     pgtype.UUID        `json:"tenant_id"`
	Name         string             `json:"name"`
	Description  pgtype.Text        `json:"description"`
	SortOrder    int32              `json:"sort_order"`
	CreatedBy    pgtype.UUID        `json:"created_by"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	ProjectCount int64              `json:"project_count"`
}

func (q *Queries) ListProjectGroups(ctx context.Context, arg ListProjectGroupsParams) ([]ListProjectGroupsRow, error) {
	rows, err := q.db.Query(ctx, listProjectGroups, arg.TenantID, arg.Keyword)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProjectGroupsRow{}
	for rows.Next() {
		var i ListProjectGroupsRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.Description,
			&i.SortOrder,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ProjectCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectTags = `-- name: ListProjectTags :many
SELECT t.id, t.tenant_id, t.name, t.color, t.description, t.sort_order, t.created_by, t.created_at, t.updated_at, (SELECT count(*) FROM project_tag_bindings b WHERE b.tag_id = t.id) AS project_count
FROM project_tags t
WHERE t.tenant_id = $1
  AND ($2::text = '' OR t.name ILIKE '%' || $2 || '%')
ORDER BY t.sort_order, t.created_at
`

type ListProjectTagsParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	Keyword  string      `json:"keyword"`
}

type ListProjectTagsRow struct {
	ID           pgtype.UUID        `json:"id"`
	TenantID     pgtype.UUID        `json:"tenant_id"`
	Name         string             `json:"name"`
	Color        pgtype.Text        `json:"color"`
	Description  pgtype.Text        `json:"description"`
	SortOrder    int32              `json:"sort_order"`
	CreatedBy    pgtype.UUID        `json:"created_by"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	ProjectCount int64              `json:"project_count"`
}

func (q *Queries) ListProjectTags(ctx context.Context, arg ListProjectTagsParams) ([]ListProjectTagsRow, error) {
	rows, err := q.db.Query(ctx, listProjectTags, arg.TenantID, arg.Keyword)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProjectTagsRow{}
	for rows.Next() {
		var i ListProjectTagsRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.Color,
			&i.Description,
			&i.SortOrder,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ProjectCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjects = `-- name: ListProjects :many
SELECT p.id, p.tenant_id, p.name, p.code, p.description, p.icon, p.workspace_path,
       p.status, p.visibility, p.authoring_epoch, p.created_by, p.updated_by, p.archived_at, p.created_at, p.updated_at,
       creator.username AS created_by_name,
       g.id AS group_id, g.name AS group_name,
       COALESCE(jsonb_agg(DISTINCT jsonb_build_object('id', t.id, 'name', t.name, 'color', t.color, 'description', t.description, 'sortOrder', t.sort_order)) FILTER (WHERE t.id IS NOT NULL), '[]'::jsonb) AS tags
FROM projects p
JOIN users creator ON creator.id = p.created_by
LEFT JOIN project_group_members gm ON gm.project_id = p.id
LEFT JOIN project_groups g ON g.id = gm.group_id
LEFT JOIN project_tag_bindings tb ON tb.project_id = p.id
LEFT JOIN project_tags t ON t.id = tb.tag_id
WHERE p.tenant_id = $1
  AND p.status <> 'deleted'
  AND (
    $2::boolean
    OR p.created_by = $3
    OR ($4::boolean AND p.visibility = 'internal')
  )
  AND ($5::text = '' OR p.name ILIKE '%' || $5 || '%' OR p.code ILIKE '%' || $5 || '%')
  AND ($6::text = '' OR p.status = $6)
  AND ($7::text = '' OR p.visibility = $7)
  AND ($8::text = '' OR g.id::text = $8)
  AND ($9::text = '' OR EXISTS (SELECT 1 FROM project_tag_bindings filter_tb WHERE filter_tb.project_id = p.id AND filter_tb.tag_id::text = $9))
GROUP BY p.id, creator.username, g.id, g.name
ORDER BY p.updated_at DESC,p.id DESC
LIMIT $11 OFFSET $10
`

type ListProjectsParams struct {
	TenantID        pgtype.UUID `json:"tenant_id"`
	IsPlatformAdmin bool        `json:"is_platform_admin"`
	ActorID         pgtype.UUID `json:"actor_id"`
	CanReadShared   bool        `json:"can_read_shared"`
	Keyword         string      `json:"keyword"`
	Status          string      `json:"status"`
	Visibility      string      `json:"visibility"`
	GroupID         string      `json:"group_id"`
	TagID           string      `json:"tag_id"`
	PageOffset      int32       `json:"page_offset"`
	PageLimit       int32       `json:"page_limit"`
}

type ListProjectsRow struct {
	ID             pgtype.UUID        `json:"id"`
	TenantID       pgtype.UUID        `json:"tenant_id"`
	Name           string             `json:"name"`
	Code           string             `json:"code"`
	Description    pgtype.Text        `json:"description"`
	Icon           pgtype.Text        `json:"icon"`
	WorkspacePath  string             `json:"workspace_path"`
	Status         string             `json:"status"`
	Visibility     string             `json:"visibility"`
	AuthoringEpoch int64              `json:"authoring_epoch"`
	CreatedBy      pgtype.UUID        `json:"created_by"`
	UpdatedBy      pgtype.UUID        `json:"updated_by"`
	ArchivedAt     pgtype.Timestamptz `json:"archived_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	CreatedByName  string             `json:"created_by_name"`
	GroupID        pgtype.UUID        `json:"group_id"`
	GroupName      pgtype.Text        `json:"group_name"`
	Tags           interface{}        `json:"tags"`
}

func (q *Queries) ListProjects(ctx context.Context, arg ListProjectsParams) ([]ListProjectsRow, error) {
	rows, err := q.db.Query(ctx, listProjects,
		arg.TenantID,
		arg.IsPlatformAdmin,
		arg.ActorID,
		arg.CanReadShared,
		arg.Keyword,
		arg.Status,
		arg.Visibility,
		arg.GroupID,
		arg.TagID,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProjectsRow{}
	for rows.Next() {
		var i ListProjectsRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.Code,
			&i.Description,
			&i.Icon,
			&i.WorkspacePath,
			&i.Status,
			&i.Visibility,
			&i.AuthoringEpoch,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.ArchivedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatedByName,
			&i.GroupID,
			&i.GroupName,
			&i.Tags,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setProjectLifecycleStatus = `-- name: SetProjectLifecycleStatus :one
UPDATE projects
SET status = $1, archived_at = CASE WHEN $1 = 'archived' THEN now() ELSE NULL END,
    updated_by = $2, updated_at = now()
WHERE id = $3 AND tenant_id = $4 AND status <> 'deleted'
RETURNING id, tenant_id, name, code, description, icon, workspace_path, status, visibility, authoring_epoch, created_by, updated_by, archived_at, created_at, updated_at
`

type SetProjectLifecycleStatusParams struct {
	Status    string      `json:"status"`
	UserID    pgtype.UUID `json:"user_id"`
	ProjectID pgtype.UUID `json:"project_id"`
	TenantID  pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) SetProjectLifecycleStatus(ctx context.Context, arg SetProjectLifecycleStatusParams) (Project, error) {
	row := q.db.QueryRow(ctx, setProjectLifecycleStatus,
		arg.Status,
		arg.UserID,
		arg.ProjectID,
		arg.TenantID,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Code,
		&i.Description,
		&i.Icon,
		&i.WorkspacePath,
		&i.Status,
		&i.Visibility,
		&i.AuthoringEpoch,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const softDeleteProject = `-- name: SoftDeleteProject :execrows
UPDATE projects SET status = 'deleted', updated_by = $1, updated_at = now()
WHERE id = $2 AND tenant_id = $3 AND status <> 'deleted'
`

type SoftDeleteProjectParams struct {
	UserID    pgtype.UUID `json:"user_id"`
	ProjectID pgtype.UUID `json:"project_id"`
	TenantID  pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) SoftDeleteProject(ctx context.Context, arg SoftDeleteProjectParams) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteProject, arg.UserID, arg.ProjectID, arg.TenantID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateProject = `-- name: UpdateProject :one
UPDATE projects
SET name = $1, description = $2,
    icon = $3, visibility = $4, updated_by = $5, updated_at = now()
WHERE id = $6 AND tenant_id = $7 AND status <> 'deleted'
RETURNING id, tenant_id, name, code, description, icon, workspace_path, status, visibility, authoring_epoch, created_by, updated_by, archived_at, created_at, updated_at
`

type UpdateProjectParams struct {
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	Icon        pgtype.Text `json:"icon"`
	Visibility  string      `json:"visibility"`
	UserID      pgtype.UUID `json:"user_id"`
	ProjectID   pgtype.UUID `json:"project_id"`
	TenantID    pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, updateProject,
		arg.Name,
		arg.Description,
		arg.Icon,
		arg.Visibility,
		arg.UserID,
		arg.ProjectID,
		arg.TenantID,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Code,
		&i.Description,
		&i.Icon,
		&i.WorkspacePath,
		&i.Status,
		&i.Visibility,
		&i.AuthoringEpoch,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateProjectGroup = `-- name: UpdateProjectGroup :one
UPDATE project_groups
SET name = $1, description = $2, sort_order = $3, updated_at = now()
WHERE id = $4 AND tenant_id = $5
RETURNING id, tenant_id, name, description, sort_order, created_by, created_at, updated_at
`

type UpdateProjectGroupParams struct {
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	SortOrder   int32       `json:"sort_order"`
	GroupID     pgtype.UUID `json:"group_id"`
	TenantID    pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) UpdateProjectGroup(ctx context.Context, arg UpdateProjectGroupParams) (ProjectGroup, error) {
	row := q.db.QueryRow(ctx, updateProjectGroup,
		arg.Name,
		arg.Description,
		arg.SortOrder,
		arg.GroupID,
		arg.TenantID,
	)
	var i ProjectGroup
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Description,
		&i.SortOrder,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateProjectTag = `-- name: UpdateProjectTag :one
UPDATE project_tags
SET name = $1, color = $2, description = $3,
    sort_order = $4, updated_at = now()
WHERE id = $5 AND tenant_id = $6
RETURNING id, tenant_id, name, color, description, sort_order, created_by, created_at, updated_at
`

type UpdateProjectTagParams struct {
	Name        string      `json:"name"`
	Color       pgtype.Text `json:"color"`
	Description pgtype.Text `json:"description"`
	SortOrder   int32       `json:"sort_order"`
	TagID       pgtype.UUID `json:"tag_id"`
	TenantID    pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) UpdateProjectTag(ctx context.Context, arg UpdateProjectTagParams) (ProjectTag, error) {
	row := q.db.QueryRow(ctx, updateProjectTag,
		arg.Name,
		arg.Color,
		arg.Description,
		arg.SortOrder,
		arg.TagID,
		arg.TenantID,
	)
	var i ProjectTag
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Color,
		&i.Description,
		&i.SortOrder,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
