// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	ApproveNode(ctx context.Context, arg ApproveNodeParams) (Node, error)
	CheckRuntimeRoleInProject(ctx context.Context, arg CheckRuntimeRoleInProjectParams) (bool, error)
	CompleteNodeDeploymentCommands(ctx context.Context, arg CompleteNodeDeploymentCommandsParams) error
	ConsumeRefreshToken(ctx context.Context, tokenHash string) (ConsumeRefreshTokenRow, error)
	CountApplicationVersions(ctx context.Context, arg CountApplicationVersionsParams) (int64, error)
	CountAuditLogs(ctx context.Context, arg CountAuditLogsParams) (int64, error)
	CountFilteredTenants(ctx context.Context, arg CountFilteredTenantsParams) (int64, error)
	CountNodes(ctx context.Context, arg CountNodesParams) (int64, error)
	CountProjects(ctx context.Context, arg CountProjectsParams) (int64, error)
	CountRuntimeRoles(ctx context.Context, arg CountRuntimeRolesParams) (int64, error)
	CountRuntimeUsers(ctx context.Context, arg CountRuntimeUsersParams) (int64, error)
	CountTenantUsers(ctx context.Context, tenantID pgtype.UUID) (int64, error)
	CountTenants(ctx context.Context) (int64, error)
	CountUsers(ctx context.Context, arg CountUsersParams) (int64, error)
	CreateApplicationVersion(ctx context.Context, arg CreateApplicationVersionParams) (ApplicationVersion, error)
	CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) error
	CreateDashboardNote(ctx context.Context, arg CreateDashboardNoteParams) (TenantDashboardNote, error)
	CreateManagedUser(ctx context.Context, arg CreateManagedUserParams) (User, error)
	CreateNodeCommand(ctx context.Context, arg CreateNodeCommandParams) (NodeCommand, error)
	CreateNodeDeployment(ctx context.Context, arg CreateNodeDeploymentParams) (NodeDeployment, error)
	CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error)
	CreateProjectGroup(ctx context.Context, arg CreateProjectGroupParams) (ProjectGroup, error)
	CreateProjectGroupBinding(ctx context.Context, arg CreateProjectGroupBindingParams) error
	CreateProjectTag(ctx context.Context, arg CreateProjectTagParams) (ProjectTag, error)
	CreateProjectTagBinding(ctx context.Context, arg CreateProjectTagBindingParams) error
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (pgtype.UUID, error)
	CreateRuntimeRole(ctx context.Context, arg CreateRuntimeRoleParams) (ProjectRole, error)
	CreateRuntimeRoleGrant(ctx context.Context, arg CreateRuntimeRoleGrantParams) error
	CreateRuntimeUser(ctx context.Context, arg CreateRuntimeUserParams) (ProjectRuntimeUser, error)
	CreateRuntimeUserRoleBinding(ctx context.Context, arg CreateRuntimeUserRoleBindingParams) error
	CreateTenant(ctx context.Context, arg CreateTenantParams) (Tenant, error)
	DeleteApplicationVersion(ctx context.Context, arg DeleteApplicationVersionParams) (int64, error)
	DeleteAuditLogsBefore(ctx context.Context, arg DeleteAuditLogsBeforeParams) (int64, error)
	DeleteDashboardNote(ctx context.Context, arg DeleteDashboardNoteParams) (int64, error)
	DeleteManagedUser(ctx context.Context, arg DeleteManagedUserParams) (int64, error)
	DeleteNode(ctx context.Context, arg DeleteNodeParams) (int64, error)
	DeleteProjectGroup(ctx context.Context, arg DeleteProjectGroupParams) (int64, error)
	DeleteProjectGroupBinding(ctx context.Context, projectID pgtype.UUID) error
	DeleteProjectTag(ctx context.Context, arg DeleteProjectTagParams) (int64, error)
	DeleteProjectTagBindings(ctx context.Context, projectID pgtype.UUID) error
	DeleteRuntimeRole(ctx context.Context, arg DeleteRuntimeRoleParams) (int64, error)
	DeleteRuntimeRoleGrants(ctx context.Context, roleID pgtype.UUID) error
	DeleteRuntimeUser(ctx context.Context, arg DeleteRuntimeUserParams) (int64, error)
	DeleteRuntimeUserRoleBindings(ctx context.Context, runtimeUserID pgtype.UUID) error
	DeleteTenant(ctx context.Context, tenantID pgtype.UUID) (int64, error)
	ExportAuditLogs(ctx context.Context, arg ExportAuditLogsParams) ([]ExportAuditLogsRow, error)
	FindAuthUserByTenantCode(ctx context.Context, arg FindAuthUserByTenantCodeParams) (FindAuthUserByTenantCodeRow, error)
	FindAuthUsersByUsername(ctx context.Context, username string) ([]FindAuthUsersByUsernameRow, error)
	GetApplicationVersion(ctx context.Context, arg GetApplicationVersionParams) (ApplicationVersion, error)
	GetApprovedDeploymentNode(ctx context.Context, arg GetApprovedDeploymentNodeParams) (Node, error)
	GetAuditLog(ctx context.Context, arg GetAuditLogParams) (GetAuditLogRow, error)
	GetAuditLogActionStats(ctx context.Context, arg GetAuditLogActionStatsParams) ([]GetAuditLogActionStatsRow, error)
	GetAuditLogLevelStats(ctx context.Context, arg GetAuditLogLevelStatsParams) ([]GetAuditLogLevelStatsRow, error)
	GetAuditLogTrendStats(ctx context.Context, arg GetAuditLogTrendStatsParams) ([]GetAuditLogTrendStatsRow, error)
	GetAuthUserByID(ctx context.Context, userID pgtype.UUID) (GetAuthUserByIDRow, error)
	GetManagedUser(ctx context.Context, arg GetManagedUserParams) (User, error)
	GetNode(ctx context.Context, arg GetNodeParams) (Node, error)
	GetNodeApprovalStatus(ctx context.Context, nodeID pgtype.UUID) (GetNodeApprovalStatusRow, error)
	GetNodeByToken(ctx context.Context, arg GetNodeByTokenParams) (Node, error)
	GetNodeDeployment(ctx context.Context, arg GetNodeDeploymentParams) (NodeDeployment, error)
	GetProject(ctx context.Context, arg GetProjectParams) (Project, error)
	GetProjectDeleteImpact(ctx context.Context, projectID pgtype.UUID) (GetProjectDeleteImpactRow, error)
	GetProjectGroup(ctx context.Context, arg GetProjectGroupParams) (ProjectGroup, error)
	GetProjectTag(ctx context.Context, arg GetProjectTagParams) (ProjectTag, error)
	GetRefreshTokenByHash(ctx context.Context, tokenHash string) (GetRefreshTokenByHashRow, error)
	GetRuntimeRole(ctx context.Context, arg GetRuntimeRoleParams) (ProjectRole, error)
	GetRuntimeUser(ctx context.Context, arg GetRuntimeUserParams) (ProjectRuntimeUser, error)
	GetTenantBrandingByCode(ctx context.Context, tenantCode string) (GetTenantBrandingByCodeRow, error)
	GetTenantByIdentifier(ctx context.Context, identifier string) (GetTenantByIdentifierRow, error)
	ListApplicationVersions(ctx context.Context, arg ListApplicationVersionsParams) ([]ApplicationVersion, error)
	ListAuditLogs(ctx context.Context, arg ListAuditLogsParams) ([]ListAuditLogsRow, error)
	ListDashboardNotes(ctx context.Context, tenantID pgtype.UUID) ([]ListDashboardNotesRow, error)
	ListNodes(ctx context.Context, arg ListNodesParams) ([]ListNodesRow, error)
	ListPendingNodeCommands(ctx context.Context, nodeID pgtype.UUID) ([]NodeCommand, error)
	ListProjectGroups(ctx context.Context, arg ListProjectGroupsParams) ([]ListProjectGroupsRow, error)
	ListProjectNodeDeployments(ctx context.Context, arg ListProjectNodeDeploymentsParams) ([]ListProjectNodeDeploymentsRow, error)
	ListProjectTags(ctx context.Context, arg ListProjectTagsParams) ([]ListProjectTagsRow, error)
	ListProjects(ctx context.Context, arg ListProjectsParams) ([]ListProjectsRow, error)
	ListRecentAuditActivities(ctx context.Context, arg ListRecentAuditActivitiesParams) ([]ListRecentAuditActivitiesRow, error)
	ListRuntimeRoles(ctx context.Context, arg ListRuntimeRolesParams) ([]ListRuntimeRolesRow, error)
	ListRuntimeUsers(ctx context.Context, arg ListRuntimeUsersParams) ([]ListRuntimeUsersRow, error)
	ListStaleNodeCommands(ctx context.Context) ([]ListStaleNodeCommandsRow, error)
	ListTenants(ctx context.Context, arg ListTenantsParams) ([]ListTenantsRow, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]ListUsersRow, error)
	MarkApplicationVersionFailed(ctx context.Context, arg MarkApplicationVersionFailedParams) (ApplicationVersion, error)
	MarkApplicationVersionReady(ctx context.Context, arg MarkApplicationVersionReadyParams) (ApplicationVersion, error)
	MarkNodeCommandIssued(ctx context.Context, commandID pgtype.UUID) error
	PageRuntimeRoles(ctx context.Context, arg PageRuntimeRolesParams) ([]PageRuntimeRolesRow, error)
	PageRuntimeUsers(ctx context.Context, arg PageRuntimeUsersParams) ([]PageRuntimeUsersRow, error)
	RecoverStaleNodeCommand(ctx context.Context, arg RecoverStaleNodeCommandParams) (int64, error)
	RecoverStaleNodeCommands(ctx context.Context) (int64, error)
	RegisterNode(ctx context.Context, arg RegisterNodeParams) (Node, error)
	RejectNode(ctx context.Context, arg RejectNodeParams) (Node, error)
	RemoveActiveNodeDeployment(ctx context.Context, arg RemoveActiveNodeDeploymentParams) error
	RevokeRefreshToken(ctx context.Context, tokenHash string) error
	RevokeUserRefreshTokens(ctx context.Context, userID pgtype.UUID) error
	SetProjectLifecycleStatus(ctx context.Context, arg SetProjectLifecycleStatusParams) (Project, error)
	SetRefreshTokenReplacement(ctx context.Context, arg SetRefreshTokenReplacementParams) error
	SetTenantStatus(ctx context.Context, arg SetTenantStatusParams) (Tenant, error)
	SoftDeleteProject(ctx context.Context, arg SoftDeleteProjectParams) (int64, error)
	UpdateAuthUserAvatar(ctx context.Context, arg UpdateAuthUserAvatarParams) (pgtype.Text, error)
	UpdateAuthUserLogin(ctx context.Context, arg UpdateAuthUserLoginParams) error
	UpdateAuthUserPassword(ctx context.Context, arg UpdateAuthUserPasswordParams) (int64, error)
	UpdateAuthUserProfile(ctx context.Context, arg UpdateAuthUserProfileParams) (int64, error)
	UpdateDashboardNote(ctx context.Context, arg UpdateDashboardNoteParams) (TenantDashboardNote, error)
	UpdateManagedUser(ctx context.Context, arg UpdateManagedUserParams) (User, error)
	UpdateNodeDeploymentState(ctx context.Context, arg UpdateNodeDeploymentStateParams) (NodeDeployment, error)
	UpdateNodeHeartbeat(ctx context.Context, arg UpdateNodeHeartbeatParams) (Node, error)
	UpdateNodeOffline(ctx context.Context, arg UpdateNodeOfflineParams) (Node, error)
	UpdateNodeReportedDeployment(ctx context.Context, arg UpdateNodeReportedDeploymentParams) (NodeDeployment, error)
	UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error)
	UpdateProjectGroup(ctx context.Context, arg UpdateProjectGroupParams) (ProjectGroup, error)
	UpdateProjectTag(ctx context.Context, arg UpdateProjectTagParams) (ProjectTag, error)
	UpdateRuntimeRole(ctx context.Context, arg UpdateRuntimeRoleParams) (ProjectRole, error)
	UpdateRuntimeUserPassword(ctx context.Context, arg UpdateRuntimeUserPasswordParams) error
	UpdateRuntimeUserStatus(ctx context.Context, arg UpdateRuntimeUserStatusParams) (ProjectRuntimeUser, error)
	UpdateTenant(ctx context.Context, arg UpdateTenantParams) (Tenant, error)
}

var _ Querier = (*Queries)(nil)
