// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: runtime_access.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const checkRuntimeRoleInProject = `-- name: CheckRuntimeRoleInProject :one
SELECT EXISTS (SELECT 1 FROM project_roles WHERE id = $1 AND project_id = $2)
`

type CheckRuntimeRoleInProjectParams struct {
	RoleID    pgtype.UUID `json:"role_id"`
	ProjectID pgtype.UUID `json:"project_id"`
}

func (q *Queries) CheckRuntimeRoleInProject(ctx context.Context, arg CheckRuntimeRoleInProjectParams) (bool, error) {
	row := q.db.QueryRow(ctx, checkRuntimeRoleInProject, arg.RoleID, arg.ProjectID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const createRuntimeRole = `-- name: CreateRuntimeRole :one
INSERT INTO project_roles (project_id, code, name, description, status, is_builtin, created_by)
VALUES ($1, $2, $3, $4, $5, false, $6)
RETURNING id, project_id, code, name, description, status, is_builtin, created_by, updated_by, created_at, updated_at
`

type CreateRuntimeRoleParams struct {
	ProjectID   pgtype.UUID `json:"project_id"`
	Code        string      `json:"code"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	Status      string      `json:"status"`
	UserID      pgtype.UUID `json:"user_id"`
}

func (q *Queries) CreateRuntimeRole(ctx context.Context, arg CreateRuntimeRoleParams) (ProjectRole, error) {
	row := q.db.QueryRow(ctx, createRuntimeRole,
		arg.ProjectID,
		arg.Code,
		arg.Name,
		arg.Description,
		arg.Status,
		arg.UserID,
	)
	var i ProjectRole
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.IsBuiltin,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createRuntimeRoleGrant = `-- name: CreateRuntimeRoleGrant :exec
INSERT INTO project_role_grants (project_id, role_id, capability, effect)
VALUES ($1, $2, $3, 'allow')
`

type CreateRuntimeRoleGrantParams struct {
	ProjectID  pgtype.UUID `json:"project_id"`
	RoleID     pgtype.UUID `json:"role_id"`
	Capability string      `json:"capability"`
}

func (q *Queries) CreateRuntimeRoleGrant(ctx context.Context, arg CreateRuntimeRoleGrantParams) error {
	_, err := q.db.Exec(ctx, createRuntimeRoleGrant, arg.ProjectID, arg.RoleID, arg.Capability)
	return err
}

const createRuntimeUser = `-- name: CreateRuntimeUser :one
INSERT INTO project_runtime_users (project_id, username, password_hash, display_name, email, status, is_builtin_admin, created_by)
VALUES ($1, $2, $3, $4, $5, $6, false, $7)
RETURNING id, project_id, username, password_hash, display_name, email, status, is_builtin_admin, last_login_at, password_changed_at, created_by, updated_by, created_at, updated_at
`

type CreateRuntimeUserParams struct {
	ProjectID    pgtype.UUID `json:"project_id"`
	Username     string      `json:"username"`
	PasswordHash string      `json:"password_hash"`
	DisplayName  pgtype.Text `json:"display_name"`
	Email        pgtype.Text `json:"email"`
	Status       string      `json:"status"`
	UserID       pgtype.UUID `json:"user_id"`
}

func (q *Queries) CreateRuntimeUser(ctx context.Context, arg CreateRuntimeUserParams) (ProjectRuntimeUser, error) {
	row := q.db.QueryRow(ctx, createRuntimeUser,
		arg.ProjectID,
		arg.Username,
		arg.PasswordHash,
		arg.DisplayName,
		arg.Email,
		arg.Status,
		arg.UserID,
	)
	var i ProjectRuntimeUser
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Username,
		&i.PasswordHash,
		&i.DisplayName,
		&i.Email,
		&i.Status,
		&i.IsBuiltinAdmin,
		&i.LastLoginAt,
		&i.PasswordChangedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createRuntimeUserRoleBinding = `-- name: CreateRuntimeUserRoleBinding :exec
INSERT INTO project_user_role_bindings (runtime_user_id, role_id) VALUES ($1, $2)
`

type CreateRuntimeUserRoleBindingParams struct {
	RuntimeUserID pgtype.UUID `json:"runtime_user_id"`
	RoleID        pgtype.UUID `json:"role_id"`
}

func (q *Queries) CreateRuntimeUserRoleBinding(ctx context.Context, arg CreateRuntimeUserRoleBindingParams) error {
	_, err := q.db.Exec(ctx, createRuntimeUserRoleBinding, arg.RuntimeUserID, arg.RoleID)
	return err
}

const deleteRuntimeRole = `-- name: DeleteRuntimeRole :execrows
DELETE FROM project_roles WHERE id = $1 AND project_id = $2 AND is_builtin = false
`

type DeleteRuntimeRoleParams struct {
	RoleID    pgtype.UUID `json:"role_id"`
	ProjectID pgtype.UUID `json:"project_id"`
}

func (q *Queries) DeleteRuntimeRole(ctx context.Context, arg DeleteRuntimeRoleParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteRuntimeRole, arg.RoleID, arg.ProjectID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteRuntimeRoleGrants = `-- name: DeleteRuntimeRoleGrants :exec
DELETE FROM project_role_grants WHERE role_id = $1
`

func (q *Queries) DeleteRuntimeRoleGrants(ctx context.Context, roleID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteRuntimeRoleGrants, roleID)
	return err
}

const deleteRuntimeUser = `-- name: DeleteRuntimeUser :execrows
DELETE FROM project_runtime_users WHERE id = $1 AND project_id = $2 AND is_builtin_admin = false
`

type DeleteRuntimeUserParams struct {
	RuntimeUserID pgtype.UUID `json:"runtime_user_id"`
	ProjectID     pgtype.UUID `json:"project_id"`
}

func (q *Queries) DeleteRuntimeUser(ctx context.Context, arg DeleteRuntimeUserParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteRuntimeUser, arg.RuntimeUserID, arg.ProjectID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteRuntimeUserRoleBindings = `-- name: DeleteRuntimeUserRoleBindings :exec
DELETE FROM project_user_role_bindings WHERE runtime_user_id = $1
`

func (q *Queries) DeleteRuntimeUserRoleBindings(ctx context.Context, runtimeUserID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteRuntimeUserRoleBindings, runtimeUserID)
	return err
}

const getRuntimeRole = `-- name: GetRuntimeRole :one
SELECT r.id, r.project_id, r.code, r.name, r.description, r.status, r.is_builtin, r.created_by, r.updated_by, r.created_at, r.updated_at FROM project_roles r JOIN projects p ON p.id = r.project_id
WHERE r.id = $1 AND r.project_id = $2 AND p.tenant_id = $3 AND p.status <> 'deleted'
LIMIT 1
`

type GetRuntimeRoleParams struct {
	RoleID    pgtype.UUID `json:"role_id"`
	ProjectID pgtype.UUID `json:"project_id"`
	TenantID  pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) GetRuntimeRole(ctx context.Context, arg GetRuntimeRoleParams) (ProjectRole, error) {
	row := q.db.QueryRow(ctx, getRuntimeRole, arg.RoleID, arg.ProjectID, arg.TenantID)
	var i ProjectRole
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.IsBuiltin,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRuntimeUser = `-- name: GetRuntimeUser :one
SELECT u.id, u.project_id, u.username, u.password_hash, u.display_name, u.email, u.status, u.is_builtin_admin, u.last_login_at, u.password_changed_at, u.created_by, u.updated_by, u.created_at, u.updated_at FROM project_runtime_users u JOIN projects p ON p.id = u.project_id
WHERE u.id = $1 AND u.project_id = $2 AND p.tenant_id = $3 AND p.status <> 'deleted'
LIMIT 1
`

type GetRuntimeUserParams struct {
	RuntimeUserID pgtype.UUID `json:"runtime_user_id"`
	ProjectID     pgtype.UUID `json:"project_id"`
	TenantID      pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) GetRuntimeUser(ctx context.Context, arg GetRuntimeUserParams) (ProjectRuntimeUser, error) {
	row := q.db.QueryRow(ctx, getRuntimeUser, arg.RuntimeUserID, arg.ProjectID, arg.TenantID)
	var i ProjectRuntimeUser
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Username,
		&i.PasswordHash,
		&i.DisplayName,
		&i.Email,
		&i.Status,
		&i.IsBuiltinAdmin,
		&i.LastLoginAt,
		&i.PasswordChangedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listRuntimeRoles = `-- name: ListRuntimeRoles :many
SELECT r.id, r.project_id, r.code, r.name, r.description, r.status, r.is_builtin,
       r.created_at, r.updated_at,
       COALESCE(jsonb_agg(DISTINCT g.capability) FILTER (WHERE g.id IS NOT NULL AND g.effect = 'allow'), '[]'::jsonb) AS capabilities,
       (SELECT count(*) FROM project_user_role_bindings b WHERE b.role_id = r.id) AS user_count
FROM project_roles r
JOIN projects p ON p.id = r.project_id
LEFT JOIN project_role_grants g ON g.role_id = r.id
WHERE r.project_id = $1 AND p.tenant_id = $2 AND p.status <> 'deleted'
GROUP BY r.id
ORDER BY r.is_builtin DESC, r.created_at
`

type ListRuntimeRolesParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	TenantID  pgtype.UUID `json:"tenant_id"`
}

type ListRuntimeRolesRow struct {
	ID           pgtype.UUID        `json:"id"`
	ProjectID    pgtype.UUID        `json:"project_id"`
	Code         string             `json:"code"`
	Name         string             `json:"name"`
	Description  pgtype.Text        `json:"description"`
	Status       string             `json:"status"`
	IsBuiltin    bool               `json:"is_builtin"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	Capabilities interface{}        `json:"capabilities"`
	UserCount    int64              `json:"user_count"`
}

func (q *Queries) ListRuntimeRoles(ctx context.Context, arg ListRuntimeRolesParams) ([]ListRuntimeRolesRow, error) {
	rows, err := q.db.Query(ctx, listRuntimeRoles, arg.ProjectID, arg.TenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRuntimeRolesRow{}
	for rows.Next() {
		var i ListRuntimeRolesRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Code,
			&i.Name,
			&i.Description,
			&i.Status,
			&i.IsBuiltin,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Capabilities,
			&i.UserCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRuntimeUsers = `-- name: ListRuntimeUsers :many
SELECT u.id, u.project_id, u.username, u.display_name, u.email, u.status, u.is_builtin_admin,
       u.last_login_at, u.password_changed_at, u.created_at, u.updated_at,
       COALESCE(jsonb_agg(DISTINCT jsonb_build_object('id', r.id, 'code', r.code, 'name', r.name, 'status', r.status, 'isBuiltin', r.is_builtin)) FILTER (WHERE r.id IS NOT NULL), '[]'::jsonb) AS roles
FROM project_runtime_users u
JOIN projects p ON p.id = u.project_id
LEFT JOIN project_user_role_bindings b ON b.runtime_user_id = u.id
LEFT JOIN project_roles r ON r.id = b.role_id
WHERE u.project_id = $1 AND p.tenant_id = $2 AND p.status <> 'deleted'
GROUP BY u.id
ORDER BY u.is_builtin_admin DESC, u.created_at
`

type ListRuntimeUsersParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	TenantID  pgtype.UUID `json:"tenant_id"`
}

type ListRuntimeUsersRow struct {
	ID                pgtype.UUID        `json:"id"`
	ProjectID         pgtype.UUID        `json:"project_id"`
	Username          string             `json:"username"`
	DisplayName       pgtype.Text        `json:"display_name"`
	Email             pgtype.Text        `json:"email"`
	Status            string             `json:"status"`
	IsBuiltinAdmin    bool               `json:"is_builtin_admin"`
	LastLoginAt       pgtype.Timestamptz `json:"last_login_at"`
	PasswordChangedAt pgtype.Timestamptz `json:"password_changed_at"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	Roles             interface{}        `json:"roles"`
}

func (q *Queries) ListRuntimeUsers(ctx context.Context, arg ListRuntimeUsersParams) ([]ListRuntimeUsersRow, error) {
	rows, err := q.db.Query(ctx, listRuntimeUsers, arg.ProjectID, arg.TenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRuntimeUsersRow{}
	for rows.Next() {
		var i ListRuntimeUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Username,
			&i.DisplayName,
			&i.Email,
			&i.Status,
			&i.IsBuiltinAdmin,
			&i.LastLoginAt,
			&i.PasswordChangedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Roles,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRuntimeRole = `-- name: UpdateRuntimeRole :one
UPDATE project_roles SET code = $1, name = $2, description = $3,
  status = $4, updated_by = $5, updated_at = now()
WHERE id = $6 AND project_id = $7 AND is_builtin = false
RETURNING id, project_id, code, name, description, status, is_builtin, created_by, updated_by, created_at, updated_at
`

type UpdateRuntimeRoleParams struct {
	Code        string      `json:"code"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	Status      string      `json:"status"`
	UserID      pgtype.UUID `json:"user_id"`
	RoleID      pgtype.UUID `json:"role_id"`
	ProjectID   pgtype.UUID `json:"project_id"`
}

func (q *Queries) UpdateRuntimeRole(ctx context.Context, arg UpdateRuntimeRoleParams) (ProjectRole, error) {
	row := q.db.QueryRow(ctx, updateRuntimeRole,
		arg.Code,
		arg.Name,
		arg.Description,
		arg.Status,
		arg.UserID,
		arg.RoleID,
		arg.ProjectID,
	)
	var i ProjectRole
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.IsBuiltin,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateRuntimeUserPassword = `-- name: UpdateRuntimeUserPassword :exec
UPDATE project_runtime_users SET password_hash = $1, password_changed_at = now(), updated_by = $2, updated_at = now()
WHERE id = $3 AND project_id = $4
`

type UpdateRuntimeUserPasswordParams struct {
	PasswordHash  string      `json:"password_hash"`
	UserID        pgtype.UUID `json:"user_id"`
	RuntimeUserID pgtype.UUID `json:"runtime_user_id"`
	ProjectID     pgtype.UUID `json:"project_id"`
}

func (q *Queries) UpdateRuntimeUserPassword(ctx context.Context, arg UpdateRuntimeUserPasswordParams) error {
	_, err := q.db.Exec(ctx, updateRuntimeUserPassword,
		arg.PasswordHash,
		arg.UserID,
		arg.RuntimeUserID,
		arg.ProjectID,
	)
	return err
}

const updateRuntimeUserStatus = `-- name: UpdateRuntimeUserStatus :one
UPDATE project_runtime_users SET status = $1, updated_by = $2, updated_at = now()
WHERE id = $3 AND project_id = $4
RETURNING id, project_id, username, password_hash, display_name, email, status, is_builtin_admin, last_login_at, password_changed_at, created_by, updated_by, created_at, updated_at
`

type UpdateRuntimeUserStatusParams struct {
	Status        string      `json:"status"`
	UserID        pgtype.UUID `json:"user_id"`
	RuntimeUserID pgtype.UUID `json:"runtime_user_id"`
	ProjectID     pgtype.UUID `json:"project_id"`
}

func (q *Queries) UpdateRuntimeUserStatus(ctx context.Context, arg UpdateRuntimeUserStatusParams) (ProjectRuntimeUser, error) {
	row := q.db.QueryRow(ctx, updateRuntimeUserStatus,
		arg.Status,
		arg.UserID,
		arg.RuntimeUserID,
		arg.ProjectID,
	)
	var i ProjectRuntimeUser
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Username,
		&i.PasswordHash,
		&i.DisplayName,
		&i.Email,
		&i.Status,
		&i.IsBuiltinAdmin,
		&i.LastLoginAt,
		&i.PasswordChangedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
