// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tenant_user.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countFilteredTenants = `-- name: CountFilteredTenants :one
SELECT count(*)
FROM tenants t
WHERE ($1::text = '' OR t.name ILIKE '%' || $1 || '%' OR t.code ILIKE '%' || $1 || '%')
  AND ($2::text = '' OR t.status = $2)
`

type CountFilteredTenantsParams struct {
	Keyword string `json:"keyword"`
	Status  string `json:"status"`
}

func (q *Queries) CountFilteredTenants(ctx context.Context, arg CountFilteredTenantsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countFilteredTenants, arg.Keyword, arg.Status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTenantUsers = `-- name: CountTenantUsers :one
SELECT count(*) FROM users WHERE tenant_id = $1 AND role <> 'SUPER_ADMIN'
`

func (q *Queries) CountTenantUsers(ctx context.Context, tenantID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countTenantUsers, tenantID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUsers = `-- name: CountUsers :one
SELECT count(*)
FROM users u
WHERE u.tenant_id = $1
  AND u.role <> 'SUPER_ADMIN'
  AND ($2::text = '' OR u.username ILIKE '%' || $2 || '%' OR u.full_name ILIKE '%' || $2 || '%' OR u.email ILIKE '%' || $2 || '%')
  AND ($3::text = '' OR u.role = $3)
  AND ($4::text = '' OR u.status = $4)
`

type CountUsersParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	Keyword  string      `json:"keyword"`
	Role     string      `json:"role"`
	Status   string      `json:"status"`
}

func (q *Queries) CountUsers(ctx context.Context, arg CountUsersParams) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers,
		arg.TenantID,
		arg.Keyword,
		arg.Role,
		arg.Status,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createDashboardNote = `-- name: CreateDashboardNote :one
INSERT INTO tenant_dashboard_notes (tenant_id, content, created_by)
VALUES ($1, $2, $3)
RETURNING id, tenant_id, content, created_by, updated_by, created_at, updated_at
`

type CreateDashboardNoteParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	Content  string      `json:"content"`
	UserID   pgtype.UUID `json:"user_id"`
}

func (q *Queries) CreateDashboardNote(ctx context.Context, arg CreateDashboardNoteParams) (TenantDashboardNote, error) {
	row := q.db.QueryRow(ctx, createDashboardNote, arg.TenantID, arg.Content, arg.UserID)
	var i TenantDashboardNote
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Content,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createManagedUser = `-- name: CreateManagedUser :one
INSERT INTO users (tenant_id, username, password_hash, email, phone, full_name, avatar, role, status, preferences)
VALUES ($1, $2, $3, $4,
        $5, $6, $7, $8,
        $9, $10)
RETURNING id, tenant_id, username, password_hash, email, phone, full_name, avatar, role, status, preferences, last_login_at, last_login_ip, password_changed_at, created_at, updated_at
`

type CreateManagedUserParams struct {
	TenantID     pgtype.UUID `json:"tenant_id"`
	Username     string      `json:"username"`
	PasswordHash string      `json:"password_hash"`
	Email        pgtype.Text `json:"email"`
	Phone        pgtype.Text `json:"phone"`
	FullName     pgtype.Text `json:"full_name"`
	Avatar       pgtype.Text `json:"avatar"`
	Role         string      `json:"role"`
	Status       string      `json:"status"`
	Preferences  []byte      `json:"preferences"`
}

func (q *Queries) CreateManagedUser(ctx context.Context, arg CreateManagedUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createManagedUser,
		arg.TenantID,
		arg.Username,
		arg.PasswordHash,
		arg.Email,
		arg.Phone,
		arg.FullName,
		arg.Avatar,
		arg.Role,
		arg.Status,
		arg.Preferences,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Username,
		&i.PasswordHash,
		&i.Email,
		&i.Phone,
		&i.FullName,
		&i.Avatar,
		&i.Role,
		&i.Status,
		&i.Preferences,
		&i.LastLoginAt,
		&i.LastLoginIp,
		&i.PasswordChangedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTenant = `-- name: CreateTenant :one
INSERT INTO tenants (
  name, code, description, status, contact_email, contact_phone,
  max_users, max_projects, max_storage, logo_object_key, login_background_object_key,
  company_name, company_address, company_phone, company_website, settings, expires_at
) VALUES (
  $1, $2, $3, $4,
  $5, $6, $7,
  $8, $9, $10,
  $11, $12, $13,
  $14, $15, $16, $17
)
RETURNING id, name, code, description, status, contact_email, contact_phone, max_users, max_projects, max_storage, used_storage, logo_object_key, login_background_object_key, company_name, company_address, company_phone, company_website, settings, expires_at, created_at, updated_at
`

type CreateTenantParams struct {
	Name                     string             `json:"name"`
	Code                     string             `json:"code"`
	Description              pgtype.Text        `json:"description"`
	Status                   string             `json:"status"`
	ContactEmail             pgtype.Text        `json:"contact_email"`
	ContactPhone             pgtype.Text        `json:"contact_phone"`
	MaxUsers                 int32              `json:"max_users"`
	MaxProjects              int32              `json:"max_projects"`
	MaxStorage               int64              `json:"max_storage"`
	LogoObjectKey            pgtype.Text        `json:"logo_object_key"`
	LoginBackgroundObjectKey pgtype.Text        `json:"login_background_object_key"`
	CompanyName              pgtype.Text        `json:"company_name"`
	CompanyAddress           pgtype.Text        `json:"company_address"`
	CompanyPhone             pgtype.Text        `json:"company_phone"`
	CompanyWebsite           pgtype.Text        `json:"company_website"`
	Settings                 []byte             `json:"settings"`
	ExpiresAt                pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateTenant(ctx context.Context, arg CreateTenantParams) (Tenant, error) {
	row := q.db.QueryRow(ctx, createTenant,
		arg.Name,
		arg.Code,
		arg.Description,
		arg.Status,
		arg.ContactEmail,
		arg.ContactPhone,
		arg.MaxUsers,
		arg.MaxProjects,
		arg.MaxStorage,
		arg.LogoObjectKey,
		arg.LoginBackgroundObjectKey,
		arg.CompanyName,
		arg.CompanyAddress,
		arg.CompanyPhone,
		arg.CompanyWebsite,
		arg.Settings,
		arg.ExpiresAt,
	)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Code,
		&i.Description,
		&i.Status,
		&i.ContactEmail,
		&i.ContactPhone,
		&i.MaxUsers,
		&i.MaxProjects,
		&i.MaxStorage,
		&i.UsedStorage,
		&i.LogoObjectKey,
		&i.LoginBackgroundObjectKey,
		&i.CompanyName,
		&i.CompanyAddress,
		&i.CompanyPhone,
		&i.CompanyWebsite,
		&i.Settings,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteDashboardNote = `-- name: DeleteDashboardNote :execrows
DELETE FROM tenant_dashboard_notes
WHERE id = $1 AND tenant_id = $2
`

type DeleteDashboardNoteParams struct {
	NoteID   pgtype.UUID `json:"note_id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) DeleteDashboardNote(ctx context.Context, arg DeleteDashboardNoteParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteDashboardNote, arg.NoteID, arg.TenantID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteManagedUser = `-- name: DeleteManagedUser :execrows
DELETE FROM users WHERE id = $1 AND tenant_id = $2
`

type DeleteManagedUserParams struct {
	UserID   pgtype.UUID `json:"user_id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) DeleteManagedUser(ctx context.Context, arg DeleteManagedUserParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteManagedUser, arg.UserID, arg.TenantID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteTenant = `-- name: DeleteTenant :execrows
DELETE FROM tenants WHERE id = $1
`

func (q *Queries) DeleteTenant(ctx context.Context, tenantID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteTenant, tenantID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getManagedUser = `-- name: GetManagedUser :one
SELECT id, tenant_id, username, password_hash, email, phone, full_name, avatar, role, status, preferences, last_login_at, last_login_ip, password_changed_at, created_at, updated_at FROM users WHERE id = $1 AND tenant_id = $2 LIMIT 1
`

type GetManagedUserParams struct {
	UserID   pgtype.UUID `json:"user_id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) GetManagedUser(ctx context.Context, arg GetManagedUserParams) (User, error) {
	row := q.db.QueryRow(ctx, getManagedUser, arg.UserID, arg.TenantID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Username,
		&i.PasswordHash,
		&i.Email,
		&i.Phone,
		&i.FullName,
		&i.Avatar,
		&i.Role,
		&i.Status,
		&i.Preferences,
		&i.LastLoginAt,
		&i.LastLoginIp,
		&i.PasswordChangedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTenantByIdentifier = `-- name: GetTenantByIdentifier :one
SELECT
  t.id, t.name, t.code, t.description, t.status, t.contact_email, t.contact_phone, t.max_users, t.max_projects, t.max_storage, t.used_storage, t.logo_object_key, t.login_background_object_key, t.company_name, t.company_address, t.company_phone, t.company_website, t.settings, t.expires_at, t.created_at, t.updated_at,
  (SELECT count(*) FROM users u WHERE u.tenant_id = t.id AND u.role <> 'SUPER_ADMIN') AS user_count,
  (SELECT count(*) FROM projects p WHERE p.tenant_id = t.id AND p.status <> 'deleted') AS project_count
FROM tenants t
WHERE t.id::text = $1::text OR lower(t.code) = lower($1::text)
LIMIT 1
`

type GetTenantByIdentifierRow struct {
	ID                       pgtype.UUID        `json:"id"`
	Name                     string             `json:"name"`
	Code                     string             `json:"code"`
	Description              pgtype.Text        `json:"description"`
	Status                   string             `json:"status"`
	ContactEmail             pgtype.Text        `json:"contact_email"`
	ContactPhone             pgtype.Text        `json:"contact_phone"`
	MaxUsers                 int32              `json:"max_users"`
	MaxProjects              int32              `json:"max_projects"`
	MaxStorage               int64              `json:"max_storage"`
	UsedStorage              int64              `json:"used_storage"`
	LogoObjectKey            pgtype.Text        `json:"logo_object_key"`
	LoginBackgroundObjectKey pgtype.Text        `json:"login_background_object_key"`
	CompanyName              pgtype.Text        `json:"company_name"`
	CompanyAddress           pgtype.Text        `json:"company_address"`
	CompanyPhone             pgtype.Text        `json:"company_phone"`
	CompanyWebsite           pgtype.Text        `json:"company_website"`
	Settings                 []byte             `json:"settings"`
	ExpiresAt                pgtype.Timestamptz `json:"expires_at"`
	CreatedAt                pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                pgtype.Timestamptz `json:"updated_at"`
	UserCount                int64              `json:"user_count"`
	ProjectCount             int64              `json:"project_count"`
}

func (q *Queries) GetTenantByIdentifier(ctx context.Context, identifier string) (GetTenantByIdentifierRow, error) {
	row := q.db.QueryRow(ctx, getTenantByIdentifier, identifier)
	var i GetTenantByIdentifierRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Code,
		&i.Description,
		&i.Status,
		&i.ContactEmail,
		&i.ContactPhone,
		&i.MaxUsers,
		&i.MaxProjects,
		&i.MaxStorage,
		&i.UsedStorage,
		&i.LogoObjectKey,
		&i.LoginBackgroundObjectKey,
		&i.CompanyName,
		&i.CompanyAddress,
		&i.CompanyPhone,
		&i.CompanyWebsite,
		&i.Settings,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserCount,
		&i.ProjectCount,
	)
	return i, err
}

const listDashboardNotes = `-- name: ListDashboardNotes :many
SELECT n.id, n.tenant_id, n.content, n.created_by, n.updated_by, n.created_at, n.updated_at,
       COALESCE(NULLIF(creator.full_name, ''), creator.username) AS created_by_username,
       COALESCE(NULLIF(updater.full_name, ''), updater.username, '') AS updated_by_username
FROM tenant_dashboard_notes n
JOIN users creator ON creator.id = n.created_by
LEFT JOIN users updater ON updater.id = n.updated_by
WHERE n.tenant_id = $1
ORDER BY n.updated_at DESC
`

type ListDashboardNotesRow struct {
	ID                pgtype.UUID        `json:"id"`
	TenantID          pgtype.UUID        `json:"tenant_id"`
	Content           string             `json:"content"`
	CreatedBy         pgtype.UUID        `json:"created_by"`
	UpdatedBy         pgtype.UUID        `json:"updated_by"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	CreatedByUsername string             `json:"created_by_username"`
	UpdatedByUsername string             `json:"updated_by_username"`
}

func (q *Queries) ListDashboardNotes(ctx context.Context, tenantID pgtype.UUID) ([]ListDashboardNotesRow, error) {
	rows, err := q.db.Query(ctx, listDashboardNotes, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDashboardNotesRow{}
	for rows.Next() {
		var i ListDashboardNotesRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Content,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatedByUsername,
			&i.UpdatedByUsername,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTenants = `-- name: ListTenants :many
SELECT
  t.id, t.name, t.code, t.description, t.status, t.contact_email, t.contact_phone, t.max_users, t.max_projects, t.max_storage, t.used_storage, t.logo_object_key, t.login_background_object_key, t.company_name, t.company_address, t.company_phone, t.company_website, t.settings, t.expires_at, t.created_at, t.updated_at,
  (SELECT count(*) FROM users u WHERE u.tenant_id = t.id AND u.role <> 'SUPER_ADMIN') AS user_count,
  (SELECT count(*) FROM projects p WHERE p.tenant_id = t.id AND p.status <> 'deleted') AS project_count
FROM tenants t
WHERE ($1::text = '' OR t.name ILIKE '%' || $1 || '%' OR t.code ILIKE '%' || $1 || '%')
  AND ($2::text = '' OR t.status = $2)
ORDER BY t.created_at DESC
LIMIT $4 OFFSET $3
`

type ListTenantsParams struct {
	Keyword    string `json:"keyword"`
	Status     string `json:"status"`
	PageOffset int32  `json:"page_offset"`
	PageLimit  int32  `json:"page_limit"`
}

type ListTenantsRow struct {
	ID                       pgtype.UUID        `json:"id"`
	Name                     string             `json:"name"`
	Code                     string             `json:"code"`
	Description              pgtype.Text        `json:"description"`
	Status                   string             `json:"status"`
	ContactEmail             pgtype.Text        `json:"contact_email"`
	ContactPhone             pgtype.Text        `json:"contact_phone"`
	MaxUsers                 int32              `json:"max_users"`
	MaxProjects              int32              `json:"max_projects"`
	MaxStorage               int64              `json:"max_storage"`
	UsedStorage              int64              `json:"used_storage"`
	LogoObjectKey            pgtype.Text        `json:"logo_object_key"`
	LoginBackgroundObjectKey pgtype.Text        `json:"login_background_object_key"`
	CompanyName              pgtype.Text        `json:"company_name"`
	CompanyAddress           pgtype.Text        `json:"company_address"`
	CompanyPhone             pgtype.Text        `json:"company_phone"`
	CompanyWebsite           pgtype.Text        `json:"company_website"`
	Settings                 []byte             `json:"settings"`
	ExpiresAt                pgtype.Timestamptz `json:"expires_at"`
	CreatedAt                pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                pgtype.Timestamptz `json:"updated_at"`
	UserCount                int64              `json:"user_count"`
	ProjectCount             int64              `json:"project_count"`
}

func (q *Queries) ListTenants(ctx context.Context, arg ListTenantsParams) ([]ListTenantsRow, error) {
	rows, err := q.db.Query(ctx, listTenants,
		arg.Keyword,
		arg.Status,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTenantsRow{}
	for rows.Next() {
		var i ListTenantsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Code,
			&i.Description,
			&i.Status,
			&i.ContactEmail,
			&i.ContactPhone,
			&i.MaxUsers,
			&i.MaxProjects,
			&i.MaxStorage,
			&i.UsedStorage,
			&i.LogoObjectKey,
			&i.LoginBackgroundObjectKey,
			&i.CompanyName,
			&i.CompanyAddress,
			&i.CompanyPhone,
			&i.CompanyWebsite,
			&i.Settings,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserCount,
			&i.ProjectCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT u.id, u.tenant_id, u.username, u.email, u.phone, u.full_name, u.avatar,
       u.role, u.status, u.preferences, u.last_login_at, u.last_login_ip,
       u.password_changed_at, u.created_at, u.updated_at
FROM users u
WHERE u.tenant_id = $1
  AND u.role <> 'SUPER_ADMIN'
  AND ($2::text = '' OR u.username ILIKE '%' || $2 || '%' OR u.full_name ILIKE '%' || $2 || '%' OR u.email ILIKE '%' || $2 || '%')
  AND ($3::text = '' OR u.role = $3)
  AND ($4::text = '' OR u.status = $4)
ORDER BY u.created_at DESC
LIMIT $6 OFFSET $5
`

type ListUsersParams struct {
	TenantID   pgtype.UUID `json:"tenant_id"`
	Keyword    string      `json:"keyword"`
	Role       string      `json:"role"`
	Status     string      `json:"status"`
	PageOffset int32       `json:"page_offset"`
	PageLimit  int32       `json:"page_limit"`
}

type ListUsersRow struct {
	ID                pgtype.UUID        `json:"id"`
	TenantID          pgtype.UUID        `json:"tenant_id"`
	Username          string             `json:"username"`
	Email             pgtype.Text        `json:"email"`
	Phone             pgtype.Text        `json:"phone"`
	FullName          pgtype.Text        `json:"full_name"`
	Avatar            pgtype.Text        `json:"avatar"`
	Role              string             `json:"role"`
	Status            string             `json:"status"`
	Preferences       []byte             `json:"preferences"`
	LastLoginAt       pgtype.Timestamptz `json:"last_login_at"`
	LastLoginIp       pgtype.Text        `json:"last_login_ip"`
	PasswordChangedAt pgtype.Timestamptz `json:"password_changed_at"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]ListUsersRow, error) {
	rows, err := q.db.Query(ctx, listUsers,
		arg.TenantID,
		arg.Keyword,
		arg.Role,
		arg.Status,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUsersRow{}
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Username,
			&i.Email,
			&i.Phone,
			&i.FullName,
			&i.Avatar,
			&i.Role,
			&i.Status,
			&i.Preferences,
			&i.LastLoginAt,
			&i.LastLoginIp,
			&i.PasswordChangedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setTenantStatus = `-- name: SetTenantStatus :one
UPDATE tenants SET status = $1, updated_at = now()
WHERE id = $2
RETURNING id, name, code, description, status, contact_email, contact_phone, max_users, max_projects, max_storage, used_storage, logo_object_key, login_background_object_key, company_name, company_address, company_phone, company_website, settings, expires_at, created_at, updated_at
`

type SetTenantStatusParams struct {
	Status   string      `json:"status"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) SetTenantStatus(ctx context.Context, arg SetTenantStatusParams) (Tenant, error) {
	row := q.db.QueryRow(ctx, setTenantStatus, arg.Status, arg.TenantID)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Code,
		&i.Description,
		&i.Status,
		&i.ContactEmail,
		&i.ContactPhone,
		&i.MaxUsers,
		&i.MaxProjects,
		&i.MaxStorage,
		&i.UsedStorage,
		&i.LogoObjectKey,
		&i.LoginBackgroundObjectKey,
		&i.CompanyName,
		&i.CompanyAddress,
		&i.CompanyPhone,
		&i.CompanyWebsite,
		&i.Settings,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateDashboardNote = `-- name: UpdateDashboardNote :one
UPDATE tenant_dashboard_notes
SET content = $1, updated_by = $2, updated_at = now()
WHERE id = $3 AND tenant_id = $4
RETURNING id, tenant_id, content, created_by, updated_by, created_at, updated_at
`

type UpdateDashboardNoteParams struct {
	Content  string      `json:"content"`
	UserID   pgtype.UUID `json:"user_id"`
	NoteID   pgtype.UUID `json:"note_id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) UpdateDashboardNote(ctx context.Context, arg UpdateDashboardNoteParams) (TenantDashboardNote, error) {
	row := q.db.QueryRow(ctx, updateDashboardNote,
		arg.Content,
		arg.UserID,
		arg.NoteID,
		arg.TenantID,
	)
	var i TenantDashboardNote
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Content,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateManagedUser = `-- name: UpdateManagedUser :one
UPDATE users
SET email = $1, phone = $2, full_name = $3,
    avatar = $4, role = $5, status = $6,
    preferences = $7, updated_at = now()
WHERE id = $8 AND tenant_id = $9
RETURNING id, tenant_id, username, password_hash, email, phone, full_name, avatar, role, status, preferences, last_login_at, last_login_ip, password_changed_at, created_at, updated_at
`

type UpdateManagedUserParams struct {
	Email       pgtype.Text `json:"email"`
	Phone       pgtype.Text `json:"phone"`
	FullName    pgtype.Text `json:"full_name"`
	Avatar      pgtype.Text `json:"avatar"`
	Role        string      `json:"role"`
	Status      string      `json:"status"`
	Preferences []byte      `json:"preferences"`
	UserID      pgtype.UUID `json:"user_id"`
	TenantID    pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) UpdateManagedUser(ctx context.Context, arg UpdateManagedUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateManagedUser,
		arg.Email,
		arg.Phone,
		arg.FullName,
		arg.Avatar,
		arg.Role,
		arg.Status,
		arg.Preferences,
		arg.UserID,
		arg.TenantID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Username,
		&i.PasswordHash,
		&i.Email,
		&i.Phone,
		&i.FullName,
		&i.Avatar,
		&i.Role,
		&i.Status,
		&i.Preferences,
		&i.LastLoginAt,
		&i.LastLoginIp,
		&i.PasswordChangedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTenant = `-- name: UpdateTenant :one
UPDATE tenants
SET name = $1,
    code = $2,
    description = $3,
    status = $4,
    contact_email = $5,
    contact_phone = $6,
    max_users = $7,
    max_projects = $8,
    max_storage = $9,
    logo_object_key = $10,
    login_background_object_key = $11,
    company_name = $12,
    company_address = $13,
    company_phone = $14,
    company_website = $15,
    settings = $16,
    expires_at = $17,
    updated_at = now()
WHERE id = $18
RETURNING id, name, code, description, status, contact_email, contact_phone, max_users, max_projects, max_storage, used_storage, logo_object_key, login_background_object_key, company_name, company_address, company_phone, company_website, settings, expires_at, created_at, updated_at
`

type UpdateTenantParams struct {
	Name                     string             `json:"name"`
	Code                     string             `json:"code"`
	Description              pgtype.Text        `json:"description"`
	Status                   string             `json:"status"`
	ContactEmail             pgtype.Text        `json:"contact_email"`
	ContactPhone             pgtype.Text        `json:"contact_phone"`
	MaxUsers                 int32              `json:"max_users"`
	MaxProjects              int32              `json:"max_projects"`
	MaxStorage               int64              `json:"max_storage"`
	LogoObjectKey            pgtype.Text        `json:"logo_object_key"`
	LoginBackgroundObjectKey pgtype.Text        `json:"login_background_object_key"`
	CompanyName              pgtype.Text        `json:"company_name"`
	CompanyAddress           pgtype.Text        `json:"company_address"`
	CompanyPhone             pgtype.Text        `json:"company_phone"`
	CompanyWebsite           pgtype.Text        `json:"company_website"`
	Settings                 []byte             `json:"settings"`
	ExpiresAt                pgtype.Timestamptz `json:"expires_at"`
	TenantID                 pgtype.UUID        `json:"tenant_id"`
}

func (q *Queries) UpdateTenant(ctx context.Context, arg UpdateTenantParams) (Tenant, error) {
	row := q.db.QueryRow(ctx, updateTenant,
		arg.Name,
		arg.Code,
		arg.Description,
		arg.Status,
		arg.ContactEmail,
		arg.ContactPhone,
		arg.MaxUsers,
		arg.MaxProjects,
		arg.MaxStorage,
		arg.LogoObjectKey,
		arg.LoginBackgroundObjectKey,
		arg.CompanyName,
		arg.CompanyAddress,
		arg.CompanyPhone,
		arg.CompanyWebsite,
		arg.Settings,
		arg.ExpiresAt,
		arg.TenantID,
	)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Code,
		&i.Description,
		&i.Status,
		&i.ContactEmail,
		&i.ContactPhone,
		&i.MaxUsers,
		&i.MaxProjects,
		&i.MaxStorage,
		&i.UsedStorage,
		&i.LogoObjectKey,
		&i.LoginBackgroundObjectKey,
		&i.CompanyName,
		&i.CompanyAddress,
		&i.CompanyPhone,
		&i.CompanyWebsite,
		&i.Settings,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
