using System.Text.Json; using InduForge.Collector.Adapters.Hsl; using InduForge.Collector.Contracts;
namespace InduForge.Collector.Drivers.OrientalMotor.Tests;
public sealed class OrientalMotorDriverTests
{
    [Fact] public void UsesDemoDefaults(){var options=OrientalMotorOptions.Parse(Profile(new{host="127.0.0.1"}));Assert.Equal(44818,options.Port);Assert.Equal((uint)1,options.RunIdleHeader);Assert.Equal((uint)100,options.RpiTimeMs);Assert.Equal(2,options.ActualTimeoutSeconds);}
    [Theory][InlineData("INPUT[048]","input[48]")][InlineData("output[0]","output[0]")] public void NormalizesAddresses(string value,string expected)=>Assert.Equal(expected,OrientalMotorAddress.Parse(Point(value)).Address);
    [Fact] public async Task ReusesClientAndIsolatesFailures(){var client=new FakeClient();var driver=new OrientalMotorEipDriver(new Factory(client));await using var session=await driver.OpenSessionAsync(Profile(new{host="127.0.0.1"}),CancellationToken.None);var result=await((IPointReaderSession)session).ReadAsync(new ReadRequest([Point("input[48]"),Point("input48")]),CancellationToken.None);Assert.Single(client.Requests);Assert.True(result.Values[0].Succeeded);Assert.Equal("ORIENTAL_MOTOR_ADDRESS_INVALID",result.Values[1].ErrorCode);}
    static ConnectionProfile Profile(object config)=>new("oriental-motor",JsonSerializer.SerializeToElement(config),JsonSerializer.SerializeToElement(new{}));static PointReadRequest Point(string address)=>new(address,JsonSerializer.SerializeToElement(new{address}),"int16",1,JsonSerializer.SerializeToElement(new{}));
    sealed class Factory(IHslSpecializedNetworkClient client):IHslSpecializedNetworkClientFactory{public IHslSpecializedNetworkClient Create(HslSpecializedNetworkClientOptions options)=>client;}sealed class FakeClient:IHslSpecializedNetworkClient{public List<HslSpecializedNetworkReadRequest> Requests{get;}=[];public bool IsConnected{get;private set;}public Task<HslOperationResult> ConnectAsync(CancellationToken token){IsConnected=true;return Task.FromResult(HslOperationResult.Success());}public Task<HslOperationResult> CloseAsync(CancellationToken token){IsConnected=false;return Task.FromResult(HslOperationResult.Success());}public Task<HslReadResult> ReadAsync(HslSpecializedNetworkReadRequest request,CancellationToken token){Requests.Add(request);return Task.FromResult(HslReadResult.Success((short)1));}public async ValueTask DisposeAsync(){if(IsConnected)await CloseAsync(CancellationToken.None);}}
}
