/**
 * Grid - CSS Grid 布局组件
 *
 * CSS Grid 布局容器，支持完整的 Grid 属性
 * 分类：布局组件
 *
 * Task 2.3: 重构布局组件注册
 */

import GridComponent from './Grid.vue';

export default {
    type: 'Grid',
    component: GridComponent,
    name: '栅格布局',
    category: '布局组件',
    icon: 'grid-outline',
    thumbnail: null,
    tags: ['布局', 'grid', '栅格', 'css grid'],
    description: 'CSS Grid 布局容器，支持完整的 Grid 属性配置',

    defaultProps: {
        gridTemplateColumns: 'repeat(3, 1fr)',
        gridTemplateRows: 'auto',
        gap: 10,
        rowGap: 10,
        columnGap: 10,
        gridAutoFlow: 'row',
        justifyItems: 'stretch',
        alignItems: 'stretch',
        justifyContent: 'start',
        alignContent: 'start',
        padding: 16,
        backgroundColor: 'transparent',
        borderWidth: 1,
        borderStyle: 'dashed',
        borderColor: '#909399',
        borderRadius: 4,
        boxShadow: 'none',
    },

    defaultStyle: {
        position: 'absolute',
        left: 100,
        top: 100,
        width: 500,
        height: 400,
        zIndex: 1,
    },

    propsSchema: {
        gridTemplateColumns: {
            type: 'string',
            label: '列模板',
            group: '布局',
            description: '定义网格列的大小，如 "repeat(3, 1fr)" 或 "100px 200px 1fr"',
            default: 'repeat(3, 1fr)',
            placeholder: 'repeat(3, 1fr)',
        },
        gridTemplateRows: {
            type: 'string',
            label: '行模板',
            group: '布局',
            description: '定义网格行的大小，如 "auto" 或 "100px 200px"',
            default: 'auto',
            placeholder: 'auto',
        },
        gap: {
            type: 'number',
            label: '网格间距',
            group: '布局',
            description: '行和列的间距（同时设置 rowGap 和 columnGap）',
            default: 10,
            min: 0,
            max: 100,
            unit: 'px',
        },
        rowGap: {
            type: 'number',
            label: '行间距',
            group: '布局',
            description: '网格行之间的间距',
            default: 10,
            min: 0,
            max: 100,
            unit: 'px',
        },
        columnGap: {
            type: 'number',
            label: '列间距',
            group: '布局',
            description: '网格列之间的间距',
            default: 10,
            min: 0,
            max: 100,
            unit: 'px',
        },
        gridAutoFlow: {
            type: 'enum',
            label: '自动流动',
            group: '布局',
            options: [
                { value: 'row', label: '按行填充' },
                { value: 'column', label: '按列填充' },
                { value: 'row dense', label: '按行填充（紧密）' },
                { value: 'column dense', label: '按列填充（紧密）' },
            ],
            default: 'row',
        },
        justifyItems: {
            type: 'enum',
            label: '水平对齐（单元格内）',
            group: '布局',
            options: [
                { value: 'start', label: '起始对齐' },
                { value: 'end', label: '结束对齐' },
                { value: 'center', label: '居中对齐' },
                { value: 'stretch', label: '拉伸填充' },
            ],
            default: 'stretch',
        },
        alignItems: {
            type: 'enum',
            label: '垂直对齐（单元格内）',
            group: '布局',
            options: [
                { value: 'start', label: '起始对齐' },
                { value: 'end', label: '结束对齐' },
                { value: 'center', label: '居中对齐' },
                { value: 'stretch', label: '拉伸填充' },
            ],
            default: 'stretch',
        },
        justifyContent: {
            type: 'enum',
            label: '水平对齐（整体）',
            group: '布局',
            options: [
                { value: 'start', label: '起始对齐' },
                { value: 'end', label: '结束对齐' },
                { value: 'center', label: '居中对齐' },
                { value: 'stretch', label: '拉伸填充' },
                { value: 'space-around', label: '均匀分布（两侧留白）' },
                { value: 'space-between', label: '两端对齐' },
                { value: 'space-evenly', label: '均匀分布（等间距）' },
            ],
            default: 'start',
        },
        alignContent: {
            type: 'enum',
            label: '垂直对齐（整体）',
            group: '布局',
            options: [
                { value: 'start', label: '起始对齐' },
                { value: 'end', label: '结束对齐' },
                { value: 'center', label: '居中对齐' },
                { value: 'stretch', label: '拉伸填充' },
                { value: 'space-around', label: '均匀分布（两侧留白）' },
                { value: 'space-between', label: '两端对齐' },
                { value: 'space-evenly', label: '均匀分布（等间距）' },
            ],
            default: 'start',
        },
        padding: {
            type: 'number',
            label: '内边距',
            group: '布局',
            default: 16,
            min: 0,
            max: 100,
            unit: 'px',
        },
        backgroundColor: {
            type: 'color',
            label: '背景颜色',
            group: '外观',
            default: 'transparent',
        },
        borderWidth: {
            type: 'number',
            label: '边框宽度',
            group: '外观',
            min: 0,
            max: 20,
            default: 1,
            unit: 'px',
        },
        borderStyle: {
            type: 'enum',
            label: '边框样式',
            group: '外观',
            options: [
                { value: 'solid', label: '实线' },
                { value: 'dashed', label: '虚线' },
                { value: 'dotted', label: '点线' },
                { value: 'none', label: '无边框' },
            ],
            default: 'dashed',
        },
        borderColor: {
            type: 'color',
            label: '边框颜色',
            group: '外观',
            default: '#909399',
        },
        borderRadius: {
            type: 'number',
            label: '圆角',
            group: '外观',
            min: 0,
            max: 100,
            default: 4,
            unit: 'px',
        },
        boxShadow: {
            type: 'enum',
            label: '阴影',
            group: '外观',
            options: [
                { value: 'none', label: '无阴影' },
                { value: '0 2px 4px rgba(0,0,0,0.1)', label: '浅阴影' },
                { value: '0 4px 8px rgba(0,0,0,0.15)', label: '中阴影' },
                { value: '0 8px 16px rgba(0,0,0,0.2)', label: '深阴影' },
            ],
            default: 'none',
        },
    },

    eventsSchema: {
        click: { label: '点击', description: '鼠标点击时触发' },
    },

    container: true,
    version: '1.0.0',
};
