using System.Text.Json; using InduForge.Collector.Adapters.Hsl; using InduForge.Collector.Contracts;
namespace InduForge.Collector.Drivers.Yamatake.Tests;
public sealed class YamatakeDriverTests
{
    [Fact] public void UsesDemoDefaults(){var tcp=YamatakeOptions.Parse(Profile(new{host="127.0.0.1"}),HslYamatakeTransport.Tcp);Assert.Equal(2000,tcp.Port);Assert.Equal((byte)1,tcp.Station);var serial=YamatakeOptions.Parse(Profile(new{portName="COM3"}),HslYamatakeTransport.Serial);Assert.Equal(9600,serial.BaudRate);Assert.Equal(8,serial.DataBits);}
    [Theory][InlineData("501","501")][InlineData("S=02;0501","s=2;501")] public void NormalizesAddress(string value,string expected)=>Assert.Equal(expected,YamatakeAddress.Parse(Point(value)).Address);
    [Fact] public async Task ReusesClientAndIsolatesFailures(){var client=new FakeClient();var driver=new YamatakeDigitronTcpDriver(new Factory(client));await using var session=await driver.OpenSessionAsync(Profile(new{host="127.0.0.1"}),CancellationToken.None);var result=await((IPointReaderSession)session).ReadAsync(new ReadRequest([Point("501"),Point("bad")]),CancellationToken.None);Assert.Single(client.Requests);Assert.True(result.Values[0].Succeeded);Assert.Equal("YAMATAKE_ADDRESS_INVALID",result.Values[1].ErrorCode);}
    static ConnectionProfile Profile(object config)=>new("yamatake",JsonSerializer.SerializeToElement(config),JsonSerializer.SerializeToElement(new{})); static PointReadRequest Point(string address)=>new(address,JsonSerializer.SerializeToElement(new{address}),"int16",1,JsonSerializer.SerializeToElement(new{}));
    sealed class Factory(IHslYamatakeClient client):IHslYamatakeClientFactory{public IHslYamatakeClient Create(HslYamatakeClientOptions options)=>client;} sealed class FakeClient:IHslYamatakeClient{public List<HslYamatakeReadRequest> Requests{get;}=[];public bool IsConnected{get;private set;}public Task<HslOperationResult> ConnectAsync(CancellationToken token){IsConnected=true;return Task.FromResult(HslOperationResult.Success());}public Task<HslOperationResult> CloseAsync(CancellationToken token){IsConnected=false;return Task.FromResult(HslOperationResult.Success());}public Task<HslReadResult> ReadAsync(HslYamatakeReadRequest request,CancellationToken token){Requests.Add(request);return Task.FromResult(HslReadResult.Success((short)1));}public async ValueTask DisposeAsync(){if(IsConnected)await CloseAsync(CancellationToken.None);}}
}
