using System.Text.Json; using InduForge.Collector.Adapters.Hsl; using InduForge.Collector.Contracts; using Xunit;
namespace InduForge.Collector.Drivers.Vigor.Tests;
public sealed class VigorDriverTests
{
    [Fact] public void UsesDemoTcpDefaults() { var o = VigorConnectionOptions.Parse(Profile(new { host = "127.0.0.1" }), VigorDriverKind.SerialOverTcp); Assert.Equal(5000, o.Port); Assert.Equal((byte)0, o.Station); Assert.Equal(5000, o.ConnectTimeoutMilliseconds); Assert.Equal(10000, o.ReceiveTimeoutMilliseconds); Assert.Equal(HslDataFormat.DCBA, o.ToHslOptions().DataFormat); }
    [Fact] public void UsesDemoSerialDefaults() { var o = VigorConnectionOptions.Parse(Profile(new { portName = "COM3" }), VigorDriverKind.Serial); Assert.Equal(9600, o.BaudRate); Assert.Equal(8, o.DataBits); Assert.Equal(HslSerialParity.None, o.Parity); }
    [Theory] [InlineData("m100", "bool", "M100")] [InlineData("d100", "int16", "D100")] [InlineData("s=02;c200", "int32", "s=2;C200")] public void NormalizesAddresses(string a, string t, string e) => Assert.Equal(e, VigorAddress.Parse(Point(a, t)).ProtocolAddress);
    [Fact] public void EnforcesCounterWidth() { var ex = Assert.Throws<VigorDriverException>(() => VigorAddress.Parse(Point("C200", "int16"))); Assert.Equal("VIGOR_COUNTER_TYPE_INVALID", ex.Code); }
    [Fact] public async Task SessionReusesClientAndIsolatesFailures() { var c = new FakeClient(); var d = new VigorSerialOverTcpDriver(new FakeFactory(c)); await using var s = await d.OpenSessionAsync(Profile(new { host = "127.0.0.1" }), CancellationToken.None); var r = await ((IPointReaderSession)s).ReadAsync(new ReadRequest([Point("D100", "int16"), Point("D101", "int16"), Point("bad", "int16")]), CancellationToken.None); Assert.Equal(2, c.Requests.Count); Assert.True(r.Values[0].Succeeded); Assert.False(r.Values[1].Succeeded); Assert.Equal("VIGOR_ADDRESS_INVALID", r.Values[2].ErrorCode); }
    private static ConnectionProfile Profile(object c) => new("vigor", JsonSerializer.SerializeToElement(c), JsonSerializer.SerializeToElement(new { })); private static PointReadRequest Point(string a, string t) => new(a, JsonSerializer.SerializeToElement(new { address = a }), t, 1, JsonSerializer.SerializeToElement(new { }));
    private sealed class FakeFactory(IHslVigorClient c) : IHslVigorClientFactory { public IHslVigorClient Create(HslVigorClientOptions o) => c; }
    private sealed class FakeClient : IHslVigorClient { public List<HslVigorReadRequest> Requests { get; } = []; public bool IsConnected { get; private set; } public Task<HslOperationResult> ConnectAsync(CancellationToken c) { IsConnected = true; return Task.FromResult(HslOperationResult.Success()); } public Task<HslOperationResult> CloseAsync(CancellationToken c) { IsConnected = false; return Task.FromResult(HslOperationResult.Success()); } public Task<HslReadResult> ReadAsync(HslVigorReadRequest r, CancellationToken c) { Requests.Add(r); return Task.FromResult(r.Address == "D100" ? HslReadResult.Success((short)1) : HslReadResult.Failure("READ_FAILED", "失败", false)); } public async ValueTask DisposeAsync() { if (IsConnected) await CloseAsync(CancellationToken.None); } }
}
