<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference
      Include="HslCommunication"
      Version="12.9.1"
      GeneratePathProperty="true"
      ExcludeAssets="compile;runtime" />
    <PackageReference Include="System.IO.Ports" Version="6.0.0" />
    <Reference Include="HslCommunication">
      <HintPath>$(PkgHslCommunication)\lib\net451\HslCommunication.dll</HintPath>
      <Private>true</Private>
    </Reference>
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
