/**
 * Auto-registered Element Plus components
 * Shared wrapper renders basic samples that can be dragged onto canvas.
 */

import ElementPlusAuto from './ElementPlusAuto.vue';

// 使用 componentName 作为 key，避免与已有 Row/Text 等基础/布局组件类型冲突
const ZH_NAME_MAP = {
  ElLink: '链接',
  ElText: '文本',
  ElRow: '行（Row）',
  ElCol: '列（Col）',
  ElContainer: '容器',
  ElHeader: '头部',
  ElAside: '侧边栏',
  ElMain: '主体',
  ElFooter: '底部',
  ElSpace: '间距',
  ElDivider: '分割线',
  ElCard: '卡片',
  ElBreadcrumb: '面包屑',
  ElTabs: '选项卡',
  ElSteps: '步骤条',
  ElMenu: '菜单',
  ElDropdown: '下拉菜单',
  ElPagination: '分页',
  ElBadge: '徽章',
  ElAvatar: '头像',
  ElTag: '标签',
  ElTree: '树形控件',
  ElTimeline: '时间线',
  ElCollapse: '折叠面板',
  ElCarousel: '走马灯',
  ElTooltip: '文字提示',
  ElPopover: '气泡卡片',
  ElPopconfirm: '气泡确认',
  ElDialog: '对话框',
  ElDrawer: '抽屉',
  ElAlert: '提示',
  ElUpload: '上传',
  ElRate: '评分',
  ElColorPicker: '取色器',
  ElTransfer: '穿梭框',
  ElInputNumber: '计数器',
  ElRadioGroup: '单选组',
  ElCheckboxGroup: '多选组',
  ElCascader: '级联选择',
  ElTimePicker: '时间选择器',
  ElTimeSelect: '时间下拉',
  ElCalendar: '日历',
  ElDescriptions: '描述列表',
  ElResult: '结果',
  ElSkeleton: '骨架屏',
  ElImage: '图片',
  ElEmpty: '空状态',
  ElStatistic: '统计数值',
  ElBacktop: '回到顶部',
  ElAffix: '固钉',
};

const COMPONENT_CONFIGS = [
  // 已拆分到独立文件的表单类组件不再通过自动注册
  {
    type: 'Row',
    name: 'Row',
    componentName: 'ElRow',
    slotText: '栅格',
    componentProps: { gutter: 12 },
    width: 320,
    height: 96,
    icon: 'grid',
    tags: ['layout', 'grid'],
    description: 'Row 栅格行',
  },
  {
    type: 'Col',
    name: 'Col',
    componentName: 'ElCol',
    slotText: '列',
    componentProps: { span: 12 },
    width: 160,
    height: 64,
    icon: 'grid',
    tags: ['layout', 'grid'],
    description: 'Col 栅格列',
  },
  {
    type: 'Container',
    name: 'Container',
    componentName: 'ElContainer',
    slotText: '容器',
    componentProps: {},
    width: 320,
    height: 160,
    icon: 'layout',
    tags: ['layout', 'container'],
    description: 'Container 布局容器',
  },
  {
    type: 'Header',
    name: 'Header',
    componentName: 'ElHeader',
    slotText: '头部',
    componentProps: { height: '48px' },
    width: 320,
    height: 60,
    icon: 'layout',
    tags: ['layout'],
    description: 'Header 布局头部',
  },
  {
    type: 'Aside',
    name: 'Aside',
    componentName: 'ElAside',
    slotText: '侧边栏',
    componentProps: { width: '120px' },
    width: 180,
    height: 160,
    icon: 'layout',
    tags: ['layout'],
    description: 'Aside 布局侧栏',
  },
  {
    type: 'Main',
    name: 'Main',
    componentName: 'ElMain',
    slotText: '内容区',
    componentProps: {},
    width: 320,
    height: 160,
    icon: 'layout',
    tags: ['layout'],
    description: 'Main 布局主体',
  },
  {
    type: 'Footer',
    name: 'Footer',
    componentName: 'ElFooter',
    slotText: '底部',
    componentProps: { height: '48px' },
    width: 320,
    height: 60,
    icon: 'layout',
    tags: ['layout'],
    description: 'Footer 布局底部',
  },
  {
    type: 'Space',
    name: 'Space',
    componentName: 'ElSpace',
    slotText: '按钮',
    componentProps: { wrap: true, size: 8 },
    width: 240,
    height: 72,
    icon: 'layout',
    tags: ['space', 'layout'],
    description: 'Space 间距容器',
  },
  {
    type: 'Divider',
    name: 'Divider',
    componentName: 'ElDivider',
    slotText: '分割线',
    componentProps: { direction: 'horizontal' },
    width: 240,
    height: 32,
    icon: 'minus',
    tags: ['divider'],
    description: 'Divider 分割线',
  },
  {
    type: 'Card',
    name: 'Card',
    componentName: 'ElCard',
    slotText: '卡片内容',
    componentProps: { shadow: 'always' },
    width: 260,
    height: 160,
    icon: 'board',
    tags: ['card'],
    description: 'Card 卡片',
  },
  {
    type: 'Breadcrumb',
    name: 'Breadcrumb',
    componentName: 'ElBreadcrumb',
    slotText: '',
    componentProps: { separator: '/' },
    width: 260,
    height: 40,
    icon: 'more',
    tags: ['breadcrumb', 'nav'],
    description: 'Breadcrumb 面包屑',
  },
  {
    type: 'Tabs',
    name: 'Tabs',
    componentName: 'ElTabs',
    slotText: '选项卡',
    componentProps: { modelValue: '1' },
    width: 300,
    height: 180,
    icon: 'tabs',
    tags: ['tabs', 'nav'],
    description: 'Tabs 选项卡',
  },
  {
    type: 'Steps',
    name: 'Steps',
    componentName: 'ElSteps',
    slotText: '步骤',
    componentProps: { active: 1, alignCenter: true },
    width: 300,
    height: 120,
    icon: 'flag',
    tags: ['steps', 'progress'],
    description: 'Steps 步骤条',
  },
  {
    type: 'Menu',
    name: 'Menu',
    componentName: 'ElMenu',
    slotText: '菜单',
    componentProps: { defaultActive: '1', mode: 'horizontal' },
    width: 320,
    height: 72,
    icon: 'menu',
    tags: ['menu', 'nav'],
    description: 'Menu 导航菜单',
  },
  {
    type: 'Dropdown',
    name: 'Dropdown',
    componentName: 'ElDropdown',
    slotText: '下拉菜单',
    componentProps: { trigger: 'click' },
    width: 180,
    height: 48,
    icon: 'arrow-down',
    tags: ['dropdown', 'nav'],
    description: 'Dropdown 下拉菜单',
  },
  {
    type: 'Pagination',
    name: 'Pagination',
    componentName: 'ElPagination',
    slotText: '',
    componentProps: { currentPage: 1, pageSize: 10, total: 100, layout: 'prev, pager, next' },
    width: 360,
    height: 48,
    icon: 'more',
    tags: ['pagination'],
    description: 'Pagination 分页',
  },
  {
    type: 'Badge',
    name: 'Badge',
    componentName: 'ElBadge',
    slotText: '消息',
    componentProps: { value: 12, type: 'primary' },
    width: 120,
    height: 32,
    icon: 'notification',
    tags: ['badge'],
    description: 'Badge 徽章',
  },
  {
    type: 'Avatar',
    name: 'Avatar',
    componentName: 'ElAvatar',
    slotText: '',
    componentProps: { size: 48, shape: 'circle', src: 'https://via.placeholder.com/80' },
    width: 60,
    height: 60,
    icon: 'user',
    tags: ['avatar'],
    description: 'Avatar 头像',
  },
  {
    type: 'Tag',
    name: 'Tag',
    componentName: 'ElTag',
    slotText: '标签',
    componentProps: { type: 'success' },
    width: 120,
    height: 32,
    icon: 'tag',
    tags: ['tag'],
    description: 'Tag 标签',
  },
  {
    type: 'Tree',
    name: 'Tree',
    componentName: 'ElTree',
    slotText: '',
    componentProps: {
      data: [
        { label: '一级 1', children: [{ label: '二级 1-1' }] },
        { label: '一级 2', children: [{ label: '二级 2-1' }] },
      ],
    },
    width: 240,
    height: 200,
    icon: 'tree',
    tags: ['tree', 'data'],
    description: 'Tree 树形控件',
  },
  {
    type: 'Timeline',
    name: 'Timeline',
    componentName: 'ElTimeline',
    slotText: '时间节点',
    componentProps: {},
    width: 240,
    height: 180,
    icon: 'time',
    tags: ['timeline'],
    description: 'Timeline 时间线',
  },
  {
    type: 'Collapse',
    name: 'Collapse',
    componentName: 'ElCollapse',
    slotText: '面板内容',
    componentProps: { modelValue: ['1'] },
    width: 260,
    height: 180,
    icon: 'list',
    tags: ['collapse'],
    description: 'Collapse 折叠面板',
  },
  {
    type: 'Carousel',
    name: 'Carousel',
    componentName: 'ElCarousel',
    slotText: '轮播',
    componentProps: { height: '160px', type: 'card' },
    width: 320,
    height: 200,
    icon: 'image',
    tags: ['carousel'],
    description: 'Carousel 走马灯',
  },
  {
    type: 'Tooltip',
    name: 'Tooltip',
    componentName: 'ElTooltip',
    slotText: '提示内容',
    componentProps: { placement: 'top', visible: true },
    width: 120,
    height: 48,
    icon: 'info',
    tags: ['tooltip'],
    description: 'Tooltip 文字提示',
  },
  {
    type: 'Popover',
    name: 'Popover',
    componentName: 'ElPopover',
    slotText: '气泡内容',
    componentProps: { trigger: 'click', width: 200, visible: true },
    width: 180,
    height: 48,
    icon: 'info',
    tags: ['popover'],
    description: 'Popover 气泡卡片',
  },
  {
    type: 'Popconfirm',
    name: 'Popconfirm',
    componentName: 'ElPopconfirm',
    slotText: '确认删除？',
    componentProps: { width: 200, visible: true, title: '确认删除？' },
    width: 200,
    height: 56,
    icon: 'warning',
    tags: ['popconfirm'],
    description: 'Popconfirm 气泡确认框',
  },
  {
    type: 'Dialog',
    name: 'Dialog',
    componentName: 'ElDialog',
    slotText: '对话框内容',
    componentProps: {
      modelValue: true,
      title: '对话框',
      width: '40%',
      modal: false,
      appendToBody: false,
      closeOnClickModal: false,
      showClose: false,
      draggable: true,
    },
    width: 360,
    height: 240,
    icon: 'dialog',
    tags: ['dialog'],
    description: 'Dialog 对话框',
  },
  {
    type: 'Drawer',
    name: 'Drawer',
    componentName: 'ElDrawer',
    slotText: '抽屉内容',
    componentProps: {
      modelValue: true,
      title: '抽屉',
      size: '320px',
      withHeader: true,
      modal: false,
      appendToBody: false,
    },
    width: 320,
    height: 240,
    icon: 'sidebar',
    tags: ['drawer'],
    description: 'Drawer 抽屉',
  },
  {
    type: 'Alert',
    name: 'Alert',
    componentName: 'ElAlert',
    slotText: '提示内容',
    componentProps: { title: '成功提示', type: 'success', closable: false, showIcon: true },
    width: 320,
    height: 64,
    icon: 'info',
    tags: ['alert'],
    description: 'Alert 提示',
  },
  {
    type: 'Upload',
    name: 'Upload',
    componentName: 'ElUpload',
    slotText: '点击上传',
    componentProps: { action: 'https://jsonplaceholder.typicode.com/posts/', limit: 3, drag: true },
    width: 320,
    height: 180,
    icon: 'upload',
    tags: ['upload'],
    description: 'Upload 上传',
  },
  {
    type: 'Rate',
    name: 'Rate',
    componentName: 'ElRate',
    slotText: '',
    componentProps: { modelValue: 4 },
    width: 200,
    height: 48,
    icon: 'star',
    tags: ['rate'],
    description: 'Rate 评分',
  },
  {
    type: 'ColorPicker',
    name: 'ColorPicker',
    componentName: 'ElColorPicker',
    slotText: '',
    componentProps: { modelValue: '#409EFF' },
    width: 120,
    height: 48,
    icon: 'palette',
    tags: ['color'],
    description: 'ColorPicker 取色器',
  },
  {
    type: 'Transfer',
    name: 'Transfer',
    componentName: 'ElTransfer',
    slotText: '',
    componentProps: {
      data: [
        { key: 1, label: '选项 1' },
        { key: 2, label: '选项 2' },
        { key: 3, label: '选项 3' },
        { key: 4, label: '选项 4' },
      ],
      modelValue: [1, 4],
      titles: ['源列表', '目标列表'],
      props: { key: 'key', label: 'label' },
    },
    width: 360,
    height: 220,
    icon: 'arrow-right',
    tags: ['transfer'],
    description: 'Transfer 穿梭框',
  },
  {
    type: 'InputNumber',
    name: 'InputNumber',
    componentName: 'ElInputNumber',
    slotText: '',
    componentProps: { modelValue: 1, min: 0, max: 10 },
    width: 160,
    height: 40,
    icon: 'numbers',
    tags: ['form'],
    description: 'InputNumber 计数器',
  },
  {
    type: 'RadioGroup',
    name: 'RadioGroup',
    componentName: 'ElRadioGroup',
    slotText: '单选',
    componentProps: { modelValue: 'A' },
    width: 220,
    height: 60,
    icon: 'radio',
    tags: ['form', 'radio'],
    description: 'RadioGroup 单选组',
  },
  {
    type: 'CheckboxGroup',
    name: 'CheckboxGroup',
    componentName: 'ElCheckboxGroup',
    slotText: '多选',
    componentProps: { modelValue: ['A'] },
    width: 220,
    height: 60,
    icon: 'checkbox',
    tags: ['form', 'checkbox'],
    description: 'CheckboxGroup 多选组',
  },
  {
    type: 'Cascader',
    name: 'Cascader',
    componentName: 'ElCascader',
    slotText: '',
    componentProps: {
      options: [
        { label: '选项一', value: '1', children: [{ label: '子项 1', value: '1-1' }] },
        { label: '选项二', value: '2', children: [{ label: '子项 2', value: '2-1' }] },
      ],
    },
    width: 220,
    height: 40,
    icon: 'tree',
    tags: ['form', 'cascader'],
    description: 'Cascader 级联选择',
  },
  {
    type: 'TimePicker',
    name: 'TimePicker',
    componentName: 'ElTimePicker',
    slotText: '',
    componentProps: { modelValue: '12:00:00', arrowControl: true },
    width: 200,
    height: 40,
    icon: 'time',
    tags: ['form', 'time'],
    description: 'TimePicker 时间选择',
  },
  {
    type: 'TimeSelect',
    name: 'TimeSelect',
    componentName: 'ElTimeSelect',
    slotText: '',
    componentProps: { start: '08:30', step: '00:30', end: '18:30', modelValue: '10:00' },
    width: 200,
    height: 40,
    icon: 'time',
    tags: ['form', 'time'],
    description: 'TimeSelect 时间下拉',
  },
  {
    type: 'Calendar',
    name: 'Calendar',
    componentName: 'ElCalendar',
    slotText: '',
    componentProps: { modelValue: '2025-01-01' },
    width: 360,
    height: 260,
    icon: 'calendar',
    tags: ['calendar'],
    description: 'Calendar 日历',
  },
  {
    type: 'Descriptions',
    name: 'Descriptions',
    componentName: 'ElDescriptions',
    slotText: '值',
    componentProps: { title: '信息', column: 2, border: true },
    width: 360,
    height: 200,
    icon: 'list',
    tags: ['descriptions'],
    description: 'Descriptions 描述列表',
  },
  {
    type: 'Result',
    name: 'Result',
    componentName: 'ElResult',
    slotText: '',
    componentProps: { icon: 'success', title: '提交成功', subTitle: '您的请求已完成' },
    width: 320,
    height: 220,
    icon: 'info',
    tags: ['result'],
    description: 'Result 结果',
  },
  {
    type: 'Skeleton',
    name: 'Skeleton',
    componentName: 'ElSkeleton',
    slotText: '',
    componentProps: { loading: true, rows: 3, animated: true },
    width: 320,
    height: 120,
    icon: 'loading',
    tags: ['skeleton'],
    description: 'Skeleton 骨架屏',
  },
  {
    type: 'Image',
    name: 'Image',
    componentName: 'ElImage',
    slotText: '',
    componentProps: { src: 'https://via.placeholder.com/240x120', fit: 'cover' },
    width: 240,
    height: 140,
    icon: 'image',
    tags: ['image'],
    description: 'Image 图片',
  },
  {
    type: 'Empty',
    name: 'Empty',
    componentName: 'ElEmpty',
    slotText: '',
    componentProps: { description: '暂无数据' },
    width: 240,
    height: 200,
    icon: 'box',
    tags: ['empty'],
    description: 'Empty 空状态',
  },
  {
    type: 'Statistic',
    name: 'Statistic',
    componentName: 'ElStatistic',
    slotText: '',
    componentProps: { title: '访问量', value: 12345, suffix: '次' },
    width: 200,
    height: 80,
    icon: 'chart',
    tags: ['statistic'],
    description: 'Statistic 统计数值',
  },
  {
    type: 'Backtop',
    name: 'Backtop',
    componentName: 'ElBacktop',
    slotText: '顶部',
    componentProps: { visibilityHeight: 0, right: 16, bottom: 16 },
    width: 80,
    height: 80,
    icon: 'arrow-up',
    tags: ['backtop'],
    description: 'Backtop 回到顶部',
  },
  {
    type: 'Affix',
    name: 'Affix',
    componentName: 'ElAffix',
    slotText: '固定按钮',
    componentProps: { offset: 10 },
    width: 160,
    height: 48,
    icon: 'pin',
    tags: ['affix'],
    description: 'Affix 固钉',
  },
];

const COMPONENT_METAS = {
  ElInput: {
    propsMeta: {
      modelValue: { label: '输入值', type: 'string', group: '组件属性' },
      placeholder: { label: '占位', type: 'string', group: '组件属性' },
      type: {
        label: '类型',
        type: 'enum',
        options: [
          { value: 'text', label: '文本' },
          { value: 'textarea', label: '文本域' },
          { value: 'password', label: '密码' },
          { value: 'number', label: '数字' },
        ],
      },
      clearable: { label: '可清空', type: 'boolean' },
      disabled: { label: '禁用', type: 'boolean' },
      showPassword: { label: '显示密码', type: 'boolean', visible: (p) => p.type === 'password' },
      maxlength: { label: '最大长度', type: 'number' },
      showWordLimit: { label: '显示字数', type: 'boolean' },
      prefixIcon: { label: '前缀图标', type: 'string', description: 'Element Plus Icons 名称' },
      suffixIcon: { label: '后缀图标', type: 'string', description: 'Element Plus Icons 名称' },
    },
    eventsSchema: {
      input: { label: '输入' },
      change: { label: '变更' },
      focus: { label: '获得焦点' },
      blur: { label: '失去焦点' },
      clear: { label: '清空' },
    },
  },
  ElInputNumber: {
    propsMeta: {
      modelValue: { label: '当前值', type: 'number' },
      min: { label: '最小值', type: 'number' },
      max: { label: '最大值', type: 'number' },
      step: { label: '步长', type: 'number' },
      precision: { label: '精度', type: 'number' },
      controls: { label: '显示控制按钮', type: 'boolean' },
      disabled: { label: '禁用', type: 'boolean' },
    },
    eventsSchema: {
      change: { label: '变更' },
      input: { label: '输入' },
      focus: { label: '获得焦点' },
      blur: { label: '失去焦点' },
    },
  },
  ElSelect: {
    propsMeta: {
      modelValue: { label: '选中值', type: 'string' },
      placeholder: { label: '占位', type: 'string' },
      multiple: { label: '多选', type: 'boolean' },
      clearable: { label: '可清空', type: 'boolean' },
      filterable: { label: '可搜索', type: 'boolean' },
      options: { label: '选项', type: 'string', multiline: true, format: 'json', description: '数组 { label, value }' },
    },
    eventsSchema: {
      change: { label: '变更' },
      'visible-change': { label: '下拉显示变化' },
      'remove-tag': { label: '移除标签' },
      clear: { label: '清空' },
      blur: { label: '失去焦点' },
      focus: { label: '获得焦点' },
    },
  },
  ElCascader: {
    propsMeta: {
      modelValue: { label: '选中值', type: 'string', description: '字符串或数组' },
      options: { label: '选项', type: 'string', multiline: true, format: 'json', description: '树形选项' },
      props: { label: '选项配置', type: 'string', multiline: true, format: 'json', description: '如 { checkStrictly, multiple }' },
      clearable: { label: '可清空', type: 'boolean' },
      filterable: { label: '可搜索', type: 'boolean' },
      placeholder: { label: '占位', type: 'string' },
    },
    eventsSchema: {
      change: { label: '变更' },
      'expand-change': { label: '展开变化' },
      blur: { label: '失去焦点' },
      focus: { label: '获得焦点' },
      'visible-change': { label: '下拉显示变化' },
    },
  },
  ElTimePicker: {
    propsMeta: {
      modelValue: { label: '时间', type: 'string' },
      isRange: { label: '范围选择', type: 'boolean' },
      startPlaceholder: { label: '开始占位', type: 'string' },
      endPlaceholder: { label: '结束占位', type: 'string' },
      placeholder: { label: '占位', type: 'string' },
      format: { label: '显示格式', type: 'string' },
      valueFormat: { label: '值格式', type: 'string' },
      arrowControl: { label: '箭头控制', type: 'boolean' },
    },
    eventsSchema: {
      change: { label: '变更' },
      blur: { label: '失去焦点' },
      focus: { label: '获得焦点' },
    },
  },
  ElTimeSelect: {
    propsMeta: {
      modelValue: { label: '时间', type: 'string' },
      start: { label: '开始时间', type: 'string' },
      end: { label: '结束时间', type: 'string' },
      step: { label: '步长', type: 'string' },
      placeholder: { label: '占位', type: 'string' },
    },
    eventsSchema: {
      change: { label: '变更' },
      blur: { label: '失去焦点' },
      focus: { label: '获得焦点' },
    },
  },
  ElDatePicker: {
    propsMeta: {
      modelValue: { label: '日期', type: 'string' },
      type: {
        label: '类型',
        type: 'enum',
        options: [
          { value: 'date', label: '日期' },
          { value: 'datetime', label: '日期时间' },
          { value: 'daterange', label: '日期范围' },
          { value: 'datetimerange', label: '日期时间范围' },
        ],
      },
      placeholder: { label: '占位', type: 'string' },
      startPlaceholder: { label: '开始占位', type: 'string' },
      endPlaceholder: { label: '结束占位', type: 'string' },
      format: { label: '显示格式', type: 'string' },
      valueFormat: { label: '值格式', type: 'string' },
      clearable: { label: '可清空', type: 'boolean' },
      rangeSeparator: { label: '范围分隔符', type: 'string' },
    },
    eventsSchema: {
      change: { label: '变更' },
      blur: { label: '失去焦点' },
      focus: { label: '获得焦点' },
    },
  },
  ElColorPicker: {
    propsMeta: {
      modelValue: { label: '颜色', type: 'string', format: 'color' },
      showAlpha: { label: 'Alpha 通道', type: 'boolean' },
      predefine: { label: '预设颜色', type: 'string', multiline: true, format: 'json' },
    },
    eventsSchema: {
      change: { label: '变更' },
      'active-change': { label: '悬浮改变' },
    },
  },
  ElSwitch: {
    propsMeta: {
      modelValue: { label: '开关值', type: 'boolean' },
      activeText: { label: '开启文案', type: 'string' },
      inactiveText: { label: '关闭文案', type: 'string' },
      activeColor: { label: '开启颜色', type: 'string' },
      inactiveColor: { label: '关闭颜色', type: 'string' },
      inlinePrompt: { label: '行内提示', type: 'boolean' },
      disabled: { label: '禁用', type: 'boolean' },
    },
    eventsSchema: {
      change: { label: '变更' },
    },
  },
  ElSlider: {
    propsMeta: {
      modelValue: { label: '当前值', type: 'number' },
      min: { label: '最小值', type: 'number' },
      max: { label: '最大值', type: 'number' },
      step: { label: '步长', type: 'number' },
      range: { label: '范围', type: 'boolean' },
      showStops: { label: '显示间断点', type: 'boolean' },
      disabled: { label: '禁用', type: 'boolean' },
    },
    eventsSchema: {
      change: { label: '变更' },
      input: { label: '输入' },
    },
  },
  ElRate: {
    propsMeta: {
      modelValue: { label: '分值', type: 'number' },
      max: { label: '最大分', type: 'number' },
      allowHalf: { label: '允许半星', type: 'boolean' },
      showScore: { label: '显示分值', type: 'boolean' },
      texts: { label: '文字提示', type: 'string', multiline: true, format: 'json' },
    },
    eventsSchema: {
      change: { label: '变更' },
    },
  },
  ElTransfer: {
    propsMeta: {
      modelValue: { label: '选中项', type: 'string', multiline: true, format: 'json', description: '目标 key 数组' },
      data: { label: '数据源', type: 'string', multiline: true, format: 'json', description: '数组 { key,label }' },
      titles: { label: '标题', type: 'string', multiline: true, format: 'json' },
      filterable: { label: '可搜索', type: 'boolean' },
    },
    eventsSchema: {
      change: { label: '变更' },
    },
  },
  ElUpload: {
    propsMeta: {
      action: { label: '上传地址', type: 'string' },
      multiple: { label: '多选', type: 'boolean' },
      limit: { label: '数量限制', type: 'number' },
      drag: { label: '拖拽上传', type: 'boolean' },
      listType: {
        label: '列表样式',
        type: 'enum',
        options: [
          { value: 'text', label: '文本' },
          { value: 'picture', label: '图片' },
          { value: 'picture-card', label: '图片卡片' },
        ],
      },
      headers: { label: '请求头', type: 'string', multiline: true, format: 'json' },
      data: { label: '额外参数', type: 'string', multiline: true, format: 'json' },
    },
    eventsSchema: {
      change: { label: '文件列表变更' },
      success: { label: '上传成功' },
      error: { label: '上传失败' },
      remove: { label: '移除文件' },
      preview: { label: '预览' },
    },
  },
};

const buildSchemaFromProps = (componentProps = {}, meta = {}) => {
  const schema = {};
  Object.entries(componentProps).forEach(([key, val]) => {
    const m = meta[key] || {};
    if (m.skip) return;
    let type = m.type;
    if (!type) {
      const inferred = typeof val;
      if (inferred === 'boolean') type = 'boolean';
      else if (inferred === 'number') type = 'number';
      else if (inferred === 'string') type = 'string';
      else type = 'string';
    }
    const entry = {
      type,
      label: m.label || key,
      group: m.group || '组件属性',
      default: m.default !== undefined ? m.default : val,
    };
    if (m.options) entry.options = m.options;
    if (m.multiline) entry.multiline = true;
    if (m.format) entry.format = m.format;
    if (m.description) entry.description = m.description;
    if (m.visible) entry.visible = m.visible;
    schema[`componentProps.${key}`] = entry;
  });
  return schema;
};

const EXCLUDED_TYPES = new Set([
  'ElInput',
  'ElInputNumber',
  'ElSelect',
  'ElCascader',
  'ElTimePicker',
  'ElTimeSelect',
  'ElDatePicker',
  'ElColorPicker',
  'ElSwitch',
  'ElSlider',
  'ElRate',
  'ElTransfer',
  'ElUpload',
  'ElRow',
  'ElCol',
  'ElContainer',
  'ElHeader',
  'ElAside',
  'ElMain',
  'ElFooter',
  'ElSpace',
  'ElDivider',
  'ElCard',
  'ElBreadcrumb',
  'ElTabs',
  'ElSteps',
  'ElMenu',
  'ElDropdown',
  'ElPagination',
  'ElTooltip',
  'ElPopover',
  'ElPopconfirm',
  'ElDialog',
  'ElDrawer',
  'ElTree',
  'ElTimeline',
  'ElCollapse',
  'ElCarousel',
  'ElDescriptions',
  'ElResult',
  'ElSkeleton',
  'ElImage',
  'ElAlert',
  'ElBadge',
  'ElAvatar',
  'ElTag',
  'ElCalendar',
  'ElRadioGroup',
  'ElCheckboxGroup',
]);

const buildDefinition = (item) => {
  const registryType = item.registryType || item.componentName || item.type;
  const zhName = ZH_NAME_MAP[item.componentName] || item.name || registryType;
  const componentPropsDefault = item.componentProps || {};
  const meta = COMPONENT_METAS[registryType] || {};
  const autoSchema = meta.propsSchema || buildSchemaFromProps(componentPropsDefault, meta.propsMeta);
  return {
    type: registryType,
    name: zhName,
    category: 'Element 组件',
    icon: item.icon || 'component',
    thumbnail: null,
    tags: item.tags || [registryType, 'ElementPlus', 'UI'],
    description: item.description || `${zhName} 组件`,
    component: ElementPlusAuto,
    defaultProps: {
      componentName: item.componentName,
      componentProps: componentPropsDefault,
      slotText: item.slotText || zhName,
      advancedProps: {},
    },
    defaultStyle: {
      position: 'absolute',
      left: 100,
      top: 100,
      width: item.width || 200,
      height: item.height || 48,
      zIndex: 1,
    },
    propsSchema: {
      slotText: {
        type: 'string',
        label: '显示文本',
        group: '内容',
        default: item.slotText || zhName,
      },
      ...autoSchema,
      advancedProps: {
        type: 'string',
        label: '高级属性 (JSON)',
        group: '配置',
        multiline: true,
        format: 'json',
        default: '{}',
      },
    },
    eventsSchema: meta.eventsSchema || {},
    container: false,
    version: '1.0.0',
  };
};

const elementPlusAll = COMPONENT_CONFIGS.filter((item) => !EXCLUDED_TYPES.has(item.componentName)).map(buildDefinition);

export default elementPlusAll;
export { elementPlusAll };
