<template>
  <el-form
    ref="formRef"
    :model="formData"
    :rules="rules"
    label-position="top"
    class="mqtt-connection-form"
  >
    <!-- 基础信息 -->
    <div class="form-section">
      <div class="form-section-title">{{ t('connection.basicInfo') }}</div>

      <el-form-item :label="t('connection.name')" prop="name">
        <el-input v-model="formData.name" :placeholder="t('connection.name')" clearable />
      </el-form-item>

      <div class="mqtt-connection-form__grid">
        <el-form-item prop="brokerUrl">
          <template #label>
            <span class="mqtt-connection-form__field-label">
              {{ t('connection.mqtt.brokerHost') }}
              <el-tooltip
                :content="t('connection.mqtt.brokerHostHint')"
                placement="top"
              >
                <IconTablerHelpCircle class="mqtt-connection-form__field-help" />
              </el-tooltip>
            </span>
          </template>
          <div class="mqtt-connection-form__broker-group">
            <el-select
              v-model="formData.protocol"
              class="mqtt-connection-form__protocol-select"
              popper-class="mqtt-connection-form__protocol-popper"
              :aria-label="t('connection.mqtt.protocolAria')"
            >
              <el-option label="mqtt://" value="mqtt" />
              <el-option label="mqtts://" value="mqtts" />
              <el-option label="ws://" value="ws" />
              <el-option label="wss://" value="wss" />
            </el-select>
            <el-input
              v-model="formData.brokerUrl"
              class="mqtt-connection-form__broker-input"
              :placeholder="t('connection.mqtt.brokerExample')"
              clearable
            />
          </div>
        </el-form-item>

        <el-form-item prop="port">
          <template #label>
            <span class="mqtt-connection-form__field-label">
              {{ t('connection.port') }}
              <el-tooltip :content="t('connection.mqtt.portHint')" placement="top">
                <IconTablerHelpCircle class="mqtt-connection-form__field-help" />
              </el-tooltip>
            </span>
          </template>
          <el-input v-model.number="formData.port" inputmode="numeric" :placeholder="t('connection.mqtt.portPlaceholder')" />
        </el-form-item>
      </div>

      <el-form-item prop="clientId">
        <template #label>
          <span class="mqtt-connection-form__field-label">
            {{ t('connection.clientId') }}
            <el-tooltip :content="t('connection.mqtt.clientIdHint')" placement="top">
              <IconTablerHelpCircle class="mqtt-connection-form__field-help" />
            </el-tooltip>
          </span>
        </template>
        <el-input v-model="formData.clientId" :placeholder="t('common.autoGenerated')" clearable>
          <template #append>
            <el-button @click="generateClientId" icon="Refresh">
              {{ t('actions.generate') }}
            </el-button>
          </template>
        </el-input>
      </el-form-item>
    </div>

    <!-- 认证信息 -->
    <div class="form-section">
      <div class="form-section-title">{{ t('connection.authInfo') }}</div>

      <div class="mqtt-connection-form__grid">
        <el-form-item :label="t('connection.username')">
          <el-input
            v-model="formData.username"
            :placeholder="t('connection.optional')"
            clearable
            autocomplete="off"
          />
        </el-form-item>

        <el-form-item :label="t('connection.password')">
          <el-input
            v-model="formData.password"
            type="password"
            :placeholder="t('connection.optional')"
            clearable
            show-password
            autocomplete="new-password"
          />
        </el-form-item>
      </div>
    </div>

    <!-- 连接参数 -->
    <div class="form-section">
      <div class="form-section-title">{{ t('connection.params') }}</div>

      <el-form-item>
        <template #label>
          <span class="mqtt-connection-form__field-label">
            {{ t('connection.mqtt.qos') }}
            <el-tooltip :content="t('connection.mqtt.qosHint')" placement="top">
              <IconTablerHelpCircle class="mqtt-connection-form__field-help" />
            </el-tooltip>
          </span>
        </template>
        <el-radio-group v-model="formData.qos">
          <el-radio :label="0">{{ t('connection.mqtt.qos0') }}</el-radio>
          <el-radio :label="1">{{ t('connection.mqtt.qos1') }}</el-radio>
          <el-radio :label="2">{{ t('connection.mqtt.qos2') }}</el-radio>
        </el-radio-group>
      </el-form-item>

      <div class="mqtt-connection-form__grid">
        <el-form-item>
          <template #label>
            <span class="mqtt-connection-form__field-label">
              {{ t('connection.mqtt.keepalive') }}
              <el-tooltip :content="t('connection.mqtt.keepaliveHint')" placement="top">
                <IconTablerHelpCircle class="mqtt-connection-form__field-help" />
              </el-tooltip>
            </span>
          </template>
          <el-input v-model.number="formData.keepalive" inputmode="numeric" placeholder="60">
            <template #append>{{ t('common.seconds') }}</template>
          </el-input>
        </el-form-item>

        <el-form-item>
          <template #label>
            <span class="mqtt-connection-form__field-label">
              {{ t('connection.mqtt.timeout') }}
              <el-tooltip :content="t('connection.mqtt.timeoutHint')" placement="top">
                <IconTablerHelpCircle class="mqtt-connection-form__field-help" />
              </el-tooltip>
            </span>
          </template>
          <el-input
            v-model.number="formData.connectTimeout"
            inputmode="numeric"
            placeholder="30000"
          >
            <template #append>{{ t('common.milliseconds') }}</template>
          </el-input>
        </el-form-item>
      </div>

      <el-form-item>
        <template #label>
          <span class="mqtt-connection-form__field-label">
            {{ t('connection.mqtt.cleanSession') }}
            <el-tooltip
              :content="t('connection.mqtt.cleanSessionHint')"
              placement="top"
            >
              <IconTablerHelpCircle class="mqtt-connection-form__field-help" />
            </el-tooltip>
          </span>
        </template>
        <el-switch v-model="formData.cleanSession" />
        <span class="form-item-tip ml-2">
          {{ formData.cleanSession ? t('connection.mqtt.newSession') : t('connection.mqtt.keepSession') }}
        </span>
      </el-form-item>

      <el-form-item>
        <template #label>
          <span class="mqtt-connection-form__field-label">
            {{ t('connection.mqtt.reconnect') }}
            <el-tooltip :content="t('connection.mqtt.reconnectHint')" placement="top">
              <IconTablerHelpCircle class="mqtt-connection-form__field-help" />
            </el-tooltip>
          </span>
        </template>
        <el-input v-model.number="formData.reconnectPeriod" inputmode="numeric" placeholder="5000">
          <template #append>{{ t('common.milliseconds') }}</template>
        </el-input>
      </el-form-item>
    </div>

    <!-- 高级选项 -->
    <el-collapse v-model="activeCollapse" class="mt-4">
      <el-collapse-item :title="t('connection.willMessage')" name="will">
        <el-form-item>
          <template #label>
            <span class="mqtt-connection-form__field-label">
              {{ t('connection.mqtt.willTopic') }}
              <el-tooltip
                :content="t('connection.mqtt.willTopicHint')"
                placement="top"
              >
                <IconTablerHelpCircle class="mqtt-connection-form__field-help" />
              </el-tooltip>
            </span>
          </template>
          <el-input v-model="formData.will.topic" :placeholder="t('connection.mqtt.willTopicExample')" clearable />
        </el-form-item>

        <el-form-item :label="t('connection.mqtt.willPayload')">
          <el-input
            v-model="formData.will.payload"
            type="textarea"
            :rows="3"
            :placeholder="t('connection.mqtt.willPayloadExample')"
            clearable
          />
        </el-form-item>

        <el-form-item :label="t('connection.mqtt.willQos')">
          <el-radio-group v-model="formData.will.qos">
            <el-radio :label="0">{{ t('connection.mqtt.qos0') }}</el-radio>
            <el-radio :label="1">{{ t('connection.mqtt.qos1') }}</el-radio>
            <el-radio :label="2">{{ t('connection.mqtt.qos2') }}</el-radio>
          </el-radio-group>
        </el-form-item>

        <el-form-item>
          <template #label>
            <span class="mqtt-connection-form__field-label">
              {{ t('connection.mqtt.willRetain') }}
              <el-tooltip
                :content="t('connection.mqtt.willRetainHint')"
                placement="top"
              >
                <IconTablerHelpCircle class="mqtt-connection-form__field-help" />
              </el-tooltip>
            </span>
          </template>
          <el-switch v-model="formData.will.retain" />
        </el-form-item>
      </el-collapse-item>

      <el-collapse-item :title="t('connection.sslTlsConfig')" name="ssl">
        <el-form-item :label="t('connection.caCertificate')">
          <el-input v-model="formData.sslConfig.ca" type="textarea" :rows="4" placeholder="PEM" />
        </el-form-item>

        <el-form-item :label="t('connection.clientCertificate')">
          <el-input v-model="formData.sslConfig.cert" type="textarea" :rows="4" placeholder="PEM" />
        </el-form-item>

        <el-form-item :label="t('connection.clientKey')">
          <el-input v-model="formData.sslConfig.key" type="textarea" :rows="4" placeholder="PEM" />
        </el-form-item>

        <el-form-item>
          <template #label>
            <span class="mqtt-connection-form__field-label">
              {{ t('connection.mqtt.verifyServer') }}
              <el-tooltip
                :content="t('connection.mqtt.verifyServerHint')"
                placement="top"
              >
                <IconTablerHelpCircle class="mqtt-connection-form__field-help" />
              </el-tooltip>
            </span>
          </template>
          <el-switch v-model="formData.sslConfig.rejectUnauthorized" />
        </el-form-item>
      </el-collapse-item>
    </el-collapse>
  </el-form>
</template>

<script setup lang="ts">
import { ref, watch, onMounted } from 'vue'
import { getDefaultConfig } from '@/config/connectionTypes'
import { t } from '@/i18n/runtime'
import IconTablerHelpCircle from '~icons/tabler/help-circle'

const props = defineProps({
  modelValue: {
    type: Object,
    default: () => ({}),
  },
  mode: {
    type: String,
    default: 'create', // 'create' | 'edit'
    validator: (value) => ['create', 'edit'].includes(value),
  },
})

const emit = defineEmits(['update:modelValue', 'validate'])

const formRef = ref(null)
const activeCollapse = ref([])

// 防止循环更新的标志
const isUpdatingFromParent = ref(false)

// 表单数据
const formData = ref({
  name: '',
  brokerUrl: 'localhost',
  protocol: 'mqtt',
  port: 1883,
  clientId: '',
  username: '',
  password: '',
  keepalive: 60,
  cleanSession: true,
  qos: 0,
  reconnectPeriod: 5000,
  connectTimeout: 30000,
  will: {
    topic: '',
    payload: '',
    qos: 0,
    retain: false,
  },
  sslConfig: {
    ca: '',
    cert: '',
    key: '',
    rejectUnauthorized: false,
  },
})

// 验证规则
const rules = {
  name: [
    { required: true, message: t('connection.name'), trigger: 'blur' },
    {
      min: 2,
      max: 100,
      message: t('subscription.nameLengthError'),
      trigger: 'blur',
    },
  ],
  brokerUrl: [{ required: true, message: t('connection.brokerUrl'), trigger: 'blur' }],
  port: [{ required: true, message: t('connection.port'), trigger: 'blur' }],
}

// 初始化表单数据
onMounted(() => {
  isUpdatingFromParent.value = true
  if (props.mode === 'create') {
    // 创建模式：使用默认配置
    const defaultConfig = getDefaultConfig('mqtt')
    const newData = { ...defaultConfig, ...props.modelValue }
    // 确保 will 和 sslConfig 始终是对象
    if (!newData.will || typeof newData.will !== 'object') {
      newData.will = { topic: '', payload: '', qos: 0, retain: false }
    }
    if (!newData.sslConfig || typeof newData.sslConfig !== 'object') {
      newData.sslConfig = {
        ca: '',
        cert: '',
        key: '',
        rejectUnauthorized: false,
      }
    }
    formData.value = newData
  } else {
    // 编辑模式：使用传入的数据
    const newData = { ...formData.value, ...props.modelValue }
    // 确保 will 和 sslConfig 始终是对象
    if (!newData.will || typeof newData.will !== 'object') {
      newData.will = { topic: '', payload: '', qos: 0, retain: false }
    }
    if (!newData.sslConfig || typeof newData.sslConfig !== 'object') {
      newData.sslConfig = {
        ca: '',
        cert: '',
        key: '',
        rejectUnauthorized: false,
      }
    }
    formData.value = newData
  }
  // 使用 setTimeout 确保更新完成后再重置标志
  setTimeout(() => {
    isUpdatingFromParent.value = false
  }, 0)
})

// 监听协议变化，自动更新默认端口
watch(
  () => formData.value.protocol,
  (newProtocol) => {
    const portMap = {
      mqtt: 1883,
      mqtts: 8883,
      ws: 8083,
      wss: 8084,
    }
    if (!isUpdatingFromParent.value) {
      formData.value.port = portMap[newProtocol] || 1883
    }
  },
)

// 监听表单数据变化，向上传递
watch(
  formData,
  (newValue) => {
    // 只有在不是从父组件更新时才向上传递
    if (!isUpdatingFromParent.value) {
      emit('update:modelValue', { ...newValue })
    }
  },
  { deep: true },
)

// 监听外部数据变化
watch(
  () => props.modelValue,
  (newValue) => {
    if (newValue && Object.keys(newValue).length > 0) {
      isUpdatingFromParent.value = true
      const newData = { ...formData.value, ...newValue }
      // 确保 will 和 sslConfig 始终是对象
      if (!newData.will || typeof newData.will !== 'object') {
        newData.will = { topic: '', payload: '', qos: 0, retain: false }
      }
      if (!newData.sslConfig || typeof newData.sslConfig !== 'object') {
        newData.sslConfig = {
          ca: '',
          cert: '',
          key: '',
          rejectUnauthorized: false,
        }
      }
      formData.value = newData
      setTimeout(() => {
        isUpdatingFromParent.value = false
      }, 0)
    }
  },
  { deep: true },
)

// 生成客户端 ID
const generateClientId = () => {
  const randomStr = Math.random().toString(36).substring(2, 10)
  formData.value.clientId = `induforge_${randomStr}`
}

/**
 * 验证表单
 */
const validate = async () => {
  if (!formRef.value) return false

  try {
    await formRef.value.validate()
    emit('validate', true, formData.value)
    return true
  } catch {
    emit('validate', false, null)
    return false
  }
}

/**
 * 重置表单
 */
const resetFields = () => {
  if (formRef.value) {
    formRef.value.resetFields()
  }
}

/**
 * 清空验证
 */
const clearValidate = () => {
  if (formRef.value) {
    formRef.value.clearValidate()
  }
}

// 暴露方法给父组件
defineExpose({
  validate,
  resetFields,
  clearValidate,
  formData,
})
</script>

<style scoped>
.mqtt-connection-form {
  padding: 20px;
}

.form-section {
  margin-bottom: 24px;
  padding: 16px;
  background-color: var(--dc-surface-muted);
  border-radius: 4px;
}

.form-section-title {
  font-size: 14px;
  font-weight: 600;
  color: var(--dc-text);
  margin-bottom: 16px;
  padding-bottom: 8px;
  border-bottom: 1px solid var(--dc-border);
}

.form-item-tip {
  font-size: 12px;
  color: var(--dc-text-muted);
  margin-left: 8px;
}

.mqtt-connection-form__field-label {
  display: inline-flex;
  align-items: center;
  gap: 4px;
}

.mqtt-connection-form__field-help {
  width: 14px;
  height: 14px;
  color: var(--dc-text-muted);
  cursor: help;
}

.mqtt-connection-form__field-help:hover {
  color: var(--el-color-primary);
}

.mqtt-connection-form__grid {
  display: grid;
  grid-template-columns: repeat(2, minmax(0, 1fr));
  gap: 0 12px;
}

.mqtt-connection-form__grid > .el-form-item {
  min-width: 0;
}

.form-actions {
  display: flex;
  justify-content: flex-end;
  gap: 12px;
  padding-top: 24px;
  border-top: 1px solid var(--dc-border);
}

:deep(.el-collapse-item__header) {
  font-weight: 500;
}

:deep(.el-radio) {
  margin-right: 20px;
}

.mqtt-connection-form__broker-group {
  display: flex;
  width: 100%;
}

.mqtt-connection-form__protocol-select {
  flex: 0 0 126px;
}

.mqtt-connection-form__broker-input {
  flex: 1 1 auto;
  min-width: 0;
}

.mqtt-connection-form__protocol-select :deep(.el-select__wrapper) {
  min-height: 32px;
  padding: 0 12px;
  border-radius: var(--el-border-radius-base) 0 0 var(--el-border-radius-base);
  background: var(--dc-surface-muted);
  box-shadow: 0 0 0 1px var(--el-border-color) inset;
}

.mqtt-connection-form__protocol-select :deep(.el-select__selected-item) {
  min-width: 0;
}

.mqtt-connection-form__protocol-select :deep(.el-select__placeholder) {
  color: var(--dc-text-secondary);
}

.mqtt-connection-form__broker-input :deep(.el-input__wrapper) {
  margin-left: -1px;
  border-radius: 0 var(--el-border-radius-base) var(--el-border-radius-base) 0;
}

.mqtt-connection-form__protocol-select:hover
  + .mqtt-connection-form__broker-input
  :deep(.el-input__wrapper),
.mqtt-connection-form__protocol-select.is-focused
  + .mqtt-connection-form__broker-input
  :deep(.el-input__wrapper) {
  position: relative;
  z-index: 0;
}

@media (max-width: 760px) {
  .mqtt-connection-form__grid {
    grid-template-columns: 1fr;
  }

  .mqtt-connection-form__protocol-select {
    flex-basis: 118px;
  }
}
</style>
