<template>
  <el-form
    ref="formRef"
    :model="formData"
    :rules="rules"
    label-width="140px"
    class="mqtt-connection-form"
  >
    <!-- 基础信息 -->
    <div class="form-section">
      <div class="form-section-title">{{ t("connection.basicInfo") }}</div>

      <el-form-item :label="t('connection.name')" prop="name">
        <el-input
          v-model="formData.name"
          :placeholder="t('connection.name')"
          clearable
        />
      </el-form-item>

      <el-form-item :label="t('connection.brokerUrl')" prop="brokerUrl">
        <el-input
          v-model="formData.brokerUrl"
          placeholder="例如: broker.emqx.io"
          clearable
        >
          <template #prepend>
            <el-select v-model="formData.protocol" style="width: 90px">
              <el-option label="mqtt://" value="mqtt" />
              <el-option label="mqtts://" value="mqtts" />
              <el-option label="ws://" value="ws" />
              <el-option label="wss://" value="wss" />
            </el-select>
          </template>
        </el-input>
      </el-form-item>

      <el-form-item :label="t('connection.port')" prop="port">
        <el-input-number
          v-model="formData.port"
          :min="1"
          :max="65535"
          :placeholder="t('connection.port')"
          style="width: 100%"
        />
      </el-form-item>

      <el-form-item :label="t('connection.clientId')" prop="clientId">
        <el-input
          v-model="formData.clientId"
          :placeholder="t('common.autoGenerated')"
          clearable
        >
          <template #append>
            <el-button @click="generateClientId" icon="Refresh">
              {{ t("actions.generate") }}
            </el-button>
          </template>
        </el-input>
      </el-form-item>
    </div>

    <!-- 认证信息 -->
    <div class="form-section">
      <div class="form-section-title">{{ t("connection.authInfo") }}</div>

      <el-form-item :label="t('connection.username')">
        <el-input
          v-model="formData.username"
          :placeholder="t('connection.optional')"
          clearable
          autocomplete="off"
        />
      </el-form-item>

      <el-form-item :label="t('connection.password')">
        <el-input
          v-model="formData.password"
          type="password"
          :placeholder="t('connection.optional')"
          clearable
          show-password
          autocomplete="new-password"
        />
      </el-form-item>
    </div>

    <!-- 连接参数 -->
    <div class="form-section">
      <div class="form-section-title">{{ t("connection.params") }}</div>

      <el-form-item label="QoS">
        <el-radio-group v-model="formData.qos">
          <el-radio :label="0">0 - At most once</el-radio>
          <el-radio :label="1">1 - At least once</el-radio>
          <el-radio :label="2">2 - Exactly once</el-radio>
        </el-radio-group>
      </el-form-item>

      <el-form-item :label="t('connection.keepAlive')">
        <el-input-number
          v-model="formData.keepalive"
          :min="10"
          :max="300"
          :placeholder="t('common.seconds')"
          style="width: 100%"
        />
        <span class="form-item-tip">{{ t("connection.keepAliveHint") }}</span>
      </el-form-item>

      <el-form-item :label="t('connection.cleanSession')">
        <el-switch v-model="formData.cleanSession" />
        <span class="form-item-tip ml-2">
          {{ t("connection.cleanSessionHint") }}
        </span>
      </el-form-item>

      <el-form-item :label="t('connection.connectionTimeout')">
        <el-input-number
          v-model="formData.connectTimeout"
          :min="1000"
          :max="60000"
          :step="1000"
          :placeholder="t('common.milliseconds')"
          style="width: 100%"
        />
        <span class="form-item-tip">{{ t("connection.timeoutHint") }}</span>
      </el-form-item>

      <el-form-item :label="t('connection.reconnectPeriod')">
        <el-input-number
          v-model="formData.reconnectPeriod"
          :min="1000"
          :max="60000"
          :step="1000"
          :placeholder="t('common.milliseconds')"
          style="width: 100%"
        />
        <span class="form-item-tip">{{ t("connection.timeoutHint") }}</span>
      </el-form-item>
    </div>

    <!-- 高级选项 -->
    <el-collapse v-model="activeCollapse" class="mt-4">
      <el-collapse-item :title="t('connection.willMessage')" name="will">
        <el-form-item :label="t('connection.willTopic')">
          <el-input
            v-model="formData.will.topic"
            placeholder="例如: device/status"
            clearable
          />
        </el-form-item>

        <el-form-item :label="t('connection.willPayload')">
          <el-input
            v-model="formData.will.payload"
            type="textarea"
            :rows="3"
            placeholder="例如: offline"
            clearable
          />
        </el-form-item>

        <el-form-item :label="t('connection.willQos')">
          <el-radio-group v-model="formData.will.qos">
            <el-radio :label="0">0</el-radio>
            <el-radio :label="1">1</el-radio>
            <el-radio :label="2">2</el-radio>
          </el-radio-group>
        </el-form-item>

        <el-form-item :label="t('connection.willRetain')">
          <el-switch v-model="formData.will.retain" />
        </el-form-item>
      </el-collapse-item>

      <el-collapse-item :title="t('connection.sslTlsConfig')" name="ssl">
        <el-form-item :label="t('connection.caCertificate')">
          <el-input
            v-model="formData.sslConfig.ca"
            type="textarea"
            :rows="4"
            placeholder="PEM"
          />
        </el-form-item>

        <el-form-item :label="t('connection.clientCertificate')">
          <el-input
            v-model="formData.sslConfig.cert"
            type="textarea"
            :rows="4"
            placeholder="PEM"
          />
        </el-form-item>

        <el-form-item :label="t('connection.clientKey')">
          <el-input
            v-model="formData.sslConfig.key"
            type="textarea"
            :rows="4"
            placeholder="PEM"
          />
        </el-form-item>

        <el-form-item :label="t('connection.validateServerCert')">
          <el-switch v-model="formData.sslConfig.rejectUnauthorized" />
        </el-form-item>
      </el-collapse-item>
    </el-collapse>
  </el-form>
</template>

<script setup lang="ts">
import { ref, watch, onMounted } from "vue";
import { getDefaultConfig } from "@/config/connectionTypes";
import { t } from "@/i18n/runtime";

const props = defineProps({
  modelValue: {
    type: Object,
    default: () => ({}),
  },
  mode: {
    type: String,
    default: "create", // 'create' | 'edit'
    validator: (value) => ["create", "edit"].includes(value),
  },
});

const emit = defineEmits(["update:modelValue", "validate"]);

const formRef = ref(null);
const activeCollapse = ref([]);

// 防止循环更新的标志
const isUpdatingFromParent = ref(false);

// 表单数据
const formData = ref({
  name: "",
  brokerUrl: "localhost",
  protocol: "mqtt",
  port: 1883,
  clientId: "",
  username: "",
  password: "",
  keepalive: 60,
  cleanSession: true,
  qos: 0,
  reconnectPeriod: 5000,
  connectTimeout: 30000,
  will: {
    topic: "",
    payload: "",
    qos: 0,
    retain: false,
  },
  sslConfig: {
    ca: "",
    cert: "",
    key: "",
    rejectUnauthorized: false,
  },
});

// 验证规则
const rules = {
  name: [
    { required: true, message: t("connection.name"), trigger: "blur" },
    {
      min: 2,
      max: 100,
      message: t("subscription.nameLengthError"),
      trigger: "blur",
    },
  ],
  brokerUrl: [
    { required: true, message: t("connection.brokerUrl"), trigger: "blur" },
  ],
  port: [{ required: true, message: t("connection.port"), trigger: "blur" }],
};

// 初始化表单数据
onMounted(() => {
  isUpdatingFromParent.value = true;
  if (props.mode === "create") {
    // 创建模式：使用默认配置
    const defaultConfig = getDefaultConfig("mqtt");
    const newData = { ...defaultConfig, ...props.modelValue };
    // 确保 will 和 sslConfig 始终是对象
    if (!newData.will || typeof newData.will !== "object") {
      newData.will = { topic: "", payload: "", qos: 0, retain: false };
    }
    if (!newData.sslConfig || typeof newData.sslConfig !== "object") {
      newData.sslConfig = {
        ca: "",
        cert: "",
        key: "",
        rejectUnauthorized: false,
      };
    }
    formData.value = newData;
  } else {
    // 编辑模式：使用传入的数据
    const newData = { ...formData.value, ...props.modelValue };
    // 确保 will 和 sslConfig 始终是对象
    if (!newData.will || typeof newData.will !== "object") {
      newData.will = { topic: "", payload: "", qos: 0, retain: false };
    }
    if (!newData.sslConfig || typeof newData.sslConfig !== "object") {
      newData.sslConfig = {
        ca: "",
        cert: "",
        key: "",
        rejectUnauthorized: false,
      };
    }
    formData.value = newData;
  }
  // 使用 setTimeout 确保更新完成后再重置标志
  setTimeout(() => {
    isUpdatingFromParent.value = false;
  }, 0);
});

// 监听协议变化，自动更新默认端口
watch(
  () => formData.value.protocol,
  (newProtocol) => {
    const portMap = {
      mqtt: 1883,
      mqtts: 8883,
      ws: 8083,
      wss: 8084,
    };
    if (!isUpdatingFromParent.value) {
      formData.value.port = portMap[newProtocol] || 1883;
    }
  },
);

// 监听表单数据变化，向上传递
watch(
  formData,
  (newValue) => {
    // 只有在不是从父组件更新时才向上传递
    if (!isUpdatingFromParent.value) {
      emit("update:modelValue", { ...newValue });
    }
  },
  { deep: true },
);

// 监听外部数据变化
watch(
  () => props.modelValue,
  (newValue) => {
    if (newValue && Object.keys(newValue).length > 0) {
      isUpdatingFromParent.value = true;
      const newData = { ...formData.value, ...newValue };
      // 确保 will 和 sslConfig 始终是对象
      if (!newData.will || typeof newData.will !== "object") {
        newData.will = { topic: "", payload: "", qos: 0, retain: false };
      }
      if (!newData.sslConfig || typeof newData.sslConfig !== "object") {
        newData.sslConfig = {
          ca: "",
          cert: "",
          key: "",
          rejectUnauthorized: false,
        };
      }
      formData.value = newData;
      setTimeout(() => {
        isUpdatingFromParent.value = false;
      }, 0);
    }
  },
  { deep: true },
);

// 生成客户端 ID
const generateClientId = () => {
  const randomStr = Math.random().toString(36).substring(2, 10);
  formData.value.clientId = `induforge_${randomStr}`;
};

/**
 * 验证表单
 */
const validate = async () => {
  if (!formRef.value) return false;

  try {
    await formRef.value.validate();
    emit("validate", true, formData.value);
    return true;
  } catch {
    emit("validate", false, null);
    return false;
  }
};

/**
 * 重置表单
 */
const resetFields = () => {
  if (formRef.value) {
    formRef.value.resetFields();
  }
};

/**
 * 清空验证
 */
const clearValidate = () => {
  if (formRef.value) {
    formRef.value.clearValidate();
  }
};

// 暴露方法给父组件
defineExpose({
  validate,
  resetFields,
  clearValidate,
  formData,
});
</script>

<style scoped>
.mqtt-connection-form {
  padding: 20px;
}

.form-section {
  margin-bottom: 24px;
  padding: 16px;
  background-color: #f5f7fa;
  border-radius: 4px;
}

.form-section-title {
  font-size: 14px;
  font-weight: 600;
  color: #303133;
  margin-bottom: 16px;
  padding-bottom: 8px;
  border-bottom: 1px solid #dcdfe6;
}

.form-item-tip {
  font-size: 12px;
  color: #909399;
  margin-left: 8px;
}

.form-actions {
  display: flex;
  justify-content: flex-end;
  gap: 12px;
  padding-top: 24px;
  border-top: 1px solid #dcdfe6;
}

:deep(.el-collapse-item__header) {
  font-weight: 500;
}

:deep(.el-radio) {
  margin-right: 20px;
}
</style>
