<template>
  <el-dialog
    v-model="visible"
    :title="t('connection.detailsTitle')"
    width="600px"
  >
    <el-descriptions :column="1" border v-if="connection">
      <el-descriptions-item :label="t('connection.name')">{{
        connection.name
      }}</el-descriptions-item>
      <el-descriptions-item :label="t('connection.connectionTypeLabel')">{{
        getConnectionTypeLabel(connection.type)
      }}</el-descriptions-item>
      <el-descriptions-item :label="t('connection.connectionStatus')">
        <el-tag
          :type="
            connection.status === 'connected'
              ? 'success'
              : connection.status === 'error'
                ? 'danger'
                : connection.status === 'disconnected'
                  ? 'warning'
                  : 'info'
          "
        >
          {{ getStatusLabel(connection.status) }}
        </el-tag>
      </el-descriptions-item>
      <template
        v-if="connection.type === 'relational' && connection.relationalConfig"
      >
        <el-descriptions-item :label="t('connection.dbType')">{{
          connection.relationalConfig.dbType
        }}</el-descriptions-item>
        <el-descriptions-item :label="t('connection.host')">{{
          connection.relationalConfig.host
        }}</el-descriptions-item>
        <el-descriptions-item :label="t('connection.port')">{{
          connection.relationalConfig.port
        }}</el-descriptions-item>
        <el-descriptions-item :label="t('connection.database')">{{
          connection.relationalConfig.database
        }}</el-descriptions-item>
        <el-descriptions-item :label="t('connection.username')">{{
          connection.relationalConfig.username
        }}</el-descriptions-item>
      </template>
      <template v-if="connection.type === 'mqtt' && connection.mqttConfig">
        <el-descriptions-item :label="t('connection.protocol')">{{
          connection.mqttConfig.protocol
        }}</el-descriptions-item>
        <el-descriptions-item :label="t('connection.brokerAddress')">{{
          connection.mqttConfig.brokerUrl
        }}</el-descriptions-item>
        <el-descriptions-item :label="t('connection.port')">{{
          connection.mqttConfig.port
        }}</el-descriptions-item>
        <el-descriptions-item :label="t('connection.clientId')">{{
          connection.mqttConfig.clientId || t("common.autoGenerated")
        }}</el-descriptions-item>
        <el-descriptions-item :label="t('connection.username')">{{
          connection.mqttConfig.username || "-"
        }}</el-descriptions-item>
        <el-descriptions-item :label="t('connection.qos')">{{
          connection.mqttConfig.qos
        }}</el-descriptions-item>
        <el-descriptions-item :label="t('connection.keepaliveSeconds')"
          >{{ connection.mqttConfig.keepalive
          }}{{ t("common.seconds") }}</el-descriptions-item
        >
        <el-descriptions-item :label="t('connection.cleanSession')">{{
          connection.mqttConfig.cleanSession ? t("common.yes") : t("common.no")
        }}</el-descriptions-item>
      </template>
      <template
        v-if="
          [
            'kafka',
            'http',
            'websocket',
            'redis',
            'opcua',
            's7',
            'modbus',
            'tdengine',
          ].includes(connection.type) && connection.config
        "
      >
        <el-descriptions-item
          v-for="item in protocolConfigRows"
          :key="item.label"
          :label="item.label"
        >
          {{ item.value }}
        </el-descriptions-item>
      </template>
      <el-descriptions-item :label="t('connection.createdAt')">{{
        formatDate(connection.createdAt)
      }}</el-descriptions-item>
      <el-descriptions-item :label="t('connection.updatedAt')">{{
        formatDate(connection.updatedAt)
      }}</el-descriptions-item>
    </el-descriptions>
    <template #footer>
      <el-button @click="visible = false">{{ t("actions.close") }}</el-button>
    </template>
  </el-dialog>
</template>

<script setup lang="ts">
import { computed } from "vue";
import { getConnectionTypeConfig } from "@/config/connectionTypes";
import dayjs from "dayjs";
import { TIME_FORMAT } from "@/constants";
import { t } from "@/i18n/runtime";

const props = defineProps({
  modelValue: {
    type: Boolean,
    default: false,
  },
  connection: {
    type: Object,
    default: null,
  },
});

const emit = defineEmits(["update:modelValue"]);

const visible = computed({
  get: () => props.modelValue,
  set: (val) => emit("update:modelValue", val),
});

const getConnectionTypeLabel = (type) => {
  if (type === "relational" && props.connection?.relationalConfig) {
    const dbType = props.connection.relationalConfig.dbType;
    const config = getConnectionTypeConfig(dbType);
    return config ? config.label : dbType;
  }
  const labels = {
    relational: t("connection.relational"),
    mqtt: "MQTT",
    kafka: "Kafka",
    websocket: "WebSocket",
    redis: "Redis",
    opcua: "OPC UA",
    http: "HTTP",
    s7: "Siemens S7",
    modbus: "Modbus",
    tdengine: "TDengine",
  };
  return labels[type] || type;
};

const protocolConfigRows = computed(() => {
  const config = props.connection?.config || {};
  switch (props.connection?.type) {
    case "kafka":
      return [
        { label: "Broker", value: config.brokers || "-" },
        { label: "Topic", value: config.topic || "-" },
        { label: "Consumer Group", value: config.consumerGroup || "-" },
      ];
    case "http":
      return [
        { label: "Method", value: config.method || "GET" },
        { label: "URL", value: config.baseUrl || "-" },
      ];
    case "websocket":
      return [
        { label: "URL", value: config.url || "-" },
        { label: "Topic", value: config.topic || "-" },
      ];
    case "redis":
      return [
        { label: "Mode", value: config.mode || "standalone" },
        { label: "Address", value: config.address || "-" },
        { label: "Key Pattern", value: config.keyPattern || "*" },
      ];
    case "opcua":
      return [
        { label: "Endpoint", value: config.endpoint || "-" },
        { label: "Security Policy", value: config.securityPolicy || "None" },
        { label: "Security Mode", value: config.securityMode || "none" },
        { label: "Auth Type", value: config.authType || "anonymous" },
        {
          label: "Sampling",
          value: config.samplingMs ? `${config.samplingMs}ms` : "-",
        },
      ];
    case "s7":
      return [
        { label: "Host", value: config.host || "-" },
        { label: "Port", value: config.port || 102 },
        { label: "Rack", value: config.rack ?? 0 },
        { label: "Slot", value: config.slot ?? 1 },
        {
          label: "Poll Interval",
          value: config.pollIntervalMs ? `${config.pollIntervalMs}ms` : "-",
        },
      ];
    case "modbus":
      return [
        { label: "Mode", value: config.mode || "tcp" },
        {
          label: "Host",
          value: config.mode === "rtu" ? "RTU 串口" : config.host || "-",
        },
        {
          label: "Port",
          value: config.mode === "rtu" ? "-" : config.port || 502,
        },
        { label: "Slave ID", value: config.slaveId ?? 1 },
        { label: "Address", value: config.startAddress ?? 0 },
        { label: "Quantity", value: config.quantity ?? 1 },
      ];
    case "tdengine":
      return [
        { label: "DSN", value: config.dsn || "-" },
        { label: "Database", value: config.database || "-" },
        { label: "Timezone", value: config.timezone || "-" },
      ];
    default:
      return [];
  }
});

const getStatusLabel = (status) => {
  const normalized = ["connected", "disconnected", "error"].includes(status)
    ? status
    : "unknown";
  return t(`connection.statuses.${normalized}`);
};

const formatDate = (dateString) => {
  if (!dateString) return "-";
  const date = dayjs(dateString);
  return date.isValid() ? date.format(TIME_FORMAT) : "-";
};
</script>
