<template>
  <el-dialog
    v-model="visible"
    :title="t('connection.detailsTitle')"
    width="600px"
  >
    <el-descriptions :column="1" border v-if="connection">
      <el-descriptions-item :label="t('connection.name')">{{
        connection.name
      }}</el-descriptions-item>
      <el-descriptions-item :label="t('connection.connectionTypeLabel')">{{
        getConnectionTypeLabel(connection.type)
      }}</el-descriptions-item>
      <el-descriptions-item :label="t('connection.connectionStatus')">
        <el-tag
          :type="
            connection.status === 'connected'
              ? 'success'
              : connection.status === 'error'
                ? 'danger'
                : connection.status === 'disconnected'
                  ? 'warning'
                  : 'info'
          "
        >
          {{ getStatusLabel(connection.status) }}
        </el-tag>
      </el-descriptions-item>
      <template
        v-if="connection.type === 'relational' && connection.relationalConfig"
      >
        <el-descriptions-item :label="t('connection.dbType')">{{
          connection.relationalConfig.dbType
        }}</el-descriptions-item>
        <el-descriptions-item :label="t('connection.host')">{{
          connection.relationalConfig.host
        }}</el-descriptions-item>
        <el-descriptions-item :label="t('connection.port')">{{
          connection.relationalConfig.port
        }}</el-descriptions-item>
        <el-descriptions-item :label="t('connection.database')">{{
          connection.relationalConfig.database
        }}</el-descriptions-item>
        <el-descriptions-item :label="t('connection.username')">{{
          connection.relationalConfig.username
        }}</el-descriptions-item>
      </template>
      <template v-if="connection.type === 'mqtt' && connection.mqttConfig">
        <el-descriptions-item :label="t('connection.protocol')">{{
          connection.mqttConfig.protocol
        }}</el-descriptions-item>
        <el-descriptions-item :label="t('connection.brokerAddress')">{{
          connection.mqttConfig.brokerUrl
        }}</el-descriptions-item>
        <el-descriptions-item :label="t('connection.port')">{{
          connection.mqttConfig.port
        }}</el-descriptions-item>
        <el-descriptions-item :label="t('connection.clientId')">{{
          connection.mqttConfig.clientId || t("common.autoGenerated")
        }}</el-descriptions-item>
        <el-descriptions-item :label="t('connection.username')">{{
          connection.mqttConfig.username || "-"
        }}</el-descriptions-item>
        <el-descriptions-item :label="t('connection.qos')">{{
          connection.mqttConfig.qos
        }}</el-descriptions-item>
        <el-descriptions-item :label="t('connection.keepaliveSeconds')"
          >{{ connection.mqttConfig.keepalive
          }}{{ t("common.seconds") }}</el-descriptions-item
        >
        <el-descriptions-item :label="t('connection.cleanSession')">{{
          connection.mqttConfig.cleanSession ? t("common.yes") : t("common.no")
        }}</el-descriptions-item>
      </template>
      <el-descriptions-item :label="t('connection.createdAt')">{{
        formatDate(connection.createdAt)
      }}</el-descriptions-item>
      <el-descriptions-item :label="t('connection.updatedAt')">{{
        formatDate(connection.updatedAt)
      }}</el-descriptions-item>
    </el-descriptions>
    <template #footer>
      <el-button @click="visible = false">{{ t("actions.close") }}</el-button>
    </template>
  </el-dialog>
</template>

<script setup lang="ts">
import { computed } from "vue";
import { getConnectionTypeConfig } from "@/config/connectionTypes";
import dayjs from "dayjs";
import { TIME_FORMAT } from "@/constants";
import { t } from "@/i18n/runtime";

const props = defineProps({
  modelValue: {
    type: Boolean,
    default: false,
  },
  connection: {
    type: Object,
    default: null,
  },
});

const emit = defineEmits(["update:modelValue"]);

const visible = computed({
  get: () => props.modelValue,
  set: (val) => emit("update:modelValue", val),
});

const getConnectionTypeLabel = (type) => {
  if (type === "relational" && props.connection?.relationalConfig) {
    const dbType = props.connection.relationalConfig.dbType;
    const config = getConnectionTypeConfig(dbType);
    return config ? config.label : dbType;
  }
  const labels = {
    relational: t("connection.relational"),
    mqtt: "MQTT",
    websocket: "WebSocket",
    opcua: "OPC UA",
    http: "HTTP",
  };
  return labels[type] || type;
};

const getStatusLabel = (status) => {
  const normalized = ["connected", "disconnected", "error"].includes(status)
    ? status
    : "unknown";
  return t(`connection.statuses.${normalized}`);
};

const formatDate = (dateString) => {
  if (!dateString) return "-";
  const date = dayjs(dateString);
  return date.isValid() ? date.format(TIME_FORMAT) : "-";
};
</script>
