using System.Text.Json; using InduForge.Collector.Adapters.Hsl; using InduForge.Collector.Contracts;
namespace InduForge.Collector.Drivers.Yaskawa.Tests;
public sealed class YaskawaDriverTests
{
    [Fact] public void UsesDemoDefaults(){var options=YaskawaOptions.Parse(Profile(new{host="127.0.0.1"}),HslYaskawaTransport.Tcp);Assert.Equal(9999,options.Port);Assert.Equal((byte)1,options.CpuFrom);Assert.Equal((byte)2,options.CpuTo);Assert.Equal(HslDataFormat.CDAB,options.DataFormat);}
    [Theory][InlineData("100")][InlineData("x=9;100")][InlineData("M100.0")][InlineData("mfc=67;x=61;0")] public void AcceptsDemoAddresses(string address)=>Assert.Equal(address,YaskawaAddress.Parse(Point(address)).Address);
    [Fact] public async Task ReusesClientAndIsolatesFailures(){var client=new FakeClient();var driver=new YaskawaMemobusTcpDriver(new Factory(client));await using var session=await driver.OpenSessionAsync(Profile(new{host="127.0.0.1"}),CancellationToken.None);var result=await((IPointReaderSession)session).ReadAsync(new ReadRequest([Point("100"),Point("bad address")]),CancellationToken.None);Assert.Single(client.Requests);Assert.True(result.Values[0].Succeeded);Assert.Equal("YASKAWA_ADDRESS_INVALID",result.Values[1].ErrorCode);}
    static ConnectionProfile Profile(object config)=>new("yaskawa",JsonSerializer.SerializeToElement(config),JsonSerializer.SerializeToElement(new{})); static PointReadRequest Point(string address)=>new(address,JsonSerializer.SerializeToElement(new{address}),"int16",1,JsonSerializer.SerializeToElement(new{}));
    sealed class Factory(IHslYaskawaClient client):IHslYaskawaClientFactory{public IHslYaskawaClient Create(HslYaskawaClientOptions options)=>client;} sealed class FakeClient:IHslYaskawaClient{public List<HslYaskawaReadRequest> Requests{get;}=[];public bool IsConnected{get;private set;}public Task<HslOperationResult> ConnectAsync(CancellationToken token){IsConnected=true;return Task.FromResult(HslOperationResult.Success());}public Task<HslOperationResult> CloseAsync(CancellationToken token){IsConnected=false;return Task.FromResult(HslOperationResult.Success());}public Task<HslReadResult> ReadAsync(HslYaskawaReadRequest request,CancellationToken token){Requests.Add(request);return Task.FromResult(HslReadResult.Success((short)1));}public async ValueTask DisposeAsync(){if(IsConnected)await CloseAsync(CancellationToken.None);}}
}
