/** 展示类 manifest：2D 绘图（Diagram2D）与文本（Text）。由 index 在 Button 之前加载。 */
import { registerManifest } from "./manifest-registry";

// Diagram2D 2D流程图组件
registerManifest({
  type: "Diagram2D",
  name: "2D流程图",
  category: "绘图",
  props: [
    {
      name: "diagramId",
      type: "string",
      label: "绘图ID",
      group: "内部",
      defaultValue: "",
    },
    {
      name: "showGrid",
      type: "boolean",
      label: "显示网格",
      group: "显示",
      defaultValue: true,
    },
    {
      name: "gridSize",
      type: "number",
      label: "网格大小",
      group: "显示",
      defaultValue: 10,
      min: 5,
      max: 50,
    },
    {
      name: "background",
      type: "color",
      label: "背景色",
      group: "样式",
      defaultValue: "#ffffff",
    },
    {
      name: "snapToGrid",
      type: "boolean",
      label: "吸附网格",
      group: "编辑",
      defaultValue: true,
    },
  ],
});

// Text 文本组件
registerManifest({
  type: "Text",
  name: "文本",
  category: "PC端组件",
  props: [
    {
      name: "text",
      type: "string",
      label: "文本内容",
      group: "基础",
      defaultValue: "文本内容",
      placeholder: "请输入文本",
    },
    {
      name: "tag",
      type: "enum",
      label: "标签类型",
      group: "基础",
      defaultValue: "span",
      options: [
        { label: "span", value: "span" },
        { label: "div", value: "div" },
        { label: "p", value: "p" },
        { label: "h1", value: "h1" },
        { label: "h2", value: "h2" },
        { label: "h3", value: "h3" },
        { label: "h4", value: "h4" },
        { label: "h5", value: "h5" },
        { label: "h6", value: "h6" },
      ],
    },
    {
      name: "fontSize",
      type: "number",
      label: "字号(px)",
      group: "字体",
      defaultValue: 14,
      min: 8,
      max: 200,
      step: 1,
    },
    {
      name: "fontWeight",
      type: "enum",
      label: "字重",
      group: "字体",
      defaultValue: "normal",
      options: [
        { label: "100-细", value: "100" },
        { label: "300-较细", value: "300" },
        { label: "正常", value: "normal" },
        { label: "500-中等", value: "500" },
        { label: "粗体", value: "bold" },
        { label: "900-最粗", value: "900" },
      ],
    },
    {
      name: "fontFamily",
      type: "string",
      label: "字体",
      group: "字体",
      defaultValue: "",
      placeholder: "如: Arial, 微软雅黑",
    },
    {
      name: "color",
      type: "color",
      label: "文字颜色",
      group: "颜色",
      defaultValue: "#333333",
    },
    {
      name: "textAlign",
      type: "enum",
      label: "对齐方式",
      group: "布局",
      defaultValue: "left",
      options: [
        { label: "左对齐", value: "left" },
        { label: "居中", value: "center" },
        { label: "右对齐", value: "right" },
        { label: "两端对齐", value: "justify" },
      ],
    },
    {
      name: "lineHeight",
      type: "number",
      label: "行高",
      group: "布局",
      defaultValue: 1.5,
      min: 0.5,
      max: 5,
      step: 0.1,
    },
    {
      name: "letterSpacing",
      type: "number",
      label: "字间距(px)",
      group: "布局",
      defaultValue: 0,
      min: -5,
      max: 20,
      step: 0.5,
    },
    {
      name: "truncate",
      type: "boolean",
      label: "单行省略",
      group: "溢出",
      defaultValue: false,
    },
    {
      name: "lineClamp",
      type: "number",
      label: "最大行数",
      group: "溢出",
      defaultValue: 0,
      min: 0,
      max: 20,
      placeholder: "0表示不限制",
    },
    {
      name: "wordBreak",
      type: "enum",
      label: "换行规则",
      group: "溢出",
      defaultValue: "normal",
      options: [
        { label: "正常", value: "normal" },
        { label: "断词", value: "break-all" },
        { label: "保持完整", value: "keep-all" },
      ],
    },
  ],
});
