using System.Text.Json;using InduForge.Collector.Adapters.Hsl;using InduForge.Collector.Contracts;
namespace InduForge.Collector.Drivers.ToyoPuc.Tests;
public sealed class ToyoPucDriverTests
{
 [Fact]public void UsesDemoDefaults(){var options=ToyoPucOptions.Parse(Profile(new{host="127.0.0.1"}));Assert.Equal(6000,options.Port);}
 [Theory][InlineData("d000a","DA")][InlineData("PRG=01;em0010","prg=1;EM10")][InlineData("GX00FF","GXFF")]public void NormalizesAddresses(string value,string expected)=>Assert.Equal(expected,ToyoPucAddress.Parse(Point(value)).Address);
 [Fact]public async Task IsolatesInvalidAddress(){var client=new FakeClient();var driver=new ToyoPucDriver(new Factory(client));await using var session=await driver.OpenSessionAsync(Profile(new{host="127.0.0.1"}),CancellationToken.None);var result=await((IPointReaderSession)session).ReadAsync(new ReadRequest([Point("D0"),Point("Q0")]),CancellationToken.None);Assert.Single(client.Requests);Assert.Equal("TOYO_PUC_ADDRESS_INVALID",result.Values[1].ErrorCode);}
 static ConnectionProfile Profile(object config)=>new("toyo",JsonSerializer.SerializeToElement(config),JsonSerializer.SerializeToElement(new{}));static PointReadRequest Point(string address)=>new(address,JsonSerializer.SerializeToElement(new{address}),"int16",1,JsonSerializer.SerializeToElement(new{}));sealed class Factory(IHslSpecializedNetworkClient client):IHslSpecializedNetworkClientFactory{public IHslSpecializedNetworkClient Create(HslSpecializedNetworkClientOptions options)=>client;}sealed class FakeClient:IHslSpecializedNetworkClient{public List<HslSpecializedNetworkReadRequest> Requests{get;}=[];public bool IsConnected{get;private set;}public Task<HslOperationResult> ConnectAsync(CancellationToken token){IsConnected=true;return Task.FromResult(HslOperationResult.Success());}public Task<HslOperationResult> CloseAsync(CancellationToken token){IsConnected=false;return Task.FromResult(HslOperationResult.Success());}public Task<HslReadResult> ReadAsync(HslSpecializedNetworkReadRequest request,CancellationToken token){Requests.Add(request);return Task.FromResult(HslReadResult.Success((short)1));}public async ValueTask DisposeAsync(){if(IsConnected)await CloseAsync(CancellationToken.None);}}
}
