package service

import (
	"strings"
	"testing"
)

func TestNormalizeBuiltinStoreCreateInput(t *testing.T) {
	input := CreateConnectionInput{
		Name:   " IF关系库 ",
		Type:   "builtin.relation",
		Status: "",
		Config: map[string]any{
			"host":        "127.0.0.1",
			"port":        5432,
			"description": "业务表",
		},
	}

	result, err := normalizeBuiltinStoreCreateInput("11111111-1111-1111-1111-111111111111", input)
	if err != nil {
		t.Fatalf("normalize builtin input failed: %v", err)
	}

	if result.Type != "builtin.relation" || result.Category != "builtin" {
		t.Fatalf("unexpected type/category: %s/%s", result.Type, result.Category)
	}
	if result.Status != "connected" {
		t.Fatalf("expected connected status, got %q", result.Status)
	}
	if _, ok := result.Config["host"]; ok {
		t.Fatal("builtin store config must not keep host")
	}
	if _, ok := result.Config["port"]; ok {
		t.Fatal("builtin store config must not keep port")
	}
	if result.Config["store"] != "relation" {
		t.Fatalf("expected relation store, got %#v", result.Config["store"])
	}
	runtimeKey, _ := result.Config["runtimeKey"].(string)
	if !strings.HasPrefix(runtimeKey, "rel_") {
		t.Fatalf("expected rel_ runtime key, got %#v", result.Config["runtimeKey"])
	}
	expectedSchema := "p_11111111_1111_1111_1111_111111111111_" + runtimeKey
	if result.Config["devSchema"] != expectedSchema {
		t.Fatalf("unexpected dev schema: %#v", result.Config["devSchema"])
	}
}

func TestNormalizeBuiltinStoreCreateInputGeneratesRuntimeKey(t *testing.T) {
	input := CreateConnectionInput{
		Name: "订单库",
		Type: "builtin.relation",
		Config: map[string]any{
			"runtimeKey": "user_supplied",
			"devSchema":  "p_leak",
			"host":       "127.0.0.1",
		},
	}

	result, err := normalizeBuiltinStoreCreateInput("11111111-1111-1111-1111-111111111111", input)
	if err != nil {
		t.Fatalf("normalize builtin input failed: %v", err)
	}

	runtimeKey, _ := result.Config["runtimeKey"].(string)
	if !strings.HasPrefix(runtimeKey, "rel_") {
		t.Fatalf("expected generated rel_ runtimeKey, got %q", runtimeKey)
	}
	if runtimeKey == "user_supplied" {
		t.Fatal("runtimeKey must be generated by service")
	}
	if result.Config["devSchema"] == "p_leak" {
		t.Fatal("devSchema must not keep user supplied value")
	}
	if _, ok := result.Config["host"]; ok {
		t.Fatal("builtin config must drop internal host")
	}
}

func TestNormalizeBuiltinMessageStoreDropsTopicDefaults(t *testing.T) {
	input := CreateConnectionInput{
		Name: "IF消息库",
		Type: "builtin.message",
		Config: map[string]any{
			"topic":         "mock-data",
			"defaultTopic":  "mock-data",
			"samplePayload": map[string]any{"value": 1},
			"topicPrefix":   "ifdev",
		},
	}

	result, err := normalizeBuiltinStoreCreateInput("11111111-1111-1111-1111-111111111111", input)
	if err != nil {
		t.Fatalf("normalize builtin message input failed: %v", err)
	}
	if result.Config["store"] != "message" {
		t.Fatalf("expected message store, got %#v", result.Config["store"])
	}
	for _, key := range []string{"topic", "defaultTopic", "samplePayload", "topicPrefix"} {
		if _, ok := result.Config[key]; ok {
			t.Fatalf("builtin message config must not keep %s", key)
		}
	}
}

func TestBuiltinStoreTypeGuards(t *testing.T) {
	for _, storeType := range []string{
		"builtin.relation",
		"builtin.timeseries",
		"builtin.realtime",
		"builtin.message",
	} {
		if !isBuiltinStoreType(storeType) {
			t.Fatalf("expected builtin type %s", storeType)
		}
	}
	if isBuiltinStoreType("redis") {
		t.Fatal("redis must remain external protocol type")
	}
}
