using System.Text.Json; using InduForge.Collector.Adapters.Hsl; using InduForge.Collector.Contracts; using Xunit;
namespace InduForge.Collector.Drivers.Yokogawa.Tests;
public sealed class YokogawaDriverTests
{
    [Fact] public void UsesDemoDefaults() { var o = YokogawaOptions.Parse(Profile(new { host = "127.0.0.1" })); Assert.Equal(12289, o.Port); Assert.Equal((byte)1, o.CpuNumber); Assert.Equal(HslDataFormat.CDAB, o.DataFormat); Assert.Equal(5000, o.ConnectTimeoutMilliseconds); Assert.Equal(10000, o.ReceiveTimeoutMilliseconds); }
    [Theory] [InlineData("d100", "int16", "D100")] [InlineData("cpu=02;y100", "bool", "cpu=2;Y100")] [InlineData("special:cpu=1;unit=0;slot=1;100", "int16", "Special:cpu=1;unit=0;slot=1;100")] public void NormalizesAddresses(string a,string t,string e)=>Assert.Equal(e,YokogawaAddress.Parse(Point(a,t)).Address);
    [Fact] public async Task ReusesClientAndIsolatesFailures(){var c=new FakeClient();var d=new YokogawaLinkTcpDriver(new Factory(c));await using var s=await d.OpenSessionAsync(Profile(new{host="127.0.0.1"}),CancellationToken.None);var r=await((IPointReaderSession)s).ReadAsync(new ReadRequest([Point("D100","int16"),Point("D101","int16"),Point("bad","int16")]),CancellationToken.None);Assert.Equal(2,c.Requests.Count);Assert.True(r.Values[0].Succeeded);Assert.Equal("YOKOGAWA_ADDRESS_INVALID",r.Values[2].ErrorCode);}
    static ConnectionProfile Profile(object c)=>new("yokogawa",JsonSerializer.SerializeToElement(c),JsonSerializer.SerializeToElement(new{})); static PointReadRequest Point(string a,string t)=>new(a,JsonSerializer.SerializeToElement(new{address=a}),t,1,JsonSerializer.SerializeToElement(new{}));
    sealed class Factory(IHslYokogawaClient c):IHslYokogawaClientFactory{public IHslYokogawaClient Create(HslYokogawaClientOptions o)=>c;} sealed class FakeClient:IHslYokogawaClient{public List<HslYokogawaReadRequest> Requests{get;}=[];public bool IsConnected{get;private set;}public Task<HslOperationResult> ConnectAsync(CancellationToken c){IsConnected=true;return Task.FromResult(HslOperationResult.Success());}public Task<HslOperationResult> CloseAsync(CancellationToken c){IsConnected=false;return Task.FromResult(HslOperationResult.Success());}public Task<HslReadResult> ReadAsync(HslYokogawaReadRequest r,CancellationToken c){Requests.Add(r);return Task.FromResult(r.Address=="D100"?HslReadResult.Success((short)1):HslReadResult.Failure("READ_FAILED","失败",false));}public async ValueTask DisposeAsync(){if(IsConnected)await CloseAsync(CancellationToken.None);}}
}
