#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../../.." && pwd)"
WINDOWS_INSTALLER="$ROOT/runtime/node_agent/packaging/install-windows.ps1"
WINDOWS_UNINSTALLER="$ROOT/runtime/node_agent/packaging/uninstall-windows.ps1"
LINUX_INSTALLER="$ROOT/runtime/node_agent/packaging/install-linux.sh"
test -s "$ROOT/runtime/node_agent/packaging/README-linux.md"
test -s "$ROOT/runtime/node_agent/packaging/README-windows.md"
rg -q 'node-agent.exe" --service' "$WINDOWS_INSTALLER"
rg -q 'NODE_AGENT_CONFIG=' "$WINDOWS_INSTALLER"
rg -q 'NODE_AGENT_WORKDIR=' "$WINDOWS_INSTALLER"
rg -q 'NODE_AGENT_DATA_DIR=' "$WINDOWS_INSTALLER"
rg -q 'EnrollmentCode' "$WINDOWS_INSTALLER"
rg -q 'Stop-ServiceForUpdate' "$WINDOWS_INSTALLER"
rg -q 'Invoke-Sc config' "$WINDOWS_INSTALLER"
rg -q 'WaitForStatus' "$WINDOWS_INSTALLER"
rg -q 'Remove-AgentService' "$WINDOWS_UNINSTALLER"
rg -q 'marked-for-delete' "$WINDOWS_UNINSTALLER"
rg -q -- '--server-url' "$LINUX_INSTALLER"
rg -q -- '--enrollment-code' "$LINUX_INSTALLER"
echo "installer static verification passed"
